using System.Collections.Generic;
using AetherArk.Core;

namespace AetherArk.Content
{
    /// <summary>Enemy configs. Generated from tools/gen_enemies.py; edit the table, not this file.</summary>
    public static class EnemyLibrary
    {
        public static void AddAll(List<EnemyDefinition> result)
        {
            result.Add(new EnemyDefinition { id = "enemy_cutter", silhouette = "enemy_cutter", nameKey = "ship.enemy_cutter", displayName = "enemy_cutter", tier = 1, weight = 40, minRegion = 1, hull = 24f, armor = 10f, ward = 8f, coreOutput = 9, boarding = false, weapons = new[] { "aether_cannon" }, power = new[] { 1, 0, 1, 2, 1, 3, 0, 0, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 4, 2, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_cutter_lance", silhouette = "enemy_cutter", nameKey = "ship.enemy_cutter_lance", displayName = "Imperial Lance Cutter", tier = 1, weight = 20, minRegion = 2, hull = 24f, armor = 10f, ward = 10f, coreOutput = 9, boarding = false, weapons = new[] { "ward_lance" }, power = new[] { 1, 0, 1, 2, 1, 3, 0, 0, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 4, 2, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_cutter_veteran", silhouette = "enemy_cutter", nameKey = "ship.enemy_cutter_veteran", displayName = "Imperial Veteran Cutter", tier = 1, weight = 15, minRegion = 3, hull = 27f, armor = 12f, ward = 9f, coreOutput = 10, boarding = false, weapons = new[] { "heavy_cannon" }, power = new[] { 1, 0, 1, 2, 1, 4, 0, 0, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 4, 2, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_carrier", silhouette = "enemy_carrier", nameKey = "ship.enemy_carrier", displayName = "enemy_carrier", tier = 1, weight = 20, minRegion = 1, hull = 28f, armor = 12f, ward = 10f, coreOutput = 10, boarding = false, weapons = new[] { "flak_battery" }, power = new[] { 1, 0, 1, 1, 1, 1, 3, 1, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 4, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_carrier_strike", silhouette = "enemy_carrier", nameKey = "ship.enemy_carrier_strike", displayName = "Imperial Strike Wing Carrier", tier = 1, weight = 15, minRegion = 2, hull = 28f, armor = 12f, ward = 10f, coreOutput = 11, boarding = false, weapons = new[] { "aether_cannon" }, power = new[] { 1, 0, 1, 1, 1, 1, 4, 1, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 4, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_carrier_veteran", silhouette = "enemy_carrier", nameKey = "ship.enemy_carrier_veteran", displayName = "Imperial Veteran Carrier", tier = 1, weight = 10, minRegion = 3, hull = 31f, armor = 14f, ward = 11f, coreOutput = 11, boarding = false, weapons = new[] { "flak_curtain" }, power = new[] { 1, 0, 1, 1, 1, 2, 3, 1, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 4, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_scout", silhouette = "enemy_scout", nameKey = "ship.enemy_scout", displayName = "enemy_scout", tier = 1, weight = 20, minRegion = 1, hull = 20f, armor = 8f, ward = 8f, coreOutput = 11, boarding = false, weapons = new[] { "bolt_thrower" }, power = new[] { 1, 0, 1, 3, 1, 2, 0, 2, 0, 1 }, maxPower = new[] { 2, 0, 3, 4, 3, 3, 1, 3, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_scout_lance", silhouette = "enemy_scout", nameKey = "ship.enemy_scout_lance", displayName = "Imperial Lance Frigate", tier = 1, weight = 15, minRegion = 2, hull = 20f, armor = 8f, ward = 10f, coreOutput = 11, boarding = false, weapons = new[] { "ward_lance" }, power = new[] { 1, 0, 1, 3, 1, 2, 0, 2, 0, 1 }, maxPower = new[] { 2, 0, 3, 4, 3, 3, 1, 3, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_scout_hunter", silhouette = "enemy_scout", nameKey = "ship.enemy_scout_hunter", displayName = "Imperial Hunter Frigate", tier = 1, weight = 15, minRegion = 3, hull = 22f, armor = 9f, ward = 9f, coreOutput = 12, boarding = false, weapons = new[] { "rail_harpoon" }, power = new[] { 1, 0, 1, 3, 1, 2, 0, 3, 0, 1 }, maxPower = new[] { 2, 0, 3, 4, 3, 3, 1, 3, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_boarder", silhouette = "enemy_boarder", nameKey = "ship.enemy_boarder", displayName = "enemy_boarder", tier = 1, weight = 20, minRegion = 1, hull = 26f, armor = 12f, ward = 6f, coreOutput = 9, boarding = true, weapons = new[] { "ember_mortar" }, power = new[] { 1, 0, 1, 1, 1, 1, 2, 0, 1, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 3, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_boarder_assault", silhouette = "enemy_boarder", nameKey = "ship.enemy_boarder_assault", displayName = "Imperial Assault Barge", tier = 1, weight = 15, minRegion = 2, hull = 26f, armor = 12f, ward = 6f, coreOutput = 10, boarding = true, weapons = new[] { "ember_mortar" }, power = new[] { 1, 0, 1, 1, 1, 1, 3, 0, 1, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 3, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_boarder_veteran", silhouette = "enemy_boarder", nameKey = "ship.enemy_boarder_veteran", displayName = "Imperial Veteran Barge", tier = 1, weight = 10, minRegion = 3, hull = 29f, armor = 13f, ward = 7f, coreOutput = 11, boarding = true, weapons = new[] { "breacher_charges" }, power = new[] { 1, 0, 1, 1, 1, 2, 3, 0, 1, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 3, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_lancer", silhouette = "enemy_lancer", nameKey = "ship.enemy_lancer", displayName = "Imperial Lancer Destroyer", tier = 1, weight = 20, minRegion = 2, hull = 22f, armor = 8f, ward = 10f, coreOutput = 10, boarding = false, weapons = new[] { "ward_lance" }, power = new[] { 1, 0, 1, 2, 2, 2, 0, 1, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 1, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_lancer_twin", silhouette = "enemy_lancer", nameKey = "ship.enemy_lancer_twin", displayName = "Imperial Twin-Lance Destroyer", tier = 1, weight = 15, minRegion = 3, hull = 24f, armor = 9f, ward = 11f, coreOutput = 11, boarding = false, weapons = new[] { "sky_lance" }, power = new[] { 1, 0, 1, 2, 2, 3, 0, 1, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 1, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_minelayer", silhouette = "enemy_minelayer", nameKey = "ship.enemy_minelayer", displayName = "Imperial Minelayer", tier = 1, weight = 15, minRegion = 2, hull = 22f, armor = 12f, ward = 6f, coreOutput = 9, boarding = false, weapons = new[] { "breacher_charges" }, power = new[] { 1, 0, 1, 1, 1, 2, 0, 1, 1, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 1, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_minelayer_ripper", silhouette = "enemy_minelayer", nameKey = "ship.enemy_minelayer_ripper", displayName = "Imperial Ripper Minelayer", tier = 1, weight = 15, minRegion = 3, hull = 24f, armor = 13f, ward = 7f, coreOutput = 10, boarding = false, weapons = new[] { "hull_ripper" }, power = new[] { 1, 0, 1, 1, 1, 3, 0, 1, 1, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 1, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_firebrand", silhouette = "enemy_firebrand", nameKey = "ship.enemy_firebrand", displayName = "Imperial Firebrand", tier = 1, weight = 15, minRegion = 2, hull = 24f, armor = 10f, ward = 8f, coreOutput = 9, boarding = false, weapons = new[] { "ember_mortar" }, power = new[] { 1, 0, 1, 2, 1, 2, 0, 1, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 1, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_firebrand_hellfire", silhouette = "enemy_firebrand", nameKey = "ship.enemy_firebrand_hellfire", displayName = "Imperial Hellfire Firebrand", tier = 1, weight = 15, minRegion = 4, hull = 26f, armor = 11f, ward = 9f, coreOutput = 10, boarding = false, weapons = new[] { "hellfire_mortar" }, power = new[] { 1, 0, 1, 2, 1, 3, 0, 1, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 1, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_cruiser", silhouette = "enemy_cruiser", nameKey = "ship.enemy_cruiser", displayName = "enemy_cruiser", tier = 2, weight = 60, minRegion = 1, hull = 34f, armor = 18f, ward = 12f, coreOutput = 11, boarding = false, weapons = new[] { "heavy_cannon" }, power = new[] { 1, 0, 1, 2, 2, 3, 1, 0, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 4, 2, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_cruiser_missile", silhouette = "enemy_cruiser", nameKey = "ship.enemy_cruiser_missile", displayName = "Imperial Missile Cruiser", tier = 2, weight = 25, minRegion = 2, hull = 34f, armor = 18f, ward = 12f, coreOutput = 11, boarding = false, weapons = new[] { "storm_missiles" }, power = new[] { 1, 0, 1, 2, 2, 3, 1, 0, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 4, 2, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_cruiser_veteran", silhouette = "enemy_cruiser", nameKey = "ship.enemy_cruiser_veteran", displayName = "Imperial Veteran Cruiser", tier = 2, weight = 20, minRegion = 3, hull = 37f, armor = 20f, ward = 13f, coreOutput = 12, boarding = false, weapons = new[] { "siege_cannon" }, power = new[] { 1, 0, 1, 2, 2, 4, 1, 0, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 4, 2, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_monitor", silhouette = "enemy_monitor", nameKey = "ship.enemy_monitor", displayName = "enemy_monitor", tier = 2, weight = 40, minRegion = 1, hull = 30f, armor = 22f, ward = 16f, coreOutput = 11, boarding = false, weapons = new[] { "aether_cannon" }, power = new[] { 1, 0, 1, 1, 3, 2, 0, 2, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 4, 4, 1, 3, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_monitor_lance", silhouette = "enemy_monitor", nameKey = "ship.enemy_monitor_lance", displayName = "Imperial Lance Monitor", tier = 2, weight = 20, minRegion = 2, hull = 30f, armor = 22f, ward = 16f, coreOutput = 11, boarding = false, weapons = new[] { "resonance_lance" }, power = new[] { 1, 0, 1, 1, 3, 2, 0, 2, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 4, 4, 1, 3, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_monitor_veteran", silhouette = "enemy_monitor", nameKey = "ship.enemy_monitor_veteran", displayName = "Imperial Veteran Monitor", tier = 2, weight = 15, minRegion = 3, hull = 33f, armor = 24f, ward = 18f, coreOutput = 12, boarding = false, weapons = new[] { "heavy_cannon" }, power = new[] { 1, 0, 1, 1, 3, 3, 0, 2, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 4, 4, 1, 3, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_dreadnought", silhouette = "enemy_dreadnought", nameKey = "ship.enemy_dreadnought", displayName = "Imperial Dreadnought", tier = 2, weight = 20, minRegion = 2, hull = 34f, armor = 22f, ward = 12f, coreOutput = 11, boarding = false, weapons = new[] { "heavy_cannon" }, power = new[] { 1, 0, 1, 1, 2, 3, 1, 1, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 5, 2, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_dreadnought_bastion", silhouette = "enemy_dreadnought", nameKey = "ship.enemy_dreadnought_bastion", displayName = "Imperial Bastion Dreadnought", tier = 2, weight = 15, minRegion = 4, hull = 40f, armor = 26f, ward = 14f, coreOutput = 12, boarding = false, weapons = new[] { "siege_cannon" }, power = new[] { 1, 0, 1, 1, 3, 3, 1, 1, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 4, 5, 2, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_hive", silhouette = "enemy_hive", nameKey = "ship.enemy_hive", displayName = "Imperial Hive Carrier", tier = 2, weight = 20, minRegion = 2, hull = 32f, armor = 16f, ward = 12f, coreOutput = 11, boarding = true, weapons = new[] { "flak_battery" }, power = new[] { 1, 0, 1, 1, 1, 1, 3, 1, 1, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 4, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_hive_swarm", silhouette = "enemy_hive", nameKey = "ship.enemy_hive_swarm", displayName = "Imperial Swarm Carrier", tier = 2, weight = 15, minRegion = 4, hull = 34f, armor = 17f, ward = 13f, coreOutput = 13, boarding = true, weapons = new[] { "rocket_pod" }, power = new[] { 1, 0, 1, 1, 1, 2, 4, 1, 1, 1 }, maxPower = new[] { 2, 0, 3, 3, 3, 3, 4, 2, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_wraith", silhouette = "enemy_wraith", nameKey = "ship.enemy_wraith", displayName = "Imperial Wraith", tier = 2, weight = 20, minRegion = 3, hull = 26f, armor = 12f, ward = 14f, coreOutput = 12, boarding = false, weapons = new[] { "rail_harpoon" }, power = new[] { 1, 0, 1, 4, 1, 2, 0, 2, 0, 1 }, maxPower = new[] { 2, 0, 3, 4, 3, 3, 1, 3, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_wraith_ghost", silhouette = "enemy_wraith", nameKey = "ship.enemy_wraith_ghost", displayName = "Imperial Ghost Wraith", tier = 2, weight = 15, minRegion = 4, hull = 28f, armor = 13f, ward = 15f, coreOutput = 13, boarding = false, weapons = new[] { "gate_piercer" }, power = new[] { 1, 0, 1, 4, 1, 2, 0, 3, 0, 1 }, maxPower = new[] { 2, 0, 3, 4, 3, 3, 1, 3, 1, 2 } });
            result.Add(new EnemyDefinition { id = "enemy_gate_warden", silhouette = "enemy_warden", nameKey = "ship.enemy_gate_warden", displayName = "Gate Warden \"Undying Oath\"", tier = 3, weight = 1, minRegion = 6, hull = 46f, armor = 28f, ward = 20f, coreOutput = 15, boarding = true, weapons = new[] { "siege_cannon", "resonance_lance" }, power = new[] { 1, 0, 1, 1, 3, 4, 2, 2, 0, 1 }, maxPower = new[] { 2, 0, 3, 3, 4, 5, 3, 3, 1, 2 } });
        }
    }
}
