namespace AetherArk.Content
{
    /// <summary>Event strings. Generated from tools/gen_events.py data; keep in sync with EncounterLibrary.</summary>
    public sealed partial class LocalizationService
    {
        private void AddEncounterStrings()
        {
            Add("enc.burning_ferry.title", "불타는 연락선", "THE BURNING FERRY");
            Add("enc.burning_ferry.body", "엔진 화재가 번진 연락선이 구름 위를 헤맵니다. 갑판에 승객이 몰려 있고, 불길은 몇 분 안에 연료고에 닿을 것입니다.", "A ferry drifts above the clouds with an engine fire spreading toward its fuel bunker. Passengers crowd the deck; you have minutes.");
            Add("enc.burning_ferry.teams", "소화반을 보내 차분히 구조한다 (보급 1)", "Send fire teams and evacuate methodically (1 supply)");
            Add("enc.burning_ferry.teams.r", "소화반이 불길을 잡는 동안 승객 40명이 옮겨 탔습니다.", "Fire teams hold the blaze while forty passengers cross.");
            Add("enc.burning_ferry.dash", "선체를 붙이고 전원 탈출시킨다 — 위험한 접근", "Lash hulls and take everyone — a dangerous approach");
            Add("enc.burning_ferry.dash.r", "무모했지만 통했습니다. 70명이 살았고 선단이 환호합니다.", "Reckless, but it works. Seventy are saved and the convoy cheers.");
            Add("enc.burning_ferry.dash_fail", "연료고 폭발", "The bunker detonates");
            Add("enc.burning_ferry.dash_fail.r", "연료고가 터지며 선체가 그을렸습니다. 20명만 구했습니다.", "The bunker blows; the hull is scorched and only twenty are pulled clear.");
            Add("enc.burning_ferry.leave", "거리를 둔다", "Keep your distance");
            Add("enc.burning_ferry.leave.r", "폭발의 빛이 구름을 물들이고, 선단은 침묵합니다.", "The explosion lights the clouds, and the convoy falls silent.");
            Add("enc.ice_locked_lifeboats.title", "결빙된 구명정", "ICE-LOCKED LIFEBOATS");
            Add("enc.ice_locked_lifeboats.body", "얼어붙은 구명정 세 척이 빙운 속에 갇혀 있습니다. 안에서 두드리는 소리가 들립니다.", "Three lifeboats hang frozen inside an ice cloud. Something knocks from within.");
            Add("enc.ice_locked_lifeboats.thaw", "[드워프] 용광로 배관으로 천천히 녹인다 (보급 1)", "[Dwarf] Thaw them with forge lines (1 supply)");
            Add("enc.ice_locked_lifeboats.thaw.r", "드워프 기술자들이 얼음을 녹여 30명을 무사히 데려왔습니다.", "Dwarven hands melt the ice away and thirty come aboard unharmed.");
            Add("enc.ice_locked_lifeboats.blast", "에테르로 얼음을 깨뜨린다 (에테르 1)", "Crack the ice with an aether pulse (1 aether)");
            Add("enc.ice_locked_lifeboats.blast.r", "얼음이 깨지고 구명정과 장비를 회수했습니다.", "The ice shatters; you recover the boats and their gear.");
            Add("enc.ice_locked_lifeboats.leave", "두드림을 뒤로하고 떠난다", "Leave the knocking behind");
            Add("enc.ice_locked_lifeboats.leave.r", "두드리는 소리가 잦아들 때까지 아무도 말을 하지 않았습니다.", "No one speaks until the knocking fades.");
            Add("enc.mutiny_transport.title", "반란 수송선", "THE MUTINOUS TRANSPORT");
            Add("enc.mutiny_transport.body", "수송선의 승무원이 선장을 가두고 선단 합류를 요구합니다. 승객들은 겁에 질려 있습니다.", "A transport's crew has locked up their captain and demand to join the convoy. The passengers are terrified.");
            Add("enc.mutiny_transport.intimidate", "[오크] 무장 승무원을 보내 질서를 잡는다", "[Orc] Send armed crew to restore order");
            Add("enc.mutiny_transport.intimidate.r", "반란자들은 오크 해병을 보자마자 무기를 내렸습니다.", "The mutineers drop their weapons the moment the orc marines board.");
            Add("enc.mutiny_transport.negotiate", "보급 2를 주고 협상한다", "Negotiate with 2 supplies");
            Add("enc.mutiny_transport.negotiate.r", "보급을 나누자 양측이 합류에 동의했습니다.", "Shared stores bring both sides to the table.");
            Add("enc.mutiny_transport.refuse", "반란선을 선단에 들이지 않는다", "Refuse the mutineers");
            Add("enc.mutiny_transport.refuse.r", "수송선은 홀로 구름 속으로 사라졌습니다.", "The transport vanishes alone into the clouds.");
            Add("enc.plague_barge.title", "역병 바지선", "THE PLAGUE BARGE");
            Add("enc.plague_barge.body", "격리 깃발을 단 바지선이 도움을 청합니다. 생존자들은 열에 시달리지만 아직 걸을 수 있습니다.", "A barge flying quarantine flags pleads for help. Its survivors are feverish but still on their feet.");
            Add("enc.plague_barge.quarantine", "[병원선] 격리 병동으로 받아들인다", "[Hospital ship] Take them into the isolation ward");
            Add("enc.plague_barge.quarantine.r", "병원선이 환자를 받았고 역병은 번지지 않았습니다.", "The hospital ship takes the sick, and the fever spreads no further.");
            Add("enc.plague_barge.take", "그냥 받아들인다 — 절반의 도박", "Take them anyway — a coin toss");
            Add("enc.plague_barge.take.r", "열이 가라앉았습니다. 60명이 합류했습니다.", "The fever breaks. Sixty join the convoy.");
            Add("enc.plague_barge.take_fail", "역병 확산", "The fever spreads");
            Add("enc.plague_barge.take_fail.r", "역병이 선단에 번져 30명을 잃었습니다.", "The fever spreads through the convoy and thirty are lost.");
            Add("enc.plague_barge.refuse", "떠난다", "Leave them");
            Add("enc.plague_barge.refuse.r", "바지선의 신호가 점점 약해집니다.", "The barge's signal grows fainter.");
            Add("enc.child_choir.title", "떠도는 성가대", "THE WANDERING CHOIR");
            Add("enc.child_choir.body", "음악학교 비행선이 연료를 다 쓰고 표류합니다. 아이들이 갑판에서 노래하며 신호를 보냅니다.", "A music-school airship has run dry. Children on its deck sing to signal you.");
            Add("enc.child_choir.take", "모두 태운다 (보급 1)", "Take them all aboard (1 supply)");
            Add("enc.child_choir.take.r", "성가대의 노래가 선단 통신망에 퍼지자 사기가 치솟았습니다.", "Their song spreads across the convoy channel and morale soars.");
            Add("enc.child_choir.fuel", "에테르 1을 나눠 준다", "Share 1 aether");
            Add("enc.child_choir.fuel.r", "비행선은 다시 떠올랐고, 아이들이 손을 흔들었습니다.", "The airship lifts again; the children wave.");
            Add("enc.child_choir.leave", "지나친다", "Pass them by");
            Add("enc.child_choir.leave.r", "노래가 뒤에서 잦아듭니다.", "The song fades behind you.");
            Add("enc.imperial_deserters.title", "제국 탈영병", "IMPERIAL DESERTERS");
            Add("enc.imperial_deserters.body", "제국 순찰정 한 척이 항복 깃발을 올렸습니다. 승무원은 탈영을 원하며 무기고를 대가로 내놓습니다.", "An imperial picket raises a surrender flag. Its crew want to desert and offer their magazine in return.");
            Add("enc.imperial_deserters.accept", "받아들인다", "Take them in");
            Add("enc.imperial_deserters.accept.r", "군수품을 받았지만 선단 일부는 제국 제복을 불신합니다.", "You gain ordnance, but parts of the convoy distrust the uniforms.");
            Add("enc.imperial_deserters.interrogate", "[인간] 옛 동료로서 항로 정보를 얻는다", "[Human] Trade on old ties for route intelligence");
            Add("enc.imperial_deserters.interrogate.r", "탈영병이 제국 연료고 좌표를 넘겼습니다.", "The deserters hand over the coordinates of an imperial fuel cache.");
            Add("enc.imperial_deserters.refuse", "거절한다", "Turn them away");
            Add("enc.imperial_deserters.refuse.r", "순찰정은 항복 깃발을 내리고 멀어졌습니다.", "The picket lowers its flag and drifts away.");
            Add("enc.stranded_engineers.title", "조난 기술자", "STRANDED ENGINEERS");
            Add("enc.stranded_engineers.body", "부서진 정비선의 기술자들이 공구를 든 채 구조를 기다립니다.", "Engineers from a wrecked tender wait for rescue, tools in hand.");
            Add("enc.stranded_engineers.take", "태우고 수리를 맡긴다", "Take them aboard and put them to work");
            Add("enc.stranded_engineers.take.r", "기술자들이 선체 균열을 메웠습니다.", "The engineers weld the flagship's cracks shut.");
            Add("enc.stranded_engineers.pay", "인양물 3을 주고 정식 수리를 부탁한다", "Pay 3 salvage for a proper refit");
            Add("enc.stranded_engineers.pay.r", "자재를 받은 기술자들이 장갑판까지 손봤습니다.", "With materials in hand they patch armor as well as hull.");
            Add("enc.stranded_engineers.leave", "떠난다", "Leave them");
            Add("enc.stranded_engineers.leave.r", "정비선의 불빛이 꺼졌습니다.", "The tender's lights go dark.");
            Add("enc.sky_whale_calf.title", "다친 하늘고래 새끼", "THE WOUNDED SKY-WHALE CALF");
            Add("enc.sky_whale_calf.body", "그물에 얽힌 하늘고래 새끼가 선단 곁을 맴돕니다. 어미는 보이지 않습니다.", "A sky-whale calf tangled in netting circles the convoy. Its mother is nowhere in sight.");
            Add("enc.sky_whale_calf.calm", "[조인] 노래로 달래며 그물을 푼다", "[Avian] Sing it calm and cut the net");
            Add("enc.sky_whale_calf.calm.r", "풀려난 새끼가 에테르 결정을 떨어뜨리고 떠났습니다.", "Freed, the calf sheds an aether crystal and swims away.");
            Add("enc.sky_whale_calf.free", "보급 1을 미끼로 그물을 푼다", "Lure it with 1 supply and cut the net");
            Add("enc.sky_whale_calf.free.r", "새끼가 선단 주위를 한 바퀴 돌고 사라졌습니다.", "The calf circles the convoy once and vanishes.");
            Add("enc.sky_whale_calf.harvest", "사냥해 자원으로 쓴다", "Harvest it");
            Add("enc.sky_whale_calf.harvest.r", "자원은 얻었지만 선단은 그 울음을 잊지 못합니다.", "The convoy gains salvage and cannot forget the sound it made.");
            Add("enc.wreck_signal_trap.title", "부르는 난파선", "THE WRECK THAT CALLED");
            Add("enc.wreck_signal_trap.body", "구조 신호가 나오는 난파선 주위로 기류가 이상하게 고요합니다.", "A wreck broadcasts a distress call. The air around it is strangely still.");
            Add("enc.wreck_signal_trap.detect", "[정찰선] 주변을 먼저 훑는다", "[Pathfinder] Sweep the approach first");
            Add("enc.wreck_signal_trap.detect.r", "정찰선이 매복 기뢰를 찾아냈고, 난파선은 조용히 인양됐습니다.", "The pathfinder finds the ambush mines; the wreck is quietly salvaged.");
            Add("enc.wreck_signal_trap.approach", "그대로 접근한다", "Approach directly");
            Add("enc.wreck_signal_trap.approach.r", "진짜 생존자였습니다. 50명이 합류했습니다.", "The call was real. Fifty survivors join you.");
            Add("enc.wreck_signal_trap.ambush", "매복", "Ambush");
            Add("enc.wreck_signal_trap.ambush.r", "난파선 뒤에서 제국 커터가 튀어나옵니다!", "An imperial cutter bursts from behind the wreck!");
            Add("enc.wreck_signal_trap.ignore", "무시한다", "Ignore the call");
            Add("enc.wreck_signal_trap.ignore.r", "신호가 뒤에서 되풀이됩니다.", "The signal repeats behind you.");
            Add("enc.derelict_cruiser.title", "표류 순양함", "THE DERELICT CRUISER");
            Add("enc.derelict_cruiser.body", "제국 순양함 한 척이 등을 꺼트린 채 표류합니다. 무장은 남아 있고 코어는 불안정하게 웅웅거립니다.", "An imperial cruiser drifts dark. Its guns are intact and its core hums unsteadily.");
            Add("enc.derelict_cruiser.strip", "무장고를 뜯어낸다", "Strip the magazines");
            Add("enc.derelict_cruiser.strip.r", "군수품과 부품을 확보했습니다.", "Ordnance and parts secured.");
            Add("enc.derelict_cruiser.core", "[드워프] 코어를 추출한다", "[Dwarf] Extract the core");
            Add("enc.derelict_cruiser.core.r", "코어가 안전하게 빠져나왔습니다.", "The core comes free cleanly.");
            Add("enc.derelict_cruiser.core_fail", "코어 폭주", "Core surge");
            Add("enc.derelict_cruiser.core_fail.r", "코어가 폭주하며 선체를 태웠습니다.", "The core surges and scorches the hull.");
            Add("enc.derelict_cruiser.leave", "손대지 않는다", "Leave it");
            Add("enc.derelict_cruiser.leave.r", "순양함은 계속 표류합니다.", "The cruiser drifts on.");
            Add("enc.aether_geyser.title", "에테르 간헐천", "THE AETHER GEYSER");
            Add("enc.aether_geyser.body", "구름 아래에서 에테르 기둥이 주기적으로 솟구칩니다.", "Columns of aether erupt from beneath the clouds at intervals.");
            Add("enc.aether_geyser.harvest", "코어를 열어 최대한 흡수한다", "Open the core and drink deep");
            Add("enc.aether_geyser.harvest.r", "에테르는 넘치지만 코어가 불안하게 떨립니다.", "Aether overflows; the core shudders.");
            Add("enc.aether_geyser.careful", "가장자리에서 조심스럽게 채집한다", "Skim the edges carefully");
            Add("enc.aether_geyser.careful.r", "안전하게 에테르를 채웠습니다.", "Aether gathered safely.");
            Add("enc.aether_geyser.pass", "지나간다", "Pass it by");
            Add("enc.aether_geyser.pass.r", "간헐천이 뒤에서 솟구칩니다.", "The geyser erupts behind you.");
            Add("enc.floating_monastery.title", "부유 수도원", "THE FLOATING MONASTERY");
            Add("enc.floating_monastery.body", "버려진 수도원이 조용히 떠 있습니다. 성유물과 낡은 기도문이 남아 있습니다.", "An abandoned monastery floats in silence, relics and worn prayers still inside.");
            Add("enc.floating_monastery.relics", "성유물을 가져간다", "Take the relics");
            Add("enc.floating_monastery.relics.r", "성유물은 값지지만 순례자들이 눈을 돌립니다.", "The relics are valuable; the pilgrims look away.");
            Add("enc.floating_monastery.prayers", "기도문을 선단에 낭독한다", "Read the prayers to the convoy");
            Add("enc.floating_monastery.prayers.r", "오래된 기도가 선단을 달랬습니다.", "Old words steady the convoy.");
            Add("enc.floating_monastery.resonate", "[엘프] 성가의 공명으로 코어를 채운다", "[Elf] Tune the core to the chant");
            Add("enc.floating_monastery.resonate.r", "성가가 코어에 에테르를 불어넣었습니다.", "The chant breathes aether into the core.");
            Add("enc.mine_field.title", "옛 기뢰 지대", "THE OLD MINEFIELD");
            Add("enc.mine_field.body", "옛 전쟁의 기뢰가 항로를 막습니다. 기뢰 사이에 침몰선 잔해가 보입니다.", "Mines from an old war block the lane. Wreckage glints between them.");
            Add("enc.mine_field.chart", "[정찰선] 안전한 길을 그린다", "[Pathfinder] Chart a safe path");
            Add("enc.mine_field.chart.r", "정찰선이 기뢰를 해체해 군수품으로 만들었습니다.", "The pathfinder defuses mines into ordnance.");
            Add("enc.mine_field.thread", "기뢰 사이를 통과한다", "Thread the mines");
            Add("enc.mine_field.thread.r", "잔해를 챙겨 무사히 빠져나왔습니다.", "You pull salvage from the wreck and slip out.");
            Add("enc.mine_field.thread_fail", "기뢰 접촉", "Mine strike");
            Add("enc.mine_field.thread_fail.r", "기뢰가 터져 장갑이 찢겼습니다.", "A mine detonates against the armor.");
            Add("enc.mine_field.avoid", "우회한다 (에테르 1)", "Go around (1 aether)");
            Add("enc.mine_field.avoid.r", "연료를 태워 기뢰 지대를 돌아갔습니다.", "You burn fuel to skirt the field.");
            Add("enc.crashed_courier.title", "추락한 급사선", "THE CRASHED COURIER");
            Add("enc.crashed_courier.body", "암호 장치가 켜진 채 추락한 제국 급사선이 있습니다.", "An imperial courier has crashed with its cipher engine still running.");
            Add("enc.crashed_courier.decode", "암호를 풀어 보급 좌표를 찾는다", "Decode it for depot coordinates");
            Add("enc.crashed_courier.decode.r", "근처 보급 좌표를 얻었습니다.", "You find a nearby depot's coordinates.");
            Add("enc.crashed_courier.sell", "장치를 뜯어 팔 준비를 한다", "Rip out the engine to sell");
            Add("enc.crashed_courier.sell.r", "암호 장치는 값이 나갈 것입니다.", "The engine will fetch a good price.");
            Add("enc.crashed_courier.burn", "급사선을 불태워 흔적을 지운다", "Burn the courier to hide your trail");
            Add("enc.crashed_courier.burn.r", "추격군이 며칠은 헤맬 것입니다.", "The pursuit will chase ghosts for days.");
            Add("enc.cloud_farm.title", "구름 농장 잔해", "THE CLOUD FARM");
            Add("enc.cloud_farm.body", "부서진 수경 농장이 떠다닙니다. 작물은 아직 살아 있고, 농부들도 일부 남았습니다.", "A broken hydroponic farm drifts by. Its crops still live, and so do a few farmers.");
            Add("enc.cloud_farm.harvest", "작물을 거둔다", "Harvest the crops");
            Add("enc.cloud_farm.harvest.r", "보급이 늘었습니다.", "Supplies replenished.");
            Add("enc.cloud_farm.settle", "농부들과 작물을 함께 태운다", "Take the farmers and their crops");
            Add("enc.cloud_farm.settle.r", "농부들이 선단 식량 관리를 맡았습니다.", "The farmers take charge of the convoy's rations.");
            Add("enc.cloud_farm.leave", "지나친다", "Leave it");
            Add("enc.cloud_farm.leave.r", "농장이 뒤로 멀어집니다.", "The farm drifts behind.");
            Add("enc.ordnance_cache.title", "봉인된 저장고", "THE SEALED CACHE");
            Add("enc.ordnance_cache.body", "제국 군수 저장고가 봉인된 채 절벽에 박혀 있습니다.", "A sealed imperial ordnance cache is wedged into a cliff.");
            Add("enc.ordnance_cache.careful", "천천히 봉인을 푼다", "Work the seal open slowly");
            Add("enc.ordnance_cache.careful.r", "군수품 일부를 회수했습니다.", "Some ordnance recovered.");
            Add("enc.ordnance_cache.blast", "폭파해서 연다", "Blow it open");
            Add("enc.ordnance_cache.blast.r", "저장고가 통째로 열렸습니다.", "The whole cache is yours.");
            Add("enc.ordnance_cache.blast_fail", "유폭", "Sympathetic detonation");
            Add("enc.ordnance_cache.blast_fail.r", "저장고가 유폭해 선체가 흔들렸습니다.", "The cache cooks off and rattles the hull.");
            Add("enc.ordnance_cache.leave", "건드리지 않는다", "Leave it sealed");
            Add("enc.ordnance_cache.leave.r", "저장고는 절벽에 남았습니다.", "The cache stays in the cliff.");
            Add("enc.sky_kelp_forest.title", "하늘 켈프 숲", "THE SKY-KELP FOREST");
            Add("enc.sky_kelp_forest.body", "부유 켈프 숲이 항로를 덮습니다. 켈프 사이에 새 둥지와 오래된 잔해가 있습니다.", "Floating kelp blankets the lane, nests and old wreckage hidden in its fronds.");
            Add("enc.sky_kelp_forest.gather", "켈프를 거둔다", "Gather kelp");
            Add("enc.sky_kelp_forest.gather.r", "식용 켈프를 저장했습니다.", "Edible kelp stored.");
            Add("enc.sky_kelp_forest.scavenge", "[고블린] 둥지와 잔해를 뒤진다", "[Goblin] Pick through the nests and wreckage");
            Add("enc.sky_kelp_forest.scavenge.r", "고블린들이 켈프 속에서 값진 부품을 찾았습니다.", "The goblins find valuable parts in the fronds.");
            Add("enc.sky_kelp_forest.push", "밀고 나간다 (에테르 1)", "Push through (1 aether)");
            Add("enc.sky_kelp_forest.push.r", "켈프를 헤치고 나왔습니다.", "You force a way through.");
            Add("enc.gate_shard.title", "천공문 파편", "THE GATE SHARD");
            Add("enc.gate_shard.body", "고대 천공문의 파편이 공중에 떠 있습니다. 코어가 그 진동에 반응합니다.", "A shard of an ancient sky gate hangs in the air. Your core answers its hum.");
            Add("enc.gate_shard.study", "파편을 연구한다", "Study the shard");
            Add("enc.gate_shard.study.r", "파편의 진동에서 에테르를 얻었습니다.", "The shard's hum yields aether.");
            Add("enc.gate_shard.sell", "파편을 잘라 판다", "Cut it up to sell");
            Add("enc.gate_shard.sell.r", "파편은 상인들에게 큰 값을 받을 것입니다.", "The fragments will fetch a fortune.");
            Add("enc.gate_shard.attune", "[엘프] 파편에 코어를 공명시킨다", "[Elf] Attune the core to the shard");
            Add("enc.gate_shard.attune.r", "코어가 넘치도록 채워졌지만 불안정해졌습니다.", "The core brims — and trembles.");
            Add("enc.smuggler_flotilla.title", "밀수단 선단", "THE SMUGGLER FLOTILLA");
            Add("enc.smuggler_flotilla.body", "깃발 없는 밀수선들이 거래를 제안합니다. 가격은 좋지만 질문은 받지 않습니다.", "Flagless smugglers offer a deal. The prices are good and no questions are taken.");
            Add("enc.smuggler_flotilla.ordnance", "인양물 5로 군수품 4", "4 ordnance for 5 salvage");
            Add("enc.smuggler_flotilla.ordnance.r", "군수품이 조용히 옮겨졌습니다.", "The ordnance changes hands quietly.");
            Add("enc.smuggler_flotilla.aether", "인양물 7로 에테르 4", "4 aether for 7 salvage");
            Add("enc.smuggler_flotilla.aether.r", "연료 탱크가 채워졌습니다.", "Your tanks are filled.");
            Add("enc.smuggler_flotilla.sell", "보급 2를 팔아 인양물 9", "Sell 2 supplies for 9 salvage");
            Add("enc.smuggler_flotilla.sell.r", "밀수단이 식량에 후한 값을 쳤습니다.", "The smugglers pay well for food.");
            Add("enc.smuggler_flotilla.depart", "거래하지 않는다", "Decline");
            Add("enc.smuggler_flotilla.depart.r", "밀수선들이 구름 속으로 흩어졌습니다.", "The smugglers scatter into the clouds.");
            Add("enc.guild_caravan.title", "길드 상단", "THE GUILD CARAVAN");
            Add("enc.guild_caravan.body", "무장한 상단이 폭풍을 피해 호위를 원합니다.", "An armed guild caravan wants an escort through the storm.");
            Add("enc.guild_caravan.escort", "군수품 1을 쓰며 호위한다", "Escort them (1 ordnance)");
            Add("enc.guild_caravan.escort.r", "상단이 호위비를 후하게 치렀습니다.", "The caravan pays handsomely for the escort.");
            Add("enc.guild_caravan.buy", "인양물 5로 보급 6", "6 supplies for 5 salvage");
            Add("enc.guild_caravan.buy.r", "보급이 늘었습니다.", "Supplies replenished.");
            Add("enc.guild_caravan.depart", "떠난다", "Move on");
            Add("enc.guild_caravan.depart.r", "상단은 다른 호위를 찾아 떠났습니다.", "The caravan seeks another escort.");
            Add("enc.refit_yard.title", "개장 조선소", "THE REFIT YARD");
            Add("enc.refit_yard.body", "떠돌이 조선소가 개장 서비스를 광고합니다.", "A roaming refit yard advertises its services.");
            Add("enc.refit_yard.refit", "인양물 6으로 편대 전면 보충", "Full air-wing refit for 6 salvage");
            Add("enc.refit_yard.refit.r", "편대가 정원을 채웠습니다.", "Both wings are back to full strength.");
            Add("enc.refit_yard.plating", "인양물 9로 장갑판 보강", "Armor plating for 9 salvage");
            Add("enc.refit_yard.plating.r", "새 장갑판이 선체를 감쌌습니다.", "Fresh plating wraps the hull.");
            Add("enc.refit_yard.depart", "떠난다", "Move on");
            Add("enc.refit_yard.depart.r", "조선소가 다음 손님을 부릅니다.", "The yard hails its next customer.");
            Add("enc.black_market.title", "암시장", "THE BLACK MARKET");
            Add("enc.black_market.body", "부유 암시장이 싼 에테르를 팝니다. 출처는 묻지 않는 편이 낫습니다.", "A floating black market sells cheap aether. Better not to ask where it came from.");
            Add("enc.black_market.cheap", "인양물 4로 에테르 3", "3 aether for 4 salvage");
            Add("enc.black_market.cheap.r", "출처 불명의 에테르가 탱크에 들어갔습니다.", "Aether of uncertain origin fills the tanks.");
            Add("enc.black_market.haggle", "[고블린] 흥정한다", "[Goblin] Haggle");
            Add("enc.black_market.haggle.r", "고블린의 흥정으로 덤까지 챙겼습니다.", "Goblin haggling wins a bonus.");
            Add("enc.black_market.depart", "떠난다", "Leave");
            Add("enc.black_market.depart.r", "시장의 불빛이 멀어집니다.", "The market's lights fade.");
            Add("enc.pilgrim_bazaar.title", "순례자 시장", "THE PILGRIM BAZAAR");
            Add("enc.pilgrim_bazaar.body", "순례선단이 임시 시장을 열었습니다. 사기 진작 물품과 성물이 오갑니다.", "A pilgrim fleet has opened a bazaar of comforts and holy trinkets.");
            Add("enc.pilgrim_bazaar.comforts", "보급 1로 위문품 구입", "Buy comforts for 1 supply");
            Add("enc.pilgrim_bazaar.comforts.r", "선단에 온기가 돌았습니다.", "Warmth spreads through the convoy.");
            Add("enc.pilgrim_bazaar.sell", "성물을 판다", "Sell holy trinkets");
            Add("enc.pilgrim_bazaar.sell.r", "돈은 벌었지만 순례자들의 시선이 차갑습니다.", "You profit; the pilgrims' eyes are cold.");
            Add("enc.pilgrim_bazaar.depart", "떠난다", "Leave");
            Add("enc.pilgrim_bazaar.depart.r", "시장이 문을 닫습니다.", "The bazaar closes.");
            Add("enc.mercenary_wing.title", "용병 편대", "THE MERCENARY WING");
            Add("enc.mercenary_wing.body", "용병 편대가 정비와 호위를 제안합니다. 값은 비쌉니다.", "A mercenary wing offers maintenance and escort. It is not cheap.");
            Add("enc.mercenary_wing.hire", "인양물 10으로 계약", "Hire them for 10 salvage");
            Add("enc.mercenary_wing.hire.r", "용병들이 편대를 보충하고 군수품을 나눴습니다.", "The mercenaries refit your wings and share ordnance.");
            Add("enc.mercenary_wing.ordnance", "인양물 4로 군수품 2", "2 ordnance for 4 salvage");
            Add("enc.mercenary_wing.ordnance.r", "군수품을 구입했습니다.", "Ordnance purchased.");
            Add("enc.mercenary_wing.depart", "거절한다", "Decline");
            Add("enc.mercenary_wing.depart.r", "용병들이 경례하고 떠났습니다.", "The mercenaries salute and depart.");
            Add("enc.fuel_barge.title", "연료 바지선", "THE FUEL BARGE");
            Add("enc.fuel_barge.body", "연료 바지선이 에테르를 팝니다. 식량도 받습니다.", "A fuel barge sells aether and accepts food in trade.");
            Add("enc.fuel_barge.small", "보급 3으로 에테르 3", "3 aether for 3 supplies");
            Add("enc.fuel_barge.small.r", "연료를 보충했습니다.", "Fuel topped up.");
            Add("enc.fuel_barge.big", "인양물 8로 에테르 6", "6 aether for 8 salvage");
            Add("enc.fuel_barge.big.r", "탱크가 가득 찼습니다.", "Tanks full.");
            Add("enc.fuel_barge.depart", "떠난다", "Leave");
            Add("enc.fuel_barge.depart.r", "바지선 승무원이 손을 흔듭니다.", "The barge crew wave you off.");
            Add("enc.quartermaster.title", "부패한 보급관", "THE CROOKED QUARTERMASTER");
            Add("enc.quartermaster.body", "제국 보급관이 몰래 물자를 팔겠다고 합니다.", "An imperial quartermaster offers to sell stores under the table.");
            Add("enc.quartermaster.bribe", "인양물 7로 군수품 5", "5 ordnance for 7 salvage");
            Add("enc.quartermaster.bribe.r", "군수품이 조용히 넘어왔습니다.", "The ordnance arrives quietly.");
            Add("enc.quartermaster.pose", "[인간] 감찰관 행세로 물자를 압수한다", "[Human] Pose as inspectors and seize stores");
            Add("enc.quartermaster.pose.r", "보급관은 서류를 보고 물자를 내줬습니다.", "One look at the papers and the stores are yours.");
            Add("enc.quartermaster.depart", "떠난다", "Leave");
            Add("enc.quartermaster.depart.r", "보급관이 어깨를 으쓱합니다.", "The quartermaster shrugs.");
            Add("enc.shipwright.title", "떠돌이 조선공", "THE WANDERING SHIPWRIGHT");
            Add("enc.shipwright.body", "은퇴한 조선공이 수리 대가로 인양물을 원합니다.", "A retired shipwright will patch you up for salvage.");
            Add("enc.shipwright.repair", "인양물 7로 기함 수리", "Repair the flagship for 7 salvage");
            Add("enc.shipwright.repair.r", "조선공이 선체와 구획을 손봤습니다.", "The shipwright patches hull and compartments.");
            Add("enc.shipwright.reinforce", "인양물 5로 선체 보강", "Reinforce the hull for 5 salvage");
            Add("enc.shipwright.reinforce.r", "보강재가 선체를 감쌌습니다.", "Bracing wraps the hull.");
            Add("enc.shipwright.depart", "떠난다", "Leave");
            Add("enc.shipwright.depart.r", "조선공이 다음 항구로 향합니다.", "The shipwright heads for the next port.");
            Add("enc.customs_inspection.title", "세관 검사", "THE CUSTOMS INSPECTION");
            Add("enc.customs_inspection.body", "세관선이 화물 검사를 요구합니다. 선단에 숨겨 둔 피난민이 있습니다.", "A customs cutter demands to inspect cargo. Refugees are hidden in your holds.");
            Add("enc.customs_inspection.submit", "보급 2를 '관세'로 낸다", "Pay 2 supplies in 'duties'");
            Add("enc.customs_inspection.submit.r", "세관은 서류를 보지도 않고 떠났습니다.", "Customs leaves without reading a page.");
            Add("enc.customs_inspection.hide", "피난민을 숨기고 통과한다", "Hide the refugees and bluff");
            Add("enc.customs_inspection.hide.r", "세관은 아무것도 찾지 못했습니다.", "Customs finds nothing.");
            Add("enc.customs_inspection.hide_fail", "발각", "Discovered");
            Add("enc.customs_inspection.hide_fail.r", "피난민이 발각됐습니다. 세관선이 포문을 엽니다!", "The refugees are found. The cutter opens fire!");
            Add("enc.customs_inspection.fight", "먼저 포문을 연다", "Open fire first");
            Add("enc.customs_inspection.fight.r", "세관선이 결계를 올립니다.", "The cutter raises its ward.");
            Add("enc.loyalty_oath.title", "충성 서약", "THE LOYALTY OATH");
            Add("enc.loyalty_oath.body", "제국 선전선이 통과 조건으로 공개 충성 서약을 요구합니다.", "An imperial broadcast ship demands a public loyalty oath as the price of passage.");
            Add("enc.loyalty_oath.swear", "서약하고 연료를 받는다", "Swear and take the fuel");
            Add("enc.loyalty_oath.swear.r", "서약이 방송됐습니다. 선단은 부끄러워합니다.", "The oath is broadcast. The convoy is ashamed.");
            Add("enc.loyalty_oath.recite", "[인간] 옛 공화국의 서약을 대신 읊는다", "[Human] Recite the old republic's oath instead");
            Add("enc.loyalty_oath.recite.r", "장교는 미소를 지으며 통과를 허락했습니다.", "The officer smiles and waves you through.");
            Add("enc.loyalty_oath.refuse", "거부하고 돌파한다", "Refuse and break through");
            Add("enc.loyalty_oath.refuse.r", "선전선이 호위함을 부릅니다.", "The broadcast ship calls its escort.");
            Add("enc.bounty_hunters.title", "현상금 사냥꾼", "THE BOUNTY HUNTERS");
            Add("enc.bounty_hunters.body", "현상금 사냥꾼들이 함장의 목에 걸린 값을 들먹입니다.", "Bounty hunters name the price on your captain's head.");
            Add("enc.bounty_hunters.pay", "인양물 8로 매수한다", "Buy them off for 8 salvage");
            Add("enc.bounty_hunters.pay.r", "사냥꾼들이 돈을 세며 떠났습니다.", "The hunters leave counting coin.");
            Add("enc.bounty_hunters.intimidate", "[오크] 해병을 갑판에 세운다", "[Orc] Line the deck with marines");
            Add("enc.bounty_hunters.intimidate.r", "사냥꾼들은 다시 생각했습니다.", "The hunters reconsider.");
            Add("enc.bounty_hunters.fight", "싸운다", "Fight");
            Add("enc.bounty_hunters.fight.r", "사냥꾼선이 무장을 펼칩니다.", "The hunters run out their guns.");
            Add("enc.blockade_toll.title", "봉쇄 통행세", "THE BLOCKADE TOLL");
            Add("enc.blockade_toll.body", "제국 봉쇄선이 통행세를 요구합니다. 뒤에는 순양함이 대기 중입니다.", "An imperial blockade demands a toll. A cruiser waits behind it.");
            Add("enc.blockade_toll.pay", "에테르 1과 인양물 4를 낸다", "Pay 1 aether and 4 salvage");
            Add("enc.blockade_toll.pay.r", "봉쇄선이 길을 열었습니다.", "The blockade opens.");
            Add("enc.blockade_toll.run", "전속으로 돌파한다", "Run the blockade");
            Add("enc.blockade_toll.run.r", "봉쇄선이 미처 반응하지 못했습니다.", "The blockade fails to react in time.");
            Add("enc.blockade_toll.run_fail", "차단", "Intercepted");
            Add("enc.blockade_toll.run_fail.r", "순양함이 앞을 막아섭니다!", "The cruiser cuts you off!");
            Add("enc.blockade_toll.fight", "순양함과 정면으로 싸운다", "Fight the cruiser head-on");
            Add("enc.blockade_toll.fight.r", "순양함이 전투 태세에 들어갑니다.", "The cruiser clears for action.");
            Add("enc.propaganda_broadcast.title", "선전 방송", "THE PROPAGANDA BROADCAST");
            Add("enc.propaganda_broadcast.body", "제국 방송이 선단 통신망을 점령해 항복을 종용합니다.", "Imperial propaganda floods the convoy channel, urging surrender.");
            Add("enc.propaganda_broadcast.jam", "군수품 1을 써 방해 전파를 쏜다", "Spend 1 ordnance to jam it");
            Add("enc.propaganda_broadcast.jam.r", "방송이 끊기자 환호가 터졌습니다.", "The broadcast dies and the convoy cheers.");
            Add("enc.propaganda_broadcast.counter", "함장이 직접 연설한다", "The captain answers on the open channel");
            Add("enc.propaganda_broadcast.counter.r", "함장의 목소리가 선단을 붙잡았습니다.", "The captain's voice holds the convoy together.");
            Add("enc.propaganda_broadcast.ignore", "무시한다", "Ignore it");
            Add("enc.propaganda_broadcast.ignore.r", "방송이 며칠간 이어졌습니다.", "The broadcast drones on for days.");
            Add("enc.reformist_courier.title", "개혁파 급사", "THE REFORMIST COURIER");
            Add("enc.reformist_courier.body", "개혁파 급사선이 추격을 받으며 도움을 청합니다.", "A reformist courier, pursued, asks for cover.");
            Add("enc.reformist_courier.help", "보급 1을 주고 숨겨 준다", "Hide them for 1 supply");
            Add("enc.reformist_courier.help.r", "급사는 비밀 연료고 좌표로 보답했습니다.", "The courier repays you with the coordinates of a hidden fuel cache.");
            Add("enc.reformist_courier.refuse", "관여하지 않는다", "Stay out of it");
            Add("enc.reformist_courier.refuse.r", "급사선이 홀로 사라졌습니다.", "The courier vanishes alone.");
            Add("enc.hostage_exchange.title", "인질 교환", "THE HOSTAGE EXCHANGE");
            Add("enc.hostage_exchange.body", "제국 초계함이 선단 출신 인질을 군수품과 바꾸자고 합니다.", "An imperial picket offers convoy hostages in exchange for ordnance.");
            Add("enc.hostage_exchange.trade", "군수품 2로 교환한다", "Trade 2 ordnance");
            Add("enc.hostage_exchange.trade.r", "인질들이 돌아왔습니다.", "The hostages come home.");
            Add("enc.hostage_exchange.assault", "강습대로 구출한다", "Storm the picket");
            Add("enc.hostage_exchange.assault.r", "강습대가 인질을 구출했습니다.", "The boarders free the hostages.");
            Add("enc.hostage_exchange.assault_fail", "강습 실패", "Assault fails");
            Add("enc.hostage_exchange.assault_fail.r", "강습이 막혔고 초계함이 반격합니다!", "The assault is repulsed and the picket fights back!");
            Add("enc.hostage_exchange.refuse", "거절한다", "Refuse");
            Add("enc.hostage_exchange.refuse.r", "초계함이 인질을 데리고 떠났습니다.", "The picket leaves with the hostages.");
            Add("enc.spy_aboard.title", "함내 첩자", "THE SPY ABOARD");
            Add("enc.spy_aboard.body", "제국 검문관이 선단에 첩자가 있다고 경고합니다. 진심일까요?", "An imperial inspector warns that a spy hides in your convoy. Is it true?");
            Add("enc.spy_aboard.search", "보급 1을 쓰며 전수 조사한다", "Search every hold (1 supply)");
            Add("enc.spy_aboard.search.r", "첩자와 숨겨진 폭약을 찾았습니다.", "You find the spy and a hidden charge.");
            Add("enc.spy_aboard.spot", "[조인] 눈으로 찾아낸다", "[Avian] Pick the spy out by sight");
            Add("enc.spy_aboard.spot.r", "조인의 눈이 첩자를 골라냈습니다.", "Avian eyes single out the spy.");
            Add("enc.spy_aboard.ignore", "무시한다", "Ignore the warning");
            Add("enc.spy_aboard.ignore.r", "경고는 헛소리였습니다.", "The warning was nothing.");
            Add("enc.spy_aboard.sabotage", "파괴 공작", "Sabotage");
            Add("enc.spy_aboard.sabotage.r", "첩자가 연료를 빼돌리고 코어를 흔들었습니다.", "The spy bleeds fuel and rattles the core.");
            Add("enc.pilgrim_blockade.title", "문 앞의 순례자", "THE PILGRIMS AT THE GATE");
            Add("enc.pilgrim_blockade.body", "검문소가 순례자들을 막고 있습니다. 그들은 선단의 호위를 청합니다.", "A checkpoint is holding pilgrims back. They ask to travel under your protection.");
            Add("enc.pilgrim_blockade.escort", "에테르 1을 쓰며 호위한다", "Escort them (1 aether)");
            Add("enc.pilgrim_blockade.escort.r", "순례자들이 선단에 합류했습니다.", "The pilgrims join the convoy.");
            Add("enc.pilgrim_blockade.leave", "지나친다", "Pass on");
            Add("enc.pilgrim_blockade.leave.r", "순례자들이 뒤에 남았습니다.", "The pilgrims stay behind.");
            Add("enc.ion_squall.title", "이온 스콜", "THE ION SQUALL");
            Add("enc.ion_squall.body", "이온 스콜이 전 계기를 흔듭니다. 코어가 비명을 지릅니다.", "An ion squall rattles every instrument. The core screams.");
            Add("enc.ion_squall.calm", "에테르 1을 태워 코어를 진정시킨다", "Burn 1 aether to calm the core");
            Add("enc.ion_squall.calm.r", "코어가 진정됐습니다.", "The core settles.");
            Add("enc.ion_squall.push", "그대로 밀어붙인다", "Push through");
            Add("enc.ion_squall.push.r", "스콜을 뚫었고 잔류 에테르를 회수했습니다.", "You clear the squall and recover stray aether.");
            Add("enc.ion_squall.push_fail", "방전", "Discharge");
            Add("enc.ion_squall.push_fail.r", "방전이 선체를 태우고 코어를 흔들었습니다.", "A discharge scorches the hull and rattles the core.");
            Add("enc.static_fog.title", "정전기 안개", "THE STATIC FOG");
            Add("enc.static_fog.body", "정전기 안개가 시야를 지웁니다.", "Static fog erases all sight.");
            Add("enc.static_fog.chart", "[정찰선] 앞장서게 한다", "[Pathfinder] Send the pathfinder ahead");
            Add("enc.static_fog.chart.r", "정찰선이 안전한 길을 찾았습니다.", "The pathfinder finds a clear line.");
            Add("enc.static_fog.slow", "속도를 늦춘다 (에테르 1)", "Slow down (1 aether)");
            Add("enc.static_fog.slow.r", "천천히, 무사히 빠져나왔습니다.", "Slow and safe.");
            Add("enc.static_fog.fast", "전속으로 돌파한다", "Full speed");
            Add("enc.static_fog.fast.r", "안개를 단숨에 벗어났습니다.", "You burst out of the fog.");
            Add("enc.static_fog.fast_fail", "충돌", "Collision");
            Add("enc.static_fog.fast_fail.r", "잔해와 충돌해 장갑이 찢겼습니다.", "You clip wreckage and lose armor.");
            Add("enc.hail_front.title", "우박 전선", "THE HAIL FRONT");
            Add("enc.hail_front.body", "주먹만 한 우박이 선단을 두드립니다.", "Fist-sized hail hammers the convoy.");
            Add("enc.hail_front.brace", "[드워프] 장갑을 세워 버틴다", "[Dwarf] Brace the plating");
            Add("enc.hail_front.brace.r", "드워프들이 장갑을 지켰습니다.", "The dwarves hold the plating.");
            Add("enc.hail_front.climb", "에테르 2로 전선 위로 오른다", "Climb above it (2 aether)");
            Add("enc.hail_front.climb.r", "우박 위의 하늘은 고요했습니다.", "Above the front, the sky is still.");
            Add("enc.hail_front.endure", "버틴다", "Endure it");
            Add("enc.hail_front.endure.r", "우박이 장갑을 두들겼습니다.", "The hail dents the armor.");
            Add("enc.aether_bloom.title", "에테르 개화", "THE AETHER BLOOM");
            Add("enc.aether_bloom.body", "폭풍 속에 에테르 꽃이 피었습니다. 눈부시고 위험합니다.", "An aether bloom opens inside the storm — dazzling and dangerous.");
            Add("enc.aether_bloom.harvest", "가운데로 들어가 채집한다", "Fly into the bloom and harvest");
            Add("enc.aether_bloom.harvest.r", "에테르가 넘치지만 코어가 비명을 지릅니다.", "Aether floods in; the core howls.");
            Add("enc.aether_bloom.skirt", "가장자리만 스친다", "Skirt the edge");
            Add("enc.aether_bloom.skirt.r", "약간의 에테르를 얻었습니다.", "A little aether gained.");
            Add("enc.aether_bloom.avoid", "피한다", "Avoid it");
            Add("enc.aether_bloom.avoid.r", "개화가 뒤에서 사그라듭니다.", "The bloom fades behind you.");
            Add("enc.lightning_choir.title", "번개 성가", "THE LIGHTNING CHOIR");
            Add("enc.lightning_choir.body", "번개가 규칙적인 화음으로 칩니다. 공명자가 귀를 기울입니다.", "Lightning strikes in regular chords. Your resonator listens.");
            Add("enc.lightning_choir.conduct", "[엘프] 화음을 지휘해 코어를 채운다", "[Elf] Conduct the chords into the core");
            Add("enc.lightning_choir.conduct.r", "번개가 코어를 채웠습니다.", "Lightning fills the core.");
            Add("enc.lightning_choir.ground", "군수품 1을 피뢰침으로 쓴다", "Sacrifice 1 ordnance as a lightning rod");
            Add("enc.lightning_choir.ground.r", "번개가 미끼를 쳤습니다.", "The lightning takes the bait.");
            Add("enc.lightning_choir.endure", "버틴다", "Ride it out");
            Add("enc.lightning_choir.endure.r", "번개가 선단을 비껴갔습니다.", "The lightning passes you by.");
            Add("enc.lightning_choir.strike", "낙뢰", "Struck");
            Add("enc.lightning_choir.strike.r", "낙뢰가 선체를 강타했습니다.", "Lightning hammers the hull.");
            Add("enc.updraft_chasm.title", "상승기류 협곡", "THE UPDRAFT CHASM");
            Add("enc.updraft_chasm.body", "협곡에서 거대한 상승기류가 솟습니다.", "A vast updraft rises from the chasm.");
            Add("enc.updraft_chasm.high", "기류를 타고 고고도로 오른다", "Ride it to high altitude");
            Add("enc.updraft_chasm.high.r", "선단이 힘들이지 않고 고고도에 올랐습니다.", "The convoy climbs high without burning fuel.");
            Add("enc.updraft_chasm.avoid", "우회한다 (에테르 1)", "Go around (1 aether)");
            Add("enc.updraft_chasm.avoid.r", "협곡을 돌아갔습니다.", "You skirt the chasm.");
            Add("enc.cloud_reef.title", "구름 암초", "THE CLOUD REEF");
            Add("enc.cloud_reef.body", "굳은 구름 암초가 항로를 막습니다. 암초 속에 난파선이 박혀 있습니다.", "A reef of hardened cloud blocks the lane. Wrecks are lodged inside it.");
            Add("enc.cloud_reef.climb", "[고블린] 암초를 타고 잔해를 챙긴다", "[Goblin] Climb the reef for salvage");
            Add("enc.cloud_reef.climb.r", "고블린들이 잔해를 뜯어 왔습니다.", "The goblins strip the wrecks.");
            Add("enc.cloud_reef.around", "우회한다 (에테르 1)", "Go around (1 aether)");
            Add("enc.cloud_reef.around.r", "암초를 돌아갔습니다.", "You go around.");
            Add("enc.cloud_reef.risk", "틈으로 통과하며 인양한다", "Squeeze through and salvage");
            Add("enc.cloud_reef.risk.r", "틈을 통과하며 잔해를 챙겼습니다.", "You slip through and take salvage.");
            Add("enc.cloud_reef.scrape", "긁힘", "Scraped");
            Add("enc.cloud_reef.scrape.r", "암초가 선체를 긁었습니다.", "The reef tears at the hull.");
            Add("enc.whiteout.title", "화이트아웃", "THE WHITEOUT");
            Add("enc.whiteout.body", "눈보라가 모든 것을 지웁니다. 수송선이 대열을 잃기 시작합니다.", "A blizzard erases everything. Transports begin losing formation.");
            Add("enc.whiteout.anchor", "보급 1을 쓰며 정박해 기다린다", "Anchor and wait (1 supply)");
            Add("enc.whiteout.anchor.r", "눈보라가 지나갈 때까지 기다렸습니다.", "You wait out the storm.");
            Add("enc.whiteout.press", "밀고 나간다", "Press on");
            Add("enc.whiteout.press.r", "대열을 유지한 채 빠져나왔습니다.", "Formation holds.");
            Add("enc.whiteout.lost", "이탈", "Lost transports");
            Add("enc.whiteout.lost.r", "수송선 한 척이 대열에서 사라졌습니다.", "A transport is lost from the formation.");
            Add("enc.storm_leviathan.title", "폭풍 리바이어던", "THE STORM LEVIATHAN");
            Add("enc.storm_leviathan.body", "폭풍 속에서 거대한 그림자가 선단을 따라옵니다.", "Something vast follows the convoy inside the storm.");
            Add("enc.storm_leviathan.flee", "에테르 2로 전속 이탈", "Flee at full burn (2 aether)");
            Add("enc.storm_leviathan.flee.r", "그림자가 뒤처졌습니다.", "The shadow falls behind.");
            Add("enc.storm_leviathan.sing", "[조인] 노래로 달랜다", "[Avian] Sing to it");
            Add("enc.storm_leviathan.sing.r", "리바이어던이 노래를 따라 부르더니 멀어졌습니다.", "The leviathan answers the song and drifts away.");
            Add("enc.storm_leviathan.harpoon", "작살을 쏜다", "Harpoon it");
            Add("enc.storm_leviathan.harpoon.r", "리바이어던이 쓰러졌고 선단이 자원을 챙겼습니다.", "The leviathan falls and the convoy strips it.");
            Add("enc.storm_leviathan.harpoon_fail", "반격", "It turns on you");
            Add("enc.storm_leviathan.harpoon_fail.r", "리바이어던이 선체를 들이받았습니다.", "The leviathan rams the hull.");
            Add("enc.frozen_survey_team.title", "얼어붙은 측량단", "THE FROZEN SURVEY TEAM");
            Add("enc.frozen_survey_team.body", "빙운 고원의 관측소에서 측량단이 구조를 청합니다. 장비는 온전하지만 연료가 다 됐습니다.", "A survey team calls from an observatory on the icefield. Their instruments are intact; their fuel is gone.");
            Add("enc.frozen_survey_team.fetch", "에테르 1을 쓰며 데려온다", "Fly them out (1 aether)");
            Add("enc.frozen_survey_team.fetch.r", "측량단이 지도와 함께 합류했습니다.", "The surveyors join you, charts and all.");
            Add("enc.frozen_survey_team.dwarf", "[드워프] 발전기를 고쳐 관측소를 살린다", "[Dwarf] Repair their generator");
            Add("enc.frozen_survey_team.dwarf.r", "관측소가 되살아나 앞길의 결빙 정보를 넘겼습니다.", "The observatory lives again and radios icing warnings ahead.");
            Add("enc.frozen_survey_team.leave", "지나친다", "Pass by");
            Add("enc.frozen_survey_team.leave.r", "관측소의 불빛이 눈보라에 묻힙니다.", "The observatory's lights vanish into the snow.");
            Add("enc.abyss_diving_bell.title", "심연의 잠수종", "THE ABYSSAL BELL");
            Add("enc.abyss_diving_bell.body", "구름 밑바닥으로 내려간 잠수종 선단이 케이블에 매달려 있습니다. 끌어올리려면 힘이 듭니다.", "A diving-bell expedition hangs by its cable below the cloud floor. Hauling it up will strain the engines.");
            Add("enc.abyss_diving_bell.haul", "엔진을 혹사해 끌어올린다", "Haul them up");
            Add("enc.abyss_diving_bell.haul.r", "케이블이 버텼고 탐사대가 심연의 표본을 넘겼습니다.", "The cable holds; the explorers hand over samples from the deep.");
            Add("enc.abyss_diving_bell.cut", "케이블을 끊고 떠난다", "Cut the cable");
            Add("enc.abyss_diving_bell.cut.r", "선단은 아무 말 없이 항로를 계속했습니다.", "No one speaks as the convoy moves on.");
            Add("enc.abyss_diving_bell.orc", "[오크] 해병이 케이블을 손으로 당긴다", "[Orc] Marines haul by hand");
            Add("enc.abyss_diving_bell.orc.r", "오크들이 노래를 부르며 종을 끌어올렸습니다.", "The orcs sing as they drag the bell home.");
            Add("enc.cordon_escapees.title", "봉쇄선 탈출자", "CORDON ESCAPEES");
            Add("enc.cordon_escapees.body", "제국 봉쇄선을 뚫고 나온 소형선 여러 척이 추격을 받고 있습니다.", "A handful of small craft have broken through the Imperial cordon with pursuers close behind.");
            Add("enc.cordon_escapees.cover", "호위하며 받아들인다", "Cover them and take them in");
            Add("enc.cordon_escapees.cover.r", "탈출자들이 합류했지만 추격대가 위치를 알아챘습니다.", "The escapees join you; the pursuit now knows where you are.");
            Add("enc.cordon_escapees.decoy", "군수품 1로 기만 신호를 쏜다", "Fire a decoy beacon (1 ordnance)");
            Add("enc.cordon_escapees.decoy.r", "추격대가 미끼를 물었고 탈출자들이 조용히 합류했습니다.", "The pursuit takes the bait and the escapees slip aboard.");
            Add("enc.cordon_escapees.leave", "관여하지 않는다", "Stay clear");
            Add("enc.cordon_escapees.leave.r", "소형선들이 구름 속으로 흩어졌습니다.", "The craft scatter into the clouds.");
            Add("enc.drifting_nursery.title", "떠도는 보육선", "THE DRIFTING NURSERY");
            Add("enc.drifting_nursery.body", "보육선 한 척이 항법 장치 고장으로 표류합니다. 보호자는 둘뿐입니다.", "A nursery ship drifts with a dead navigation core. Two adults are all that watch over it.");
            Add("enc.drifting_nursery.adopt", "선단에 받아들인다", "Bring them into the convoy");
            Add("enc.drifting_nursery.adopt.r", "아이들이 선단 곳곳에 흩어져 새 가족을 만났습니다.", "The children find new families throughout the convoy.");
            Add("enc.drifting_nursery.navigator", "[조인] 항법 장치를 고쳐 스스로 가게 한다", "[Avian] Fix their navigation and send them on");
            Add("enc.drifting_nursery.navigator.r", "보육선이 안전한 항로로 떠났습니다.", "The nursery ship sails on along a safe course.");
            Add("enc.drifting_nursery.leave", "지나친다", "Pass by");
            Add("enc.drifting_nursery.leave.r", "선단이 침묵합니다.", "The convoy falls silent.");
            Add("enc.wrecked_gunship.title", "난파한 포함", "THE WRECKED GUNSHIP");
            Add("enc.wrecked_gunship.body", "제국 포함의 잔해에서 생존자들이 신호를 보냅니다. 무장은 대부분 온전합니다.", "Survivors signal from the wreck of an Imperial gunship. Most of its guns survived the crash.");
            Add("enc.wrecked_gunship.both", "생존자와 무장을 모두 회수한다 (보급 1)", "Recover crew and guns (1 supply)");
            Add("enc.wrecked_gunship.both.r", "포함 승무원이 합류했고 군수품이 늘었습니다.", "The gunship's crew join you and the magazines fill.");
            Add("enc.wrecked_gunship.guns", "무장만 뜯어간다", "Strip the guns only");
            Add("enc.wrecked_gunship.guns.r", "군수품은 얻었지만 생존자들의 눈길이 따라옵니다.", "You gain ordnance; the survivors' eyes follow you.");
            Add("enc.wrecked_gunship.leave", "떠난다", "Leave");
            Add("enc.wrecked_gunship.leave.r", "잔해가 구름 아래로 가라앉습니다.", "The wreck sinks beneath the clouds.");
            Add("enc.storm_shrine_hermits.title", "폭풍 사원의 은둔자", "THE STORM SHRINE HERMITS");
            Add("enc.storm_shrine_hermits.body", "폭풍 속 사원에 은둔자들이 남아 있습니다. 떠나기를 거부하지만 아이들은 보내려 합니다.", "Hermits keep a shrine inside the storm. They refuse to leave but will send their children with you.");
            Add("enc.storm_shrine_hermits.children", "아이들을 받아들인다", "Take the children");
            Add("enc.storm_shrine_hermits.children.r", "은둔자들이 축복과 함께 아이들을 보냈습니다.", "The hermits send their children with a blessing.");
            Add("enc.storm_shrine_hermits.persuade", "[엘프] 폭풍 노래로 설득한다", "[Elf] Persuade them with the storm-song");
            Add("enc.storm_shrine_hermits.persuade.r", "은둔자 전원이 선단에 합류했습니다.", "Every hermit comes aboard.");
            Add("enc.storm_shrine_hermits.leave", "존중하고 떠난다", "Respect their choice and leave");
            Add("enc.storm_shrine_hermits.leave.r", "사원의 종소리가 뒤에서 울립니다.", "The shrine's bell rings behind you.");
            Add("enc.quarantined_liner.title", "격리된 여객선", "THE QUARANTINED LINER");
            Add("enc.quarantined_liner.body", "제국이 격리 표식을 붙인 여객선이 표류합니다. 승객들은 건강해 보입니다.", "A liner drifts with Imperial quarantine markings. Its passengers look healthy enough.");
            Add("enc.quarantined_liner.inspect", "[병원선] 검진 후 받아들인다", "[Hospital ship] Screen and admit them");
            Add("enc.quarantined_liner.inspect.r", "격리 표식은 정치적 낙인이었습니다. 승객 전원이 합류했습니다.", "The quarantine was a political brand; every passenger joins.");
            Add("enc.quarantined_liner.risk", "검진 없이 받아들인다", "Admit them unscreened");
            Add("enc.quarantined_liner.risk.r", "아무 문제도 없었습니다.", "Nothing was wrong with them at all.");
            Add("enc.quarantined_liner.risk_fail", "전염", "Contagion");
            Add("enc.quarantined_liner.risk_fail.r", "선단에 열병이 돌아 25명을 잃었습니다.", "A fever runs through the convoy and 25 are lost.");
            Add("enc.quarantined_liner.leave", "떠난다", "Leave them");
            Add("enc.quarantined_liner.leave.r", "여객선의 등불이 멀어집니다.", "The liner's lamps recede.");
            Add("enc.lost_patrol.title", "길 잃은 순찰대", "THE LOST PATROL");
            Add("enc.lost_patrol.body", "탈영한 제국 순찰대가 길을 잃고 연료를 구걸합니다. 무장은 없습니다.", "A deserted Imperial patrol has lost its way and begs for fuel. They carry no weapons.");
            Add("enc.lost_patrol.fuel", "에테르 1을 준다", "Give them 1 aether");
            Add("enc.lost_patrol.fuel.r", "순찰대가 감사의 표시로 항로 정보를 넘겼습니다.", "The patrol repays you with route intelligence.");
            Add("enc.lost_patrol.recruit", "선단에 편입시킨다", "Recruit them");
            Add("enc.lost_patrol.recruit.r", "순찰대원들이 선단 경비를 맡았습니다.", "The patrol takes up convoy guard duty.");
            Add("enc.lost_patrol.leave", "돌려보낸다", "Send them off");
            Add("enc.lost_patrol.leave.r", "순찰대는 흩어졌습니다.", "The patrol scatters.");
            Add("enc.collapsing_spire.title", "무너지는 첨탑", "THE COLLAPSING SPIRE");
            Add("enc.collapsing_spire.body", "공중 첨탑 도시가 기울고 있습니다. 주민들이 위층에 갇혀 있습니다.", "A spire-city leans further every minute. Its people are trapped on the upper floors.");
            Add("enc.collapsing_spire.bridge", "선체를 붙여 다리를 만든다", "Bridge the gap with the hull");
            Add("enc.collapsing_spire.bridge.r", "주민들이 선체를 건너 살아났습니다.", "The people cross the hull to safety.");
            Add("enc.collapsing_spire.bridge_fail", "붕괴", "Collapse");
            Add("enc.collapsing_spire.bridge_fail.r", "첨탑이 무너지며 선체를 긁었고 일부만 구했습니다.", "The spire falls against the hull; only some are saved.");
            Add("enc.collapsing_spire.wings", "편대로 실어 나른다 (군수품 1)", "Ferry them by wing (1 ordnance)");
            Add("enc.collapsing_spire.wings.r", "편대가 왕복하며 주민을 옮겼습니다.", "The wings shuttle the people out.");
            Add("enc.collapsing_spire.leave", "떠난다", "Leave");
            Add("enc.collapsing_spire.leave.r", "첨탑이 구름 속으로 사라집니다.", "The spire disappears into the clouds.");
            Add("enc.throne_pilgrims_stranded.title", "왕좌의 순례자", "PILGRIMS OF THE THRONE");
            Add("enc.throne_pilgrims_stranded.body", "천공 왕좌를 향하던 순례선단이 연료를 다 쓰고 멈췄습니다. 그들은 문을 봤다고 말합니다.", "A pilgrim fleet bound for the Sky Throne has run dry. They say they have seen the gate.");
            Add("enc.throne_pilgrims_stranded.share", "에테르 2를 나눠 함께 간다", "Share 2 aether and travel together");
            Add("enc.throne_pilgrims_stranded.share.r", "순례자들이 문까지의 마지막 항로를 알려 줬습니다.", "The pilgrims describe the last stretch to the gate.");
            Add("enc.throne_pilgrims_stranded.take", "순례자만 태운다", "Take the pilgrims aboard");
            Add("enc.throne_pilgrims_stranded.take.r", "순례선은 버려졌지만 사람들은 살았습니다.", "The pilgrim ships are left behind; the people live.");
            Add("enc.throne_pilgrims_stranded.leave", "지나친다", "Pass by");
            Add("enc.throne_pilgrims_stranded.leave.r", "순례자들이 왕좌를 향해 기도합니다.", "The pilgrims pray toward the throne.");
            Add("enc.ice_locked_freighter.title", "결빙된 화물선", "THE ICE-LOCKED FREIGHTER");
            Add("enc.ice_locked_freighter.body", "화물선이 얼음에 갇혀 있습니다. 화물칸은 봉인된 채입니다.", "A freighter is locked in ice with its holds still sealed.");
            Add("enc.ice_locked_freighter.thaw", "천천히 녹여 화물을 꺼낸다", "Thaw it slowly");
            Add("enc.ice_locked_freighter.thaw.r", "보급과 자재를 회수했습니다.", "Supplies and materials recovered.");
            Add("enc.ice_locked_freighter.blast", "에테르로 얼음을 깬다 (에테르 1)", "Blast the ice (1 aether)");
            Add("enc.ice_locked_freighter.blast.r", "화물 전체를 빠르게 회수했습니다.", "The whole cargo comes free quickly.");
            Add("enc.ice_locked_freighter.leave", "떠난다", "Leave it");
            Add("enc.ice_locked_freighter.leave.r", "화물선은 얼음 속에 남았습니다.", "The freighter stays in the ice.");
            Add("enc.abyss_relic_field.title", "심연 유물 지대", "THE ABYSSAL RELIC FIELD");
            Add("enc.abyss_relic_field.body", "구름 밑바닥에서 고대 유물이 떠오릅니다. 코어가 불안하게 공명합니다.", "Ancient relics rise from the cloud floor. Your core resonates uneasily.");
            Add("enc.abyss_relic_field.gather", "최대한 수집한다", "Gather everything");
            Add("enc.abyss_relic_field.gather.r", "유물은 값지지만 코어가 진동합니다.", "The relics are priceless; the core shudders.");
            Add("enc.abyss_relic_field.careful", "[엘프] 공명을 조율하며 고른다", "[Elf] Tune the resonance while choosing");
            Add("enc.abyss_relic_field.careful.r", "코어가 안정된 채 유물을 골라냈습니다.", "The core stays calm as you pick the relics.");
            Add("enc.abyss_relic_field.skirt", "가장자리만 훑는다", "Skirt the field");
            Add("enc.abyss_relic_field.skirt.r", "약간의 유물을 얻었습니다.", "A few relics gathered.");
            Add("enc.cordon_supply_dump.title", "봉쇄선 보급소", "THE CORDON SUPPLY DUMP");
            Add("enc.cordon_supply_dump.body", "버려진 제국 보급소가 부표에 매달려 있습니다. 경비는 없지만 감시 장치가 있을지 모릅니다.", "An abandoned Imperial supply dump hangs from buoys. No guards, but perhaps sensors.");
            Add("enc.cordon_supply_dump.raid", "전부 털어 간다", "Raid it all");
            Add("enc.cordon_supply_dump.raid.r", "감시 장치는 없었습니다. 보급소를 비웠습니다.", "No sensors after all; the dump is yours.");
            Add("enc.cordon_supply_dump.raid_fail", "경보", "Alarm");
            Add("enc.cordon_supply_dump.raid_fail.r", "경보가 울리고 순찰함이 나타났습니다!", "An alarm sounds and a patrol arrives!");
            Add("enc.cordon_supply_dump.scout", "[정찰선] 감시 장치를 먼저 무력화한다", "[Pathfinder] Disable the sensors first");
            Add("enc.cordon_supply_dump.scout.r", "조용히 보급소를 비웠습니다.", "You empty the dump in silence.");
            Add("enc.cordon_supply_dump.leave", "건드리지 않는다", "Leave it");
            Add("enc.cordon_supply_dump.leave.r", "보급소가 뒤에서 흔들립니다.", "The dump sways behind you.");
            Add("enc.whale_bone_reef.title", "고래뼈 암초", "THE WHALEBONE REEF");
            Add("enc.whale_bone_reef.body", "하늘고래의 뼈로 이루어진 암초입니다. 뼈 사이에 에테르 결정이 맺혀 있습니다.", "A reef of sky-whale bone. Aether crystals cling between the ribs.");
            Add("enc.whale_bone_reef.mine", "결정을 캔다", "Mine the crystals");
            Add("enc.whale_bone_reef.mine.r", "에테르를 얻었습니다.", "Aether gained.");
            Add("enc.whale_bone_reef.respect", "[조인] 뼈를 건드리지 않고 노래로 결정을 부른다", "[Avian] Sing the crystals loose without touching the bones");
            Add("enc.whale_bone_reef.respect.r", "결정이 스스로 떨어졌습니다.", "The crystals drop on their own.");
            Add("enc.whale_bone_reef.leave", "지나간다", "Pass by");
            Add("enc.whale_bone_reef.leave.r", "암초가 뒤로 멀어집니다.", "The reef recedes.");
            Add("enc.sunken_arsenal.title", "가라앉은 무기고", "THE SUNKEN ARSENAL");
            Add("enc.sunken_arsenal.body", "구름 아래로 가라앉는 무기고가 마지막 불빛을 깜빡입니다.", "An arsenal sinking into the clouds blinks its last lights.");
            Add("enc.sunken_arsenal.dive", "급강하해 회수한다", "Dive for it");
            Add("enc.sunken_arsenal.dive.r", "무기고를 비우고 빠져나왔습니다.", "You empty the arsenal and climb out.");
            Add("enc.sunken_arsenal.dive_fail", "압력 손상", "Pressure damage");
            Add("enc.sunken_arsenal.dive_fail.r", "급강하로 선체가 뒤틀렸고 일부만 회수했습니다.", "The dive warps the hull; you recover a little.");
            Add("enc.sunken_arsenal.wings", "편대를 보낸다 (군수품 1)", "Send the wings (1 ordnance)");
            Add("enc.sunken_arsenal.wings.r", "편대가 상자를 물고 돌아왔습니다.", "The wings return with crates.");
            Add("enc.sunken_arsenal.leave", "포기한다", "Let it sink");
            Add("enc.sunken_arsenal.leave.r", "무기고가 사라집니다.", "The arsenal is gone.");
            Add("enc.derelict_hospital_ship.title", "버려진 병원선", "THE DERELICT HOSPITAL SHIP");
            Add("enc.derelict_hospital_ship.body", "버려진 병원선에 의료품과 장비가 남아 있습니다.", "An abandoned hospital ship still holds medicine and equipment.");
            Add("enc.derelict_hospital_ship.medicine", "의료품을 회수한다", "Recover the medicine");
            Add("enc.derelict_hospital_ship.medicine.r", "부상자들이 치료를 받았습니다.", "The wounded are treated.");
            Add("enc.derelict_hospital_ship.equipment", "장비를 뜯어 의무실을 보강한다", "Strip equipment for the infirmary");
            Add("enc.derelict_hospital_ship.equipment.r", "의무실이 개량됐습니다.", "The infirmary is upgraded.");
            Add("enc.derelict_hospital_ship.leave", "떠난다", "Leave");
            Add("enc.derelict_hospital_ship.leave.r", "병원선이 떠돕니다.", "The hospital ship drifts on.");
            Add("enc.storm_wrecked_convoy.title", "폭풍에 부서진 선단", "THE STORM-WRECKED CONVOY");
            Add("enc.storm_wrecked_convoy.body", "폭풍이 다른 피난선단을 찢어 놓았습니다. 잔해 사이에 여전히 물자가 있습니다.", "The storm has torn another refugee convoy apart. Supplies still float among the wreckage.");
            Add("enc.storm_wrecked_convoy.salvage", "잔해를 인양한다", "Salvage the wreckage");
            Add("enc.storm_wrecked_convoy.salvage.r", "물자를 회수했지만 선단은 침묵했습니다.", "You recover supplies; the convoy is quiet.");
            Add("enc.storm_wrecked_convoy.honour", "희생자를 기리고 일부만 가져간다", "Honour the dead and take only what is needed");
            Add("enc.storm_wrecked_convoy.honour.r", "선단이 묵념했습니다.", "The convoy holds a moment of silence.");
            Add("enc.storm_wrecked_convoy.leave", "지나간다", "Pass by");
            Add("enc.storm_wrecked_convoy.leave.r", "잔해가 폭풍 속으로 사라집니다.", "The wreckage vanishes into the storm.");
            Add("enc.throne_watchtower.title", "왕좌의 감시탑", "THE THRONE WATCHTOWER");
            Add("enc.throne_watchtower.body", "천공 왕좌 외곽의 고대 감시탑이 아직 작동합니다. 안에는 문의 기록이 있습니다.", "An ancient watchtower on the throne's edge still hums. Inside are records of the gate.");
            Add("enc.throne_watchtower.records", "기록을 연구한다", "Study the records");
            Add("enc.throne_watchtower.records.r", "문의 약점을 알아냈습니다. 선단이 희망을 품습니다.", "You learn the gate's weakness; the convoy takes heart.");
            Add("enc.throne_watchtower.strip", "장치를 뜯어 판다", "Strip the machinery");
            Add("enc.throne_watchtower.strip.r", "값진 부품을 얻었습니다.", "Valuable parts recovered.");
            Add("enc.throne_watchtower.leave", "건드리지 않는다", "Leave it");
            Add("enc.throne_watchtower.leave.r", "감시탑이 계속 웅웅거립니다.", "The tower keeps humming.");
            Add("enc.pirate_cache.title", "해적의 은닉처", "THE PIRATE CACHE");
            Add("enc.pirate_cache.body", "암초 속에 해적의 은닉처가 있습니다. 함정이 있을 수 있습니다.", "A pirate cache is hidden in the reef. It may be trapped.");
            Add("enc.pirate_cache.goblin", "[고블린] 함정을 해체하고 연다", "[Goblin] Disarm the traps and open it");
            Add("enc.pirate_cache.goblin.r", "고블린들이 함정을 웃으며 해체했습니다.", "The goblins laugh as they disarm the traps.");
            Add("enc.pirate_cache.open", "그냥 연다", "Open it");
            Add("enc.pirate_cache.open.r", "함정은 없었습니다.", "No trap after all.");
            Add("enc.pirate_cache.open_fail", "폭발", "Explosion");
            Add("enc.pirate_cache.open_fail.r", "은닉처가 폭발했습니다.", "The cache explodes.");
            Add("enc.pirate_cache.leave", "떠난다", "Leave it");
            Add("enc.pirate_cache.leave.r", "은닉처는 암초에 남았습니다.", "The cache stays in the reef.");
            Add("enc.crystal_garden.title", "결정 정원", "THE CRYSTAL GARDEN");
            Add("enc.crystal_garden.body", "부유 섬에 에테르 결정 정원이 자랍니다. 지키는 이는 없습니다.", "An aether-crystal garden grows on a floating isle. No one tends it.");
            Add("enc.crystal_garden.harvest", "전부 수확한다", "Harvest it all");
            Add("enc.crystal_garden.harvest.r", "에테르가 넘칩니다.", "Aether overflows.");
            Add("enc.crystal_garden.tend", "일부만 거두고 나머지를 심는다", "Take some and replant");
            Add("enc.crystal_garden.tend.r", "정원이 다음 선단을 위해 남았습니다.", "The garden will feed the next convoy.");
            Add("enc.crystal_garden.leave", "지나간다", "Pass by");
            Add("enc.crystal_garden.leave.r", "정원이 빛납니다.", "The garden glitters.");
            Add("enc.ice_trading_post.title", "빙운 교역소", "THE ICEFIELD TRADING POST");
            Add("enc.ice_trading_post.body", "빙운 고원의 교역소가 방한 물자와 연료를 팝니다.", "A trading post on the icefield sells cold-weather stores and fuel.");
            Add("enc.ice_trading_post.stores", "인양물 5로 보급 6", "6 supplies for 5 salvage");
            Add("enc.ice_trading_post.stores.r", "보급이 늘었습니다.", "Supplies replenished.");
            Add("enc.ice_trading_post.fuel", "인양물 6으로 에테르 4", "4 aether for 6 salvage");
            Add("enc.ice_trading_post.fuel.r", "연료를 채웠습니다.", "Fuel topped up.");
            Add("enc.ice_trading_post.depart", "떠난다", "Leave");
            Add("enc.ice_trading_post.depart.r", "교역소가 눈보라에 묻힙니다.", "The post fades into the snow.");
            Add("enc.abyss_salvagers.title", "심연 인양꾼", "THE ABYSSAL SALVAGERS");
            Add("enc.abyss_salvagers.body", "심연 인양꾼들이 값진 부품과 군수품을 팝니다. 값은 인양물뿐입니다.", "Abyssal salvagers sell prized parts and ordnance. They take only salvage.");
            Add("enc.abyss_salvagers.ordnance", "인양물 8로 군수품 6", "6 ordnance for 8 salvage");
            Add("enc.abyss_salvagers.ordnance.r", "군수품이 늘었습니다.", "Ordnance purchased.");
            Add("enc.abyss_salvagers.plating", "인양물 10으로 장갑판", "Armor plating for 10 salvage");
            Add("enc.abyss_salvagers.plating.r", "장갑이 보강됐습니다.", "Armor reinforced.");
            Add("enc.abyss_salvagers.depart", "떠난다", "Leave");
            Add("enc.abyss_salvagers.depart.r", "인양꾼들이 심연으로 내려갑니다.", "The salvagers descend into the abyss.");
            Add("enc.cordon_smuggler_tunnel.title", "봉쇄선 밀수로", "THE CORDON SMUGGLER RUN");
            Add("enc.cordon_smuggler_tunnel.body", "봉쇄선을 뚫는 밀수꾼이 항로 정보와 물자를 팝니다.", "Smugglers who run the cordon sell routes and stores.");
            Add("enc.cordon_smuggler_tunnel.route", "인양물 6으로 항로 정보", "Route intelligence for 6 salvage");
            Add("enc.cordon_smuggler_tunnel.route.r", "다음 도약 비용이 줄었습니다.", "The next jumps cost less.");
            Add("enc.cordon_smuggler_tunnel.stores", "인양물 7로 보급 5·군수품 2", "5 supplies and 2 ordnance for 7 salvage");
            Add("enc.cordon_smuggler_tunnel.stores.r", "물자를 확보했습니다.", "Stores secured.");
            Add("enc.cordon_smuggler_tunnel.depart", "떠난다", "Leave");
            Add("enc.cordon_smuggler_tunnel.depart.r", "밀수꾼이 사라집니다.", "The smugglers vanish.");
            Add("enc.throne_court_merchant.title", "왕좌 궁정 상인", "THE THRONE COURT MERCHANT");
            Add("enc.throne_court_merchant.body", "천공 왕좌의 궁정 상인이 마지막 거래를 제안합니다. 값은 비싸지만 물건은 최고입니다.", "A merchant of the throne court offers one last trade. Expensive, but the best goods you will see.");
            Add("enc.throne_court_merchant.refit", "인양물 12로 기함 개장", "Full refit for 12 salvage");
            Add("enc.throne_court_merchant.refit.r", "선체와 장갑이 보강됐습니다.", "Hull and armor reinforced.");
            Add("enc.throne_court_merchant.wings", "인양물 10으로 편대 보충", "Wing refit for 10 salvage");
            Add("enc.throne_court_merchant.wings.r", "편대가 정원을 채웠습니다.", "Wings at full strength.");
            Add("enc.throne_court_merchant.depart", "떠난다", "Leave");
            Add("enc.throne_court_merchant.depart.r", "상인이 고개를 숙입니다.", "The merchant bows.");
            Add("enc.wandering_alchemist.title", "떠돌이 연금술사", "THE WANDERING ALCHEMIST");
            Add("enc.wandering_alchemist.body", "연금술사가 코어 안정제를 팝니다.", "An alchemist sells core stabilisers.");
            Add("enc.wandering_alchemist.stabilise", "인양물 5로 불안정 −30", "Cut instability by 30 for 5 salvage");
            Add("enc.wandering_alchemist.stabilise.r", "코어가 잠잠해졌습니다.", "The core settles.");
            Add("enc.wandering_alchemist.tonic", "보급 1로 사기 강장제", "Morale tonic for 1 supply");
            Add("enc.wandering_alchemist.tonic.r", "선단이 활기를 되찾았습니다.", "The convoy perks up.");
            Add("enc.wandering_alchemist.depart", "떠난다", "Leave");
            Add("enc.wandering_alchemist.depart.r", "연금술사가 손을 흔듭니다.", "The alchemist waves.");
            Add("enc.refugee_market.title", "피난민 장터", "THE REFUGEE MARKET");
            Add("enc.refugee_market.body", "다른 피난선단이 장터를 열었습니다. 물물교환입니다.", "Another refugee convoy has opened a barter market.");
            Add("enc.refugee_market.swap", "군수품 2를 보급 6과 교환", "Trade 2 ordnance for 6 supplies");
            Add("enc.refugee_market.swap.r", "보급이 늘었습니다.", "Supplies gained.");
            Add("enc.refugee_market.swap2", "보급 3을 에테르 2와 교환", "Trade 3 supplies for 2 aether");
            Add("enc.refugee_market.swap2.r", "연료가 늘었습니다.", "Fuel gained.");
            Add("enc.refugee_market.depart", "떠난다", "Leave");
            Add("enc.refugee_market.depart.r", "장터가 흩어집니다.", "The market disperses.");
            Add("enc.gunsmith_barge.title", "총포공 바지선", "THE GUNSMITH BARGE");
            Add("enc.gunsmith_barge.body", "총포공이 군수품과 정비를 팝니다.", "A gunsmith sells ordnance and tune-ups.");
            Add("enc.gunsmith_barge.ordnance", "인양물 5로 군수품 4", "4 ordnance for 5 salvage");
            Add("enc.gunsmith_barge.ordnance.r", "군수품을 구입했습니다.", "Ordnance purchased.");
            Add("enc.gunsmith_barge.tune", "인양물 6으로 무장실 정비 (수리)", "Weapons tune-up for 6 salvage");
            Add("enc.gunsmith_barge.tune.r", "무장실이 정비됐습니다.", "The weapons room is tuned.");
            Add("enc.gunsmith_barge.depart", "떠난다", "Leave");
            Add("enc.gunsmith_barge.depart.r", "바지선이 멀어집니다.", "The barge drifts off.");
            Add("enc.monastery_kitchens.title", "수도원 주방", "THE MONASTERY KITCHENS");
            Add("enc.monastery_kitchens.body", "수도원이 순례자에게 식량을 나눕니다. 기부를 받습니다.", "A monastery feeds pilgrims and accepts donations.");
            Add("enc.monastery_kitchens.donate", "인양물 4를 기부하고 식량을 받는다", "Donate 4 salvage for food");
            Add("enc.monastery_kitchens.donate.r", "보급과 축복을 받았습니다.", "Food and a blessing.");
            Add("enc.monastery_kitchens.free", "식량만 받는다", "Take the food only");
            Add("enc.monastery_kitchens.free.r", "수도사들이 조용히 식량을 건넸습니다.", "The monks hand over food in silence.");
            Add("enc.monastery_kitchens.depart", "떠난다", "Leave");
            Add("enc.monastery_kitchens.depart.r", "종소리가 울립니다.", "A bell rings.");
            Add("enc.captains_exchange.title", "함장 교환소", "THE CAPTAINS' EXCHANGE");
            Add("enc.captains_exchange.body", "자유 함장들이 정보와 장비를 교환하는 정박지입니다.", "An anchorage where free captains swap intelligence and gear.");
            Add("enc.captains_exchange.intel", "인양물 4로 항로 정보", "Route intelligence for 4 salvage");
            Add("enc.captains_exchange.intel.r", "앞길의 폭풍 정보를 얻었습니다.", "You learn where the storms are.");
            Add("enc.captains_exchange.human", "[인간] 옛 동료와 정보를 나눈다", "[Human] Trade stories with old comrades");
            Add("enc.captains_exchange.human.r", "공짜로 항로 정보와 군수품을 얻었습니다.", "Free intelligence and ordnance from old friends.");
            Add("enc.captains_exchange.depart", "떠난다", "Leave");
            Add("enc.captains_exchange.depart.r", "함장들이 경례합니다.", "The captains salute.");
            Add("enc.scrap_auction.title", "고철 경매", "THE SCRAP AUCTION");
            Add("enc.scrap_auction.body", "고철 경매가 열립니다. 헐값에 부품이 나오지만 품질은 복불복입니다.", "A scrap auction. Parts go cheap, quality is a gamble.");
            Add("enc.scrap_auction.bid", "인양물 5로 입찰", "Bid 5 salvage");
            Add("enc.scrap_auction.bid.r", "좋은 부품을 낙찰받았습니다.", "You win good parts.");
            Add("enc.scrap_auction.bid_fail", "불량품", "Junk");
            Add("enc.scrap_auction.bid_fail.r", "부품은 쓸모없었습니다.", "The parts are junk.");
            Add("enc.scrap_auction.sell", "인양물을 판다", "Sell scrap");
            Add("enc.scrap_auction.sell.r", "인양물 6을 보급 4로 바꿨습니다.", "6 salvage becomes 4 supplies.");
            Add("enc.scrap_auction.depart", "떠난다", "Leave");
            Add("enc.scrap_auction.depart.r", "경매가 끝났습니다.", "The auction closes.");
            Add("enc.ice_garrison.title", "빙운 수비대", "THE ICEFIELD GARRISON");
            Add("enc.ice_garrison.body", "얼어붙은 제국 수비대가 통행을 막습니다. 병사들은 추위에 지쳐 있습니다.", "A frozen Imperial garrison blocks the pass. Its soldiers are worn down by the cold.");
            Add("enc.ice_garrison.bribe", "보급 2를 넘긴다", "Hand over 2 supplies");
            Add("enc.ice_garrison.bribe.r", "수비대가 길을 열었습니다.", "The garrison opens the pass.");
            Add("enc.ice_garrison.dwarf", "[드워프] 난방을 고쳐 주고 통과한다", "[Dwarf] Fix their heating and pass");
            Add("enc.ice_garrison.dwarf.r", "수비대가 감사하며 길을 열었습니다.", "The grateful garrison waves you through.");
            Add("enc.ice_garrison.fight", "돌파한다", "Break through");
            Add("enc.ice_garrison.fight.r", "수비대가 포문을 엽니다.", "The garrison opens fire.");
            Add("enc.abyss_toll_keepers.title", "심연 통행세 징수인", "THE ABYSSAL TOLL KEEPERS");
            Add("enc.abyss_toll_keepers.body", "심연 해협의 징수인들은 제국 소속이 아닙니다. 그들은 인양물을 원합니다.", "The toll keepers of the Abyssal Strait answer to no empire. They want salvage.");
            Add("enc.abyss_toll_keepers.pay", "인양물 6을 낸다", "Pay 6 salvage");
            Add("enc.abyss_toll_keepers.pay.r", "징수인들이 길을 열었습니다.", "The keepers open the strait.");
            Add("enc.abyss_toll_keepers.goblin", "[고블린] 흥정으로 반값에 통과", "[Goblin] Haggle to half price");
            Add("enc.abyss_toll_keepers.goblin.r", "징수인들이 웃으며 받아들였습니다.", "The keepers accept with a grin.");
            Add("enc.abyss_toll_keepers.run", "돌파한다", "Run past");
            Add("enc.abyss_toll_keepers.run.r", "징수인들이 반응하지 못했습니다.", "The keepers fail to react.");
            Add("enc.abyss_toll_keepers.run_fail", "기뢰", "Mines");
            Add("enc.abyss_toll_keepers.run_fail.r", "기뢰가 터졌습니다.", "Mines detonate.");
            Add("enc.cordon_inquisitor.title", "봉쇄선 심문관", "THE CORDON INQUISITOR");
            Add("enc.cordon_inquisitor.body", "제국 심문관이 선단의 함장을 심문하겠다고 합니다.", "An Imperial inquisitor demands to question the convoy's captain.");
            Add("enc.cordon_inquisitor.submit", "심문에 응한다", "Submit to questioning");
            Add("enc.cordon_inquisitor.submit.r", "심문은 길었지만 통과했습니다.", "The questioning is long, but you pass.");
            Add("enc.cordon_inquisitor.human", "[인간] 옛 지위를 내세워 거절한다", "[Human] Invoke old rank and refuse");
            Add("enc.cordon_inquisitor.human.r", "심문관이 물러섰습니다.", "The inquisitor backs down.");
            Add("enc.cordon_inquisitor.fight", "포문을 연다", "Open fire");
            Add("enc.cordon_inquisitor.fight.r", "심문선이 결계를 올립니다.", "The inquisitor's ship raises its ward.");
            Add("enc.throne_gatekeepers.title", "왕좌의 문지기", "THE THRONE GATEKEEPERS");
            Add("enc.throne_gatekeepers.body", "천공 왕좌의 문지기들이 시험을 요구합니다. 통과하면 문까지의 길이 열립니다.", "The throne's gatekeepers demand a trial. Pass it and the way to the gate opens.");
            Add("enc.throne_gatekeepers.trial", "시험을 치른다", "Take the trial");
            Add("enc.throne_gatekeepers.trial.r", "문지기들이 길을 열고 선단을 축복했습니다.", "The gatekeepers open the way and bless the convoy.");
            Add("enc.throne_gatekeepers.trial_fail", "시험 실패", "Trial failed");
            Add("enc.throne_gatekeepers.trial_fail.r", "문지기들이 전투로 시험합니다!", "The gatekeepers test you in battle!");
            Add("enc.throne_gatekeepers.elf", "[엘프] 고대의 노래로 시험을 대신한다", "[Elf] Answer with the ancient song");
            Add("enc.throne_gatekeepers.elf.r", "문지기들이 무릎을 꿇었습니다.", "The gatekeepers kneel.");
            Add("enc.throne_gatekeepers.fight", "싸운다", "Fight");
            Add("enc.throne_gatekeepers.fight.r", "문지기들이 무장을 펼칩니다.", "The gatekeepers arm.");
            Add("enc.conscription_sweep.title", "징집 수색", "THE CONSCRIPTION SWEEP");
            Add("enc.conscription_sweep.body", "제국 징집대가 선단의 젊은이들을 요구합니다.", "An Imperial press gang demands the convoy's young.");
            Add("enc.conscription_sweep.refuse", "거부하고 싸운다", "Refuse and fight");
            Add("enc.conscription_sweep.refuse.r", "징집대가 포문을 엽니다.", "The press gang opens fire.");
            Add("enc.conscription_sweep.bribe", "인양물 8로 눈감게 한다", "Bribe them with 8 salvage");
            Add("enc.conscription_sweep.bribe.r", "징집대가 떠났습니다.", "The press gang leaves.");
            Add("enc.conscription_sweep.orc", "[오크] 해병을 세워 위협한다", "[Orc] Face them down with marines");
            Add("enc.conscription_sweep.orc.r", "징집대가 물러섰습니다.", "The press gang backs off.");
            Add("enc.tariff_station.title", "관세 기지", "THE TARIFF STATION");
            Add("enc.tariff_station.body", "관세 기지가 화물의 10분의 1을 요구합니다.", "A tariff station demands a tenth of your cargo.");
            Add("enc.tariff_station.pay", "보급 1·인양물 3을 낸다", "Pay 1 supply and 3 salvage");
            Add("enc.tariff_station.pay.r", "통과했습니다.", "You pass.");
            Add("enc.tariff_station.forge", "서류를 위조한다", "Forge the manifests");
            Add("enc.tariff_station.forge.r", "위조는 통했습니다.", "The forgery works.");
            Add("enc.tariff_station.forge_fail", "적발", "Caught");
            Add("enc.tariff_station.forge_fail.r", "위조가 적발돼 벌금을 물었습니다.", "The forgery is caught and fined.");
            Add("enc.tariff_station.fight", "돌파한다", "Break through");
            Add("enc.tariff_station.fight.r", "기지가 포문을 엽니다.", "The station opens fire.");
            Add("enc.deserter_hunt.title", "탈영병 수색", "THE DESERTER HUNT");
            Add("enc.deserter_hunt.body", "제국군이 탈영병을 찾아 선단을 수색하려 합니다. 선단에 탈영병이 있을지도 모릅니다.", "Imperial troops want to search the convoy for deserters. There may be some aboard.");
            Add("enc.deserter_hunt.allow", "수색을 허락한다", "Allow the search");
            Add("enc.deserter_hunt.allow.r", "몇 명이 끌려갔습니다.", "A few are taken away.");
            Add("enc.deserter_hunt.hide", "숨긴다", "Hide them");
            Add("enc.deserter_hunt.hide.r", "아무도 발견되지 않았습니다.", "No one is found.");
            Add("enc.deserter_hunt.hide_fail", "발각", "Discovered");
            Add("enc.deserter_hunt.hide_fail.r", "숨긴 이들이 발각돼 전투가 시작됩니다!", "The hidden are found; battle!");
            Add("enc.deserter_hunt.fight", "거부한다", "Refuse");
            Add("enc.deserter_hunt.fight.r", "제국군이 무장을 펼칩니다.", "The troops arm.");
            Add("enc.weather_station_seizure.title", "기상 관측소 압수", "THE WEATHER STATION SEIZURE");
            Add("enc.weather_station_seizure.body", "제국이 기상 관측소를 봉쇄했습니다. 관측 자료가 있으면 폭풍을 피할 수 있습니다.", "The Empire has sealed a weather station. Its data would let you dodge the storms.");
            Add("enc.weather_station_seizure.buy", "인양물 5로 자료를 산다", "Buy the data for 5 salvage");
            Add("enc.weather_station_seizure.buy.r", "폭풍 경로를 얻었습니다.", "You learn the storm tracks.");
            Add("enc.weather_station_seizure.avian", "[조인] 하늘을 읽어 자료 없이 통과한다", "[Avian] Read the sky instead");
            Add("enc.weather_station_seizure.avian.r", "조인이 폭풍을 읽어 냈습니다.", "The avian reads the storms.");
            Add("enc.weather_station_seizure.leave", "지나친다", "Pass by");
            Add("enc.weather_station_seizure.leave.r", "관측소가 멀어집니다.", "The station recedes.");
            Add("enc.refugee_registration.title", "피난민 등록소", "THE REFUGEE REGISTRY");
            Add("enc.refugee_registration.body", "제국 등록소가 선단 전원의 등록을 요구합니다. 등록하면 추적당합니다.", "An Imperial registry demands every soul aboard be recorded. Registered means tracked.");
            Add("enc.refugee_registration.register", "등록한다", "Register");
            Add("enc.refugee_registration.register.r", "추격군이 위치를 알았지만 통과했습니다.", "The pursuit learns your position; you pass.");
            Add("enc.refugee_registration.partial", "일부만 등록한다", "Register only some");
            Add("enc.refugee_registration.partial.r", "등록관이 눈치채지 못했습니다.", "The registrar notices nothing.");
            Add("enc.refugee_registration.partial_fail", "적발", "Caught");
            Add("enc.refugee_registration.partial_fail.r", "등록관이 알아채고 초계함을 불렀습니다.", "The registrar calls a picket.");
            Add("enc.refugee_registration.fight", "등록소를 파괴한다", "Destroy the registry");
            Add("enc.refugee_registration.fight.r", "등록소가 방어선을 부릅니다.", "The registry calls its guards.");
            Add("enc.admiral_parley.title", "제독의 회담", "THE ADMIRAL'S PARLEY");
            Add("enc.admiral_parley.body", "추격군 제독이 회담을 제안합니다. 항복하면 선단은 살려 준다고 합니다.", "The pursuing admiral proposes a parley: surrender, and the convoy lives.");
            Add("enc.admiral_parley.refuse", "거절하고 떠난다", "Refuse and leave");
            Add("enc.admiral_parley.refuse.r", "제독이 침묵했습니다. 선단은 결의를 다졌습니다.", "The admiral says nothing. The convoy hardens.");
            Add("enc.admiral_parley.stall", "시간을 끌며 정보를 캔다", "Stall and probe");
            Add("enc.admiral_parley.stall.r", "제독의 함대 배치를 알아냈습니다.", "You learn the fleet's disposition.");
            Add("enc.admiral_parley.fight", "기함을 노린다", "Strike the flagship");
            Add("enc.admiral_parley.fight.r", "제독의 기함이 응전합니다!", "The admiral's flagship answers!");
            Add("enc.ice_storm.title", "얼음 폭풍", "THE ICE STORM");
            Add("enc.ice_storm.body", "얼음 폭풍이 선단을 덮칩니다. 갑판이 얼어붙습니다.", "An ice storm engulfs the convoy. The decks freeze.");
            Add("enc.ice_storm.heat", "에테르 1로 갑판을 녹인다", "Heat the decks (1 aether)");
            Add("enc.ice_storm.heat.r", "편대가 출격 가능 상태로 유지됐습니다.", "The wings stay ready.");
            Add("enc.ice_storm.endure", "버틴다", "Endure");
            Add("enc.ice_storm.endure.r", "장갑에 얼음이 끼었습니다.", "Ice cakes the armor.");
            Add("enc.ice_storm.dwarf", "[드워프] 용광로 열을 돌린다", "[Dwarf] Route forge heat");
            Add("enc.ice_storm.dwarf.r", "드워프들이 선단을 녹였습니다.", "The dwarves thaw the convoy.");
            Add("enc.abyss_undertow.title", "심연 역류", "THE ABYSSAL UNDERTOW");
            Add("enc.abyss_undertow.body", "구름 밑바닥에서 역류가 선단을 끌어내립니다.", "An undertow from the cloud floor drags the convoy down.");
            Add("enc.abyss_undertow.climb", "에테르 2로 전속 상승", "Climb at full burn (2 aether)");
            Add("enc.abyss_undertow.climb.r", "선단이 빠져나왔습니다.", "The convoy pulls free.");
            Add("enc.abyss_undertow.ride", "역류를 타고 내려갔다 올라온다", "Ride it down and out");
            Add("enc.abyss_undertow.ride.r", "심연에서 에테르를 건졌습니다.", "You come up with aether from the deep.");
            Add("enc.abyss_undertow.ride_fail", "압력", "Pressure");
            Add("enc.abyss_undertow.ride_fail.r", "선체가 압력에 눌렸습니다.", "The hull buckles under pressure.");
            Add("enc.abyss_undertow.anchor", "보급 1을 쓰며 정박한다", "Anchor and wait (1 supply)");
            Add("enc.abyss_undertow.anchor.r", "역류가 지나갔습니다.", "The undertow passes.");
            Add("enc.cordon_searchlights.title", "봉쇄선 탐조등", "THE CORDON SEARCHLIGHTS");
            Add("enc.cordon_searchlights.body", "폭풍 속에서 제국 탐조등이 선단을 훑습니다.", "Imperial searchlights sweep the storm for you.");
            Add("enc.cordon_searchlights.dark", "전등화 관제로 숨는다", "Run dark");
            Add("enc.cordon_searchlights.dark.r", "탐조등이 지나갔습니다.", "The lights pass over.");
            Add("enc.cordon_searchlights.fast", "전속으로 벗어난다 (에테르 1)", "Burn out of the sweep (1 aether)");
            Add("enc.cordon_searchlights.fast.r", "벗어났습니다.", "You are clear.");
            Add("enc.cordon_searchlights.caught", "그대로 간다", "Press on");
            Add("enc.cordon_searchlights.caught.r", "들키지 않았습니다.", "Unseen.");
            Add("enc.cordon_searchlights.caught_fail", "포착", "Spotted");
            Add("enc.cordon_searchlights.caught_fail.r", "탐조등이 선단을 잡았습니다!", "The searchlights find you!");
            Add("enc.throne_aurora.title", "왕좌의 오로라", "THE THRONE AURORA");
            Add("enc.throne_aurora.body", "천공 왕좌 위로 오로라가 흐릅니다. 코어가 노래합니다.", "An aurora flows above the Sky Throne. The core sings.");
            Add("enc.throne_aurora.bathe", "오로라 속으로 들어간다", "Fly into the aurora");
            Add("enc.throne_aurora.bathe.r", "코어가 가득 찼습니다.", "The core brims.");
            Add("enc.throne_aurora.elf", "[엘프] 오로라를 조율한다", "[Elf] Tune the aurora");
            Add("enc.throne_aurora.elf.r", "코어가 안정된 채 채워졌습니다.", "The core fills and stays calm.");
            Add("enc.throne_aurora.skirt", "가장자리를 지난다", "Skirt it");
            Add("enc.throne_aurora.skirt.r", "약간의 에테르를 얻었습니다.", "A little aether.");
            Add("enc.ash_cloud.title", "재 구름", "THE ASH CLOUD");
            Add("enc.ash_cloud.body", "화산재 구름이 항로를 덮습니다. 엔진 필터가 막힙니다.", "A volcanic ash cloud covers the lane. Engine filters clog.");
            Add("enc.ash_cloud.slow", "천천히 통과한다 (에테르 1)", "Go slowly (1 aether)");
            Add("enc.ash_cloud.slow.r", "필터를 갈며 통과했습니다.", "You swap filters as you go.");
            Add("enc.ash_cloud.fast", "단숨에 돌파한다", "Punch through");
            Add("enc.ash_cloud.fast.r", "엔진이 손상됐습니다.", "The engines take damage.");
            Add("enc.ash_cloud.around", "우회한다 (에테르 2)", "Go around (2 aether)");
            Add("enc.ash_cloud.around.r", "깨끗한 하늘로 돌아갔습니다.", "Clear skies around.");
            Add("enc.ghost_lights.title", "도깨비불", "THE GHOST LIGHTS");
            Add("enc.ghost_lights.body", "폭풍 속에 도깨비불이 선단을 유혹합니다. 항로를 잃기 쉽습니다.", "Ghost lights in the storm lure the convoy off course.");
            Add("enc.ghost_lights.ignore", "무시하고 계기 비행", "Ignore them and fly by instruments");
            Add("enc.ghost_lights.ignore.r", "무사히 지났습니다.", "Safely through.");
            Add("enc.ghost_lights.follow", "따라간다", "Follow them");
            Add("enc.ghost_lights.follow.r", "도깨비불이 숨겨진 연료고로 이끌었습니다.", "The lights lead to a hidden fuel cache.");
            Add("enc.ghost_lights.follow_fail", "미로", "Lost");
            Add("enc.ghost_lights.follow_fail.r", "항로를 잃고 연료를 태웠습니다.", "You lose the lane and burn fuel.");
            Add("enc.ghost_lights.avian", "[조인] 진짜 별을 읽는다", "[Avian] Read the true stars");
            Add("enc.ghost_lights.avian.r", "조인이 선단을 이끌었습니다.", "The avian leads the convoy through.");
            Add("enc.crystal_rain.title", "결정 비", "THE CRYSTAL RAIN");
            Add("enc.crystal_rain.body", "에테르 결정이 비처럼 쏟아집니다. 갑판을 열면 모을 수 있지만 위험합니다.", "Aether crystals fall like rain. Opening the decks would gather them — dangerously.");
            Add("enc.crystal_rain.open", "갑판을 열어 모은다", "Open the decks");
            Add("enc.crystal_rain.open.r", "에테르가 모였지만 갑판이 긁혔습니다.", "Aether gathered; the decks are scarred.");
            Add("enc.crystal_rain.closed", "갑판을 닫고 지난다", "Keep the decks closed");
            Add("enc.crystal_rain.closed.r", "무사히 지났습니다.", "Safely through.");
            Add("enc.crystal_rain.goblin", "[고블린] 그물로 받는다", "[Goblin] Catch it in nets");
            Add("enc.crystal_rain.goblin.r", "고블린들이 그물 가득 결정을 받았습니다.", "The goblins fill their nets.");
            Add("enc.pressure_front.title", "기압 전선", "THE PRESSURE FRONT");
            Add("enc.pressure_front.body", "급격한 기압 변화가 승무원을 쓰러뜨립니다.", "A violent pressure change knocks crew off their feet.");
            Add("enc.pressure_front.medic", "의무실을 가동한다 (보급 1)", "Run the infirmary (1 supply)");
            Add("enc.pressure_front.medic.r", "승무원이 회복했습니다.", "The crew recover.");
            Add("enc.pressure_front.endure", "버틴다", "Endure");
            Add("enc.pressure_front.endure.r", "선단 일부가 앓았습니다.", "Some of the convoy fall ill.");
            Add("enc.pressure_front.climb", "에테르 1로 고도를 바꾼다", "Change altitude (1 aether)");
            Add("enc.pressure_front.climb.r", "전선을 피했습니다.", "You dodge the front.");
            Add("enc.thunder_leviathan_pod.title", "천둥 리바이어던 무리", "THE THUNDER LEVIATHAN POD");
            Add("enc.thunder_leviathan_pod.body", "리바이어던 무리가 폭풍과 함께 이동합니다. 그 사이에 숨으면 추격을 따돌릴 수 있습니다.", "A pod of leviathans travels with the storm. Hiding among them could shake the pursuit.");
            Add("enc.thunder_leviathan_pod.hide", "무리 사이에 숨는다", "Hide among them");
            Add("enc.thunder_leviathan_pod.hide.r", "추격군이 무리에 막혔습니다.", "The pursuit is blocked by the pod.");
            Add("enc.thunder_leviathan_pod.hide_fail", "꼬리", "The tail");
            Add("enc.thunder_leviathan_pod.hide_fail.r", "리바이어던의 꼬리가 선체를 쳤습니다.", "A leviathan's tail strikes the hull.");
            Add("enc.thunder_leviathan_pod.avian", "[조인] 노래로 무리와 함께 간다", "[Avian] Sing and travel with the pod");
            Add("enc.thunder_leviathan_pod.avian.r", "리바이어던들이 선단을 호위했습니다.", "The leviathans escort the convoy.");
            Add("enc.thunder_leviathan_pod.avoid", "피한다 (에테르 1)", "Avoid them (1 aether)");
            Add("enc.thunder_leviathan_pod.avoid.r", "무리를 돌아갔습니다.", "You go around the pod.");
            Add("enc.eye_of_silence.title", "침묵의 눈", "THE EYE OF SILENCE");
            Add("enc.eye_of_silence.body", "폭풍의 눈 안은 완전한 정적입니다. 승무원이 쉴 수 있습니다.", "Inside the storm's eye there is perfect silence. The crew could rest.");
            Add("enc.eye_of_silence.rest", "정박해 쉰다 (보급 1)", "Anchor and rest (1 supply)");
            Add("enc.eye_of_silence.rest.r", "승무원과 선단이 회복했습니다.", "Crew and convoy recover.");
            Add("enc.eye_of_silence.repair", "쉬는 동안 수리한다 (인양물 4)", "Repair while resting (4 salvage)");
            Add("enc.eye_of_silence.repair.r", "선체가 수리됐습니다.", "The hull is patched.");
            Add("enc.eye_of_silence.move", "쉬지 않고 나간다", "Move on");
            Add("enc.eye_of_silence.move.r", "선단은 계속 나아갔습니다.", "The convoy presses on.");
        }
    }
}
