namespace AetherArk.Content
{
    /// <summary>Event strings. Generated from tools/gen_events.py data; keep in sync with EncounterLibrary.</summary>
    public sealed partial class LocalizationService
    {
        private void AddEncounterStrings()
        {
            Add("enc.burning_ferry.title", "불타는 연락선", "THE BURNING FERRY");
            Add("enc.burning_ferry.body", "엔진 화재가 번진 연락선이 구름 위를 헤맵니다. 갑판에 승객이 몰려 있고, 불길은 몇 분 안에 연료고에 닿을 것입니다.", "A ferry drifts above the clouds with an engine fire spreading toward its fuel bunker. Passengers crowd the deck; you have minutes.");
            Add("enc.burning_ferry.teams", "소화반을 보내 차분히 구조한다 (보급 1)", "Send fire teams and evacuate methodically (1 supply)");
            Add("enc.burning_ferry.teams.r", "소화반이 불길을 잡는 동안 승객 40명이 옮겨 탔습니다.", "Fire teams hold the blaze while forty passengers cross.");
            Add("enc.burning_ferry.dash", "선체를 붙이고 전원 탈출시킨다 — 위험한 접근", "Lash hulls and take everyone — a dangerous approach");
            Add("enc.burning_ferry.dash.r", "무모했지만 통했습니다. 70명이 살았고 선단이 환호합니다.", "Reckless, but it works. Seventy are saved and the convoy cheers.");
            Add("enc.burning_ferry.dash_fail", "연료고 폭발", "The bunker detonates");
            Add("enc.burning_ferry.dash_fail.r", "연료고가 터지며 선체가 그을렸습니다. 20명만 구했습니다.", "The bunker blows; the hull is scorched and only twenty are pulled clear.");
            Add("enc.burning_ferry.leave", "거리를 둔다", "Keep your distance");
            Add("enc.burning_ferry.leave.r", "폭발의 빛이 구름을 물들이고, 선단은 침묵합니다.", "The explosion lights the clouds, and the convoy falls silent.");
            Add("enc.ice_locked_lifeboats.title", "결빙된 구명정", "ICE-LOCKED LIFEBOATS");
            Add("enc.ice_locked_lifeboats.body", "얼어붙은 구명정 세 척이 빙운 속에 갇혀 있습니다. 안에서 두드리는 소리가 들립니다.", "Three lifeboats hang frozen inside an ice cloud. Something knocks from within.");
            Add("enc.ice_locked_lifeboats.thaw", "[드워프] 용광로 배관으로 천천히 녹인다 (보급 1)", "[Dwarf] Thaw them with forge lines (1 supply)");
            Add("enc.ice_locked_lifeboats.thaw.r", "드워프 기술자들이 얼음을 녹여 30명을 무사히 데려왔습니다.", "Dwarven hands melt the ice away and thirty come aboard unharmed.");
            Add("enc.ice_locked_lifeboats.blast", "에테르로 얼음을 깨뜨린다 (에테르 1)", "Crack the ice with an aether pulse (1 aether)");
            Add("enc.ice_locked_lifeboats.blast.r", "얼음이 깨지고 구명정과 장비를 회수했습니다.", "The ice shatters; you recover the boats and their gear.");
            Add("enc.ice_locked_lifeboats.leave", "두드림을 뒤로하고 떠난다", "Leave the knocking behind");
            Add("enc.ice_locked_lifeboats.leave.r", "두드리는 소리가 잦아들 때까지 아무도 말을 하지 않았습니다.", "No one speaks until the knocking fades.");
            Add("enc.mutiny_transport.title", "반란 수송선", "THE MUTINOUS TRANSPORT");
            Add("enc.mutiny_transport.body", "수송선의 승무원이 선장을 가두고 선단 합류를 요구합니다. 승객들은 겁에 질려 있습니다.", "A transport's crew has locked up their captain and demand to join the convoy. The passengers are terrified.");
            Add("enc.mutiny_transport.intimidate", "[오크] 무장 승무원을 보내 질서를 잡는다", "[Orc] Send armed crew to restore order");
            Add("enc.mutiny_transport.intimidate.r", "반란자들은 오크 해병을 보자마자 무기를 내렸습니다.", "The mutineers drop their weapons the moment the orc marines board.");
            Add("enc.mutiny_transport.negotiate", "보급 2를 주고 협상한다", "Negotiate with 2 supplies");
            Add("enc.mutiny_transport.negotiate.r", "보급을 나누자 양측이 합류에 동의했습니다.", "Shared stores bring both sides to the table.");
            Add("enc.mutiny_transport.refuse", "반란선을 선단에 들이지 않는다", "Refuse the mutineers");
            Add("enc.mutiny_transport.refuse.r", "수송선은 홀로 구름 속으로 사라졌습니다.", "The transport vanishes alone into the clouds.");
            Add("enc.plague_barge.title", "역병 바지선", "THE PLAGUE BARGE");
            Add("enc.plague_barge.body", "격리 깃발을 단 바지선이 도움을 청합니다. 생존자들은 열에 시달리지만 아직 걸을 수 있습니다.", "A barge flying quarantine flags pleads for help. Its survivors are feverish but still on their feet.");
            Add("enc.plague_barge.quarantine", "[병원선] 격리 병동으로 받아들인다", "[Hospital ship] Take them into the isolation ward");
            Add("enc.plague_barge.quarantine.r", "병원선이 환자를 받았고 역병은 번지지 않았습니다.", "The hospital ship takes the sick, and the fever spreads no further.");
            Add("enc.plague_barge.take", "그냥 받아들인다 — 절반의 도박", "Take them anyway — a coin toss");
            Add("enc.plague_barge.take.r", "열이 가라앉았습니다. 60명이 합류했습니다.", "The fever breaks. Sixty join the convoy.");
            Add("enc.plague_barge.take_fail", "역병 확산", "The fever spreads");
            Add("enc.plague_barge.take_fail.r", "역병이 선단에 번져 30명을 잃었습니다.", "The fever spreads through the convoy and thirty are lost.");
            Add("enc.plague_barge.refuse", "떠난다", "Leave them");
            Add("enc.plague_barge.refuse.r", "바지선의 신호가 점점 약해집니다.", "The barge's signal grows fainter.");
            Add("enc.child_choir.title", "떠도는 성가대", "THE WANDERING CHOIR");
            Add("enc.child_choir.body", "음악학교 비행선이 연료를 다 쓰고 표류합니다. 아이들이 갑판에서 노래하며 신호를 보냅니다.", "A music-school airship has run dry. Children on its deck sing to signal you.");
            Add("enc.child_choir.take", "모두 태운다 (보급 1)", "Take them all aboard (1 supply)");
            Add("enc.child_choir.take.r", "성가대의 노래가 선단 통신망에 퍼지자 사기가 치솟았습니다.", "Their song spreads across the convoy channel and morale soars.");
            Add("enc.child_choir.fuel", "에테르 1을 나눠 준다", "Share 1 aether");
            Add("enc.child_choir.fuel.r", "비행선은 다시 떠올랐고, 아이들이 손을 흔들었습니다.", "The airship lifts again; the children wave.");
            Add("enc.child_choir.leave", "지나친다", "Pass them by");
            Add("enc.child_choir.leave.r", "노래가 뒤에서 잦아듭니다.", "The song fades behind you.");
            Add("enc.imperial_deserters.title", "제국 탈영병", "IMPERIAL DESERTERS");
            Add("enc.imperial_deserters.body", "제국 순찰정 한 척이 항복 깃발을 올렸습니다. 승무원은 탈영을 원하며 무기고를 대가로 내놓습니다.", "An imperial picket raises a surrender flag. Its crew want to desert and offer their magazine in return.");
            Add("enc.imperial_deserters.accept", "받아들인다", "Take them in");
            Add("enc.imperial_deserters.accept.r", "군수품을 받았지만 선단 일부는 제국 제복을 불신합니다.", "You gain ordnance, but parts of the convoy distrust the uniforms.");
            Add("enc.imperial_deserters.interrogate", "[인간] 옛 동료로서 항로 정보를 얻는다", "[Human] Trade on old ties for route intelligence");
            Add("enc.imperial_deserters.interrogate.r", "탈영병이 제국 연료고 좌표를 넘겼습니다.", "The deserters hand over the coordinates of an imperial fuel cache.");
            Add("enc.imperial_deserters.refuse", "거절한다", "Turn them away");
            Add("enc.imperial_deserters.refuse.r", "순찰정은 항복 깃발을 내리고 멀어졌습니다.", "The picket lowers its flag and drifts away.");
            Add("enc.stranded_engineers.title", "조난 기술자", "STRANDED ENGINEERS");
            Add("enc.stranded_engineers.body", "부서진 정비선의 기술자들이 공구를 든 채 구조를 기다립니다.", "Engineers from a wrecked tender wait for rescue, tools in hand.");
            Add("enc.stranded_engineers.take", "태우고 수리를 맡긴다", "Take them aboard and put them to work");
            Add("enc.stranded_engineers.take.r", "기술자들이 선체 균열을 메웠습니다.", "The engineers weld the flagship's cracks shut.");
            Add("enc.stranded_engineers.pay", "인양물 3을 주고 정식 수리를 부탁한다", "Pay 3 salvage for a proper refit");
            Add("enc.stranded_engineers.pay.r", "자재를 받은 기술자들이 장갑판까지 손봤습니다.", "With materials in hand they patch armor as well as hull.");
            Add("enc.stranded_engineers.leave", "떠난다", "Leave them");
            Add("enc.stranded_engineers.leave.r", "정비선의 불빛이 꺼졌습니다.", "The tender's lights go dark.");
            Add("enc.sky_whale_calf.title", "다친 하늘고래 새끼", "THE WOUNDED SKY-WHALE CALF");
            Add("enc.sky_whale_calf.body", "그물에 얽힌 하늘고래 새끼가 선단 곁을 맴돕니다. 어미는 보이지 않습니다.", "A sky-whale calf tangled in netting circles the convoy. Its mother is nowhere in sight.");
            Add("enc.sky_whale_calf.calm", "[조인] 노래로 달래며 그물을 푼다", "[Avian] Sing it calm and cut the net");
            Add("enc.sky_whale_calf.calm.r", "풀려난 새끼가 에테르 결정을 떨어뜨리고 떠났습니다.", "Freed, the calf sheds an aether crystal and swims away.");
            Add("enc.sky_whale_calf.free", "보급 1을 미끼로 그물을 푼다", "Lure it with 1 supply and cut the net");
            Add("enc.sky_whale_calf.free.r", "새끼가 선단 주위를 한 바퀴 돌고 사라졌습니다.", "The calf circles the convoy once and vanishes.");
            Add("enc.sky_whale_calf.harvest", "사냥해 자원으로 쓴다", "Harvest it");
            Add("enc.sky_whale_calf.harvest.r", "자원은 얻었지만 선단은 그 울음을 잊지 못합니다.", "The convoy gains salvage and cannot forget the sound it made.");
            Add("enc.wreck_signal_trap.title", "부르는 난파선", "THE WRECK THAT CALLED");
            Add("enc.wreck_signal_trap.body", "구조 신호가 나오는 난파선 주위로 기류가 이상하게 고요합니다.", "A wreck broadcasts a distress call. The air around it is strangely still.");
            Add("enc.wreck_signal_trap.detect", "[정찰선] 주변을 먼저 훑는다", "[Pathfinder] Sweep the approach first");
            Add("enc.wreck_signal_trap.detect.r", "정찰선이 매복 기뢰를 찾아냈고, 난파선은 조용히 인양됐습니다.", "The pathfinder finds the ambush mines; the wreck is quietly salvaged.");
            Add("enc.wreck_signal_trap.approach", "그대로 접근한다 (55%)", "Approach directly (55%)");
            Add("enc.wreck_signal_trap.approach.r", "진짜 생존자였습니다. 50명이 합류했습니다.", "The call was real. Fifty survivors join you.");
            Add("enc.wreck_signal_trap.ambush", "매복", "Ambush");
            Add("enc.wreck_signal_trap.ambush.r", "난파선 뒤에서 제국 커터가 튀어나옵니다!", "An imperial cutter bursts from behind the wreck!");
            Add("enc.wreck_signal_trap.ignore", "무시한다", "Ignore the call");
            Add("enc.wreck_signal_trap.ignore.r", "신호가 뒤에서 되풀이됩니다.", "The signal repeats behind you.");
            Add("enc.derelict_cruiser.title", "표류 순양함", "THE DERELICT CRUISER");
            Add("enc.derelict_cruiser.body", "제국 순양함 한 척이 등을 꺼트린 채 표류합니다. 무장은 남아 있고 코어는 불안정하게 웅웅거립니다.", "An imperial cruiser drifts dark. Its guns are intact and its core hums unsteadily.");
            Add("enc.derelict_cruiser.strip", "무장고를 뜯어낸다", "Strip the magazines");
            Add("enc.derelict_cruiser.strip.r", "군수품과 부품을 확보했습니다.", "Ordnance and parts secured.");
            Add("enc.derelict_cruiser.core", "[드워프] 코어를 추출한다 (70%)", "[Dwarf] Extract the core (70%)");
            Add("enc.derelict_cruiser.core.r", "코어가 안전하게 빠져나왔습니다.", "The core comes free cleanly.");
            Add("enc.derelict_cruiser.core_fail", "코어 폭주", "Core surge");
            Add("enc.derelict_cruiser.core_fail.r", "코어가 폭주하며 선체를 태웠습니다.", "The core surges and scorches the hull.");
            Add("enc.derelict_cruiser.leave", "손대지 않는다", "Leave it");
            Add("enc.derelict_cruiser.leave.r", "순양함은 계속 표류합니다.", "The cruiser drifts on.");
            Add("enc.aether_geyser.title", "에테르 간헐천", "THE AETHER GEYSER");
            Add("enc.aether_geyser.body", "구름 아래에서 에테르 기둥이 주기적으로 솟구칩니다.", "Columns of aether erupt from beneath the clouds at intervals.");
            Add("enc.aether_geyser.harvest", "코어를 열어 최대한 흡수한다", "Open the core and drink deep");
            Add("enc.aether_geyser.harvest.r", "에테르는 넘치지만 코어가 불안하게 떨립니다.", "Aether overflows; the core shudders.");
            Add("enc.aether_geyser.careful", "가장자리에서 조심스럽게 채집한다", "Skim the edges carefully");
            Add("enc.aether_geyser.careful.r", "안전하게 에테르를 채웠습니다.", "Aether gathered safely.");
            Add("enc.aether_geyser.pass", "지나간다", "Pass it by");
            Add("enc.aether_geyser.pass.r", "간헐천이 뒤에서 솟구칩니다.", "The geyser erupts behind you.");
            Add("enc.floating_monastery.title", "부유 수도원", "THE FLOATING MONASTERY");
            Add("enc.floating_monastery.body", "버려진 수도원이 조용히 떠 있습니다. 성유물과 낡은 기도문이 남아 있습니다.", "An abandoned monastery floats in silence, relics and worn prayers still inside.");
            Add("enc.floating_monastery.relics", "성유물을 가져간다", "Take the relics");
            Add("enc.floating_monastery.relics.r", "성유물은 값지지만 순례자들이 눈을 돌립니다.", "The relics are valuable; the pilgrims look away.");
            Add("enc.floating_monastery.prayers", "기도문을 선단에 낭독한다", "Read the prayers to the convoy");
            Add("enc.floating_monastery.prayers.r", "오래된 기도가 선단을 달랬습니다.", "Old words steady the convoy.");
            Add("enc.floating_monastery.resonate", "[엘프] 성가의 공명으로 코어를 채운다", "[Elf] Tune the core to the chant");
            Add("enc.floating_monastery.resonate.r", "성가가 코어에 에테르를 불어넣었습니다.", "The chant breathes aether into the core.");
            Add("enc.mine_field.title", "옛 기뢰 지대", "THE OLD MINEFIELD");
            Add("enc.mine_field.body", "옛 전쟁의 기뢰가 항로를 막습니다. 기뢰 사이에 침몰선 잔해가 보입니다.", "Mines from an old war block the lane. Wreckage glints between them.");
            Add("enc.mine_field.chart", "[정찰선] 안전한 길을 그린다", "[Pathfinder] Chart a safe path");
            Add("enc.mine_field.chart.r", "정찰선이 기뢰를 해체해 군수품으로 만들었습니다.", "The pathfinder defuses mines into ordnance.");
            Add("enc.mine_field.thread", "기뢰 사이를 통과한다 (60%)", "Thread the mines (60%)");
            Add("enc.mine_field.thread.r", "잔해를 챙겨 무사히 빠져나왔습니다.", "You pull salvage from the wreck and slip out.");
            Add("enc.mine_field.thread_fail", "기뢰 접촉", "Mine strike");
            Add("enc.mine_field.thread_fail.r", "기뢰가 터져 장갑이 찢겼습니다.", "A mine detonates against the armor.");
            Add("enc.mine_field.avoid", "우회한다 (에테르 1)", "Go around (1 aether)");
            Add("enc.mine_field.avoid.r", "연료를 태워 기뢰 지대를 돌아갔습니다.", "You burn fuel to skirt the field.");
            Add("enc.crashed_courier.title", "추락한 급사선", "THE CRASHED COURIER");
            Add("enc.crashed_courier.body", "암호 장치가 켜진 채 추락한 제국 급사선이 있습니다.", "An imperial courier has crashed with its cipher engine still running.");
            Add("enc.crashed_courier.decode", "암호를 풀어 보급 좌표를 찾는다", "Decode it for depot coordinates");
            Add("enc.crashed_courier.decode.r", "근처 보급 좌표를 얻었습니다.", "You find a nearby depot's coordinates.");
            Add("enc.crashed_courier.sell", "장치를 뜯어 팔 준비를 한다", "Rip out the engine to sell");
            Add("enc.crashed_courier.sell.r", "암호 장치는 값이 나갈 것입니다.", "The engine will fetch a good price.");
            Add("enc.crashed_courier.burn", "급사선을 불태워 흔적을 지운다", "Burn the courier to hide your trail");
            Add("enc.crashed_courier.burn.r", "추격군이 며칠은 헤맬 것입니다.", "The pursuit will chase ghosts for days.");
            Add("enc.cloud_farm.title", "구름 농장 잔해", "THE CLOUD FARM");
            Add("enc.cloud_farm.body", "부서진 수경 농장이 떠다닙니다. 작물은 아직 살아 있고, 농부들도 일부 남았습니다.", "A broken hydroponic farm drifts by. Its crops still live, and so do a few farmers.");
            Add("enc.cloud_farm.harvest", "작물을 거둔다", "Harvest the crops");
            Add("enc.cloud_farm.harvest.r", "보급이 늘었습니다.", "Supplies replenished.");
            Add("enc.cloud_farm.settle", "농부들과 작물을 함께 태운다", "Take the farmers and their crops");
            Add("enc.cloud_farm.settle.r", "농부들이 선단 식량 관리를 맡았습니다.", "The farmers take charge of the convoy's rations.");
            Add("enc.cloud_farm.leave", "지나친다", "Leave it");
            Add("enc.cloud_farm.leave.r", "농장이 뒤로 멀어집니다.", "The farm drifts behind.");
            Add("enc.ordnance_cache.title", "봉인된 저장고", "THE SEALED CACHE");
            Add("enc.ordnance_cache.body", "제국 군수 저장고가 봉인된 채 절벽에 박혀 있습니다.", "A sealed imperial ordnance cache is wedged into a cliff.");
            Add("enc.ordnance_cache.careful", "천천히 봉인을 푼다", "Work the seal open slowly");
            Add("enc.ordnance_cache.careful.r", "군수품 일부를 회수했습니다.", "Some ordnance recovered.");
            Add("enc.ordnance_cache.blast", "폭파해서 연다 (65%)", "Blow it open (65%)");
            Add("enc.ordnance_cache.blast.r", "저장고가 통째로 열렸습니다.", "The whole cache is yours.");
            Add("enc.ordnance_cache.blast_fail", "유폭", "Sympathetic detonation");
            Add("enc.ordnance_cache.blast_fail.r", "저장고가 유폭해 선체가 흔들렸습니다.", "The cache cooks off and rattles the hull.");
            Add("enc.ordnance_cache.leave", "건드리지 않는다", "Leave it sealed");
            Add("enc.ordnance_cache.leave.r", "저장고는 절벽에 남았습니다.", "The cache stays in the cliff.");
            Add("enc.sky_kelp_forest.title", "하늘 켈프 숲", "THE SKY-KELP FOREST");
            Add("enc.sky_kelp_forest.body", "부유 켈프 숲이 항로를 덮습니다. 켈프 사이에 새 둥지와 오래된 잔해가 있습니다.", "Floating kelp blankets the lane, nests and old wreckage hidden in its fronds.");
            Add("enc.sky_kelp_forest.gather", "켈프를 거둔다", "Gather kelp");
            Add("enc.sky_kelp_forest.gather.r", "식용 켈프를 저장했습니다.", "Edible kelp stored.");
            Add("enc.sky_kelp_forest.scavenge", "[고블린] 둥지와 잔해를 뒤진다", "[Goblin] Pick through the nests and wreckage");
            Add("enc.sky_kelp_forest.scavenge.r", "고블린들이 켈프 속에서 값진 부품을 찾았습니다.", "The goblins find valuable parts in the fronds.");
            Add("enc.sky_kelp_forest.push", "밀고 나간다 (에테르 1)", "Push through (1 aether)");
            Add("enc.sky_kelp_forest.push.r", "켈프를 헤치고 나왔습니다.", "You force a way through.");
            Add("enc.gate_shard.title", "천공문 파편", "THE GATE SHARD");
            Add("enc.gate_shard.body", "고대 천공문의 파편이 공중에 떠 있습니다. 코어가 그 진동에 반응합니다.", "A shard of an ancient sky gate hangs in the air. Your core answers its hum.");
            Add("enc.gate_shard.study", "파편을 연구한다", "Study the shard");
            Add("enc.gate_shard.study.r", "파편의 진동에서 에테르를 얻었습니다.", "The shard's hum yields aether.");
            Add("enc.gate_shard.sell", "파편을 잘라 판다", "Cut it up to sell");
            Add("enc.gate_shard.sell.r", "파편은 상인들에게 큰 값을 받을 것입니다.", "The fragments will fetch a fortune.");
            Add("enc.gate_shard.attune", "[엘프] 파편에 코어를 공명시킨다", "[Elf] Attune the core to the shard");
            Add("enc.gate_shard.attune.r", "코어가 넘치도록 채워졌지만 불안정해졌습니다.", "The core brims — and trembles.");
            Add("enc.smuggler_flotilla.title", "밀수단 선단", "THE SMUGGLER FLOTILLA");
            Add("enc.smuggler_flotilla.body", "깃발 없는 밀수선들이 거래를 제안합니다. 가격은 좋지만 질문은 받지 않습니다.", "Flagless smugglers offer a deal. The prices are good and no questions are taken.");
            Add("enc.smuggler_flotilla.ordnance", "인양물 5로 군수품 4", "4 ordnance for 5 salvage");
            Add("enc.smuggler_flotilla.ordnance.r", "군수품이 조용히 옮겨졌습니다.", "The ordnance changes hands quietly.");
            Add("enc.smuggler_flotilla.aether", "인양물 7로 에테르 4", "4 aether for 7 salvage");
            Add("enc.smuggler_flotilla.aether.r", "연료 탱크가 채워졌습니다.", "Your tanks are filled.");
            Add("enc.smuggler_flotilla.sell", "보급 2를 팔아 인양물 9", "Sell 2 supplies for 9 salvage");
            Add("enc.smuggler_flotilla.sell.r", "밀수단이 식량에 후한 값을 쳤습니다.", "The smugglers pay well for food.");
            Add("enc.smuggler_flotilla.depart", "거래하지 않는다", "Decline");
            Add("enc.smuggler_flotilla.depart.r", "밀수선들이 구름 속으로 흩어졌습니다.", "The smugglers scatter into the clouds.");
            Add("enc.guild_caravan.title", "길드 상단", "THE GUILD CARAVAN");
            Add("enc.guild_caravan.body", "무장한 상단이 폭풍을 피해 호위를 원합니다.", "An armed guild caravan wants an escort through the storm.");
            Add("enc.guild_caravan.escort", "군수품 1을 쓰며 호위한다", "Escort them (1 ordnance)");
            Add("enc.guild_caravan.escort.r", "상단이 호위비를 후하게 치렀습니다.", "The caravan pays handsomely for the escort.");
            Add("enc.guild_caravan.buy", "인양물 5로 보급 6", "6 supplies for 5 salvage");
            Add("enc.guild_caravan.buy.r", "보급이 늘었습니다.", "Supplies replenished.");
            Add("enc.guild_caravan.depart", "떠난다", "Move on");
            Add("enc.guild_caravan.depart.r", "상단은 다른 호위를 찾아 떠났습니다.", "The caravan seeks another escort.");
            Add("enc.refit_yard.title", "개장 조선소", "THE REFIT YARD");
            Add("enc.refit_yard.body", "떠돌이 조선소가 개장 서비스를 광고합니다.", "A roaming refit yard advertises its services.");
            Add("enc.refit_yard.refit", "인양물 6으로 편대 전면 보충", "Full air-wing refit for 6 salvage");
            Add("enc.refit_yard.refit.r", "편대가 정원을 채웠습니다.", "Both wings are back to full strength.");
            Add("enc.refit_yard.plating", "인양물 9로 장갑판 보강", "Armor plating for 9 salvage");
            Add("enc.refit_yard.plating.r", "새 장갑판이 선체를 감쌌습니다.", "Fresh plating wraps the hull.");
            Add("enc.refit_yard.depart", "떠난다", "Move on");
            Add("enc.refit_yard.depart.r", "조선소가 다음 손님을 부릅니다.", "The yard hails its next customer.");
            Add("enc.black_market.title", "암시장", "THE BLACK MARKET");
            Add("enc.black_market.body", "부유 암시장이 싼 에테르를 팝니다. 출처는 묻지 않는 편이 낫습니다.", "A floating black market sells cheap aether. Better not to ask where it came from.");
            Add("enc.black_market.cheap", "인양물 4로 에테르 3", "3 aether for 4 salvage");
            Add("enc.black_market.cheap.r", "출처 불명의 에테르가 탱크에 들어갔습니다.", "Aether of uncertain origin fills the tanks.");
            Add("enc.black_market.haggle", "[고블린] 흥정한다", "[Goblin] Haggle");
            Add("enc.black_market.haggle.r", "고블린의 흥정으로 덤까지 챙겼습니다.", "Goblin haggling wins a bonus.");
            Add("enc.black_market.depart", "떠난다", "Leave");
            Add("enc.black_market.depart.r", "시장의 불빛이 멀어집니다.", "The market's lights fade.");
            Add("enc.pilgrim_bazaar.title", "순례자 시장", "THE PILGRIM BAZAAR");
            Add("enc.pilgrim_bazaar.body", "순례선단이 임시 시장을 열었습니다. 사기 진작 물품과 성물이 오갑니다.", "A pilgrim fleet has opened a bazaar of comforts and holy trinkets.");
            Add("enc.pilgrim_bazaar.comforts", "보급 1로 위문품 구입", "Buy comforts for 1 supply");
            Add("enc.pilgrim_bazaar.comforts.r", "선단에 온기가 돌았습니다.", "Warmth spreads through the convoy.");
            Add("enc.pilgrim_bazaar.sell", "성물을 판다", "Sell holy trinkets");
            Add("enc.pilgrim_bazaar.sell.r", "돈은 벌었지만 순례자들의 시선이 차갑습니다.", "You profit; the pilgrims' eyes are cold.");
            Add("enc.pilgrim_bazaar.depart", "떠난다", "Leave");
            Add("enc.pilgrim_bazaar.depart.r", "시장이 문을 닫습니다.", "The bazaar closes.");
            Add("enc.mercenary_wing.title", "용병 편대", "THE MERCENARY WING");
            Add("enc.mercenary_wing.body", "용병 편대가 정비와 호위를 제안합니다. 값은 비쌉니다.", "A mercenary wing offers maintenance and escort. It is not cheap.");
            Add("enc.mercenary_wing.hire", "인양물 10으로 계약", "Hire them for 10 salvage");
            Add("enc.mercenary_wing.hire.r", "용병들이 편대를 보충하고 군수품을 나눴습니다.", "The mercenaries refit your wings and share ordnance.");
            Add("enc.mercenary_wing.ordnance", "인양물 4로 군수품 2", "2 ordnance for 4 salvage");
            Add("enc.mercenary_wing.ordnance.r", "군수품을 구입했습니다.", "Ordnance purchased.");
            Add("enc.mercenary_wing.depart", "거절한다", "Decline");
            Add("enc.mercenary_wing.depart.r", "용병들이 경례하고 떠났습니다.", "The mercenaries salute and depart.");
            Add("enc.fuel_barge.title", "연료 바지선", "THE FUEL BARGE");
            Add("enc.fuel_barge.body", "연료 바지선이 에테르를 팝니다. 식량도 받습니다.", "A fuel barge sells aether and accepts food in trade.");
            Add("enc.fuel_barge.small", "보급 3으로 에테르 3", "3 aether for 3 supplies");
            Add("enc.fuel_barge.small.r", "연료를 보충했습니다.", "Fuel topped up.");
            Add("enc.fuel_barge.big", "인양물 8로 에테르 6", "6 aether for 8 salvage");
            Add("enc.fuel_barge.big.r", "탱크가 가득 찼습니다.", "Tanks full.");
            Add("enc.fuel_barge.depart", "떠난다", "Leave");
            Add("enc.fuel_barge.depart.r", "바지선 승무원이 손을 흔듭니다.", "The barge crew wave you off.");
            Add("enc.quartermaster.title", "부패한 보급관", "THE CROOKED QUARTERMASTER");
            Add("enc.quartermaster.body", "제국 보급관이 몰래 물자를 팔겠다고 합니다.", "An imperial quartermaster offers to sell stores under the table.");
            Add("enc.quartermaster.bribe", "인양물 7로 군수품 5", "5 ordnance for 7 salvage");
            Add("enc.quartermaster.bribe.r", "군수품이 조용히 넘어왔습니다.", "The ordnance arrives quietly.");
            Add("enc.quartermaster.pose", "[인간] 감찰관 행세로 물자를 압수한다", "[Human] Pose as inspectors and seize stores");
            Add("enc.quartermaster.pose.r", "보급관은 서류를 보고 물자를 내줬습니다.", "One look at the papers and the stores are yours.");
            Add("enc.quartermaster.depart", "떠난다", "Leave");
            Add("enc.quartermaster.depart.r", "보급관이 어깨를 으쓱합니다.", "The quartermaster shrugs.");
            Add("enc.shipwright.title", "떠돌이 조선공", "THE WANDERING SHIPWRIGHT");
            Add("enc.shipwright.body", "은퇴한 조선공이 수리 대가로 인양물을 원합니다.", "A retired shipwright will patch you up for salvage.");
            Add("enc.shipwright.repair", "인양물 7로 기함 수리", "Repair the flagship for 7 salvage");
            Add("enc.shipwright.repair.r", "조선공이 선체와 구획을 손봤습니다.", "The shipwright patches hull and compartments.");
            Add("enc.shipwright.reinforce", "인양물 5로 선체 보강", "Reinforce the hull for 5 salvage");
            Add("enc.shipwright.reinforce.r", "보강재가 선체를 감쌌습니다.", "Bracing wraps the hull.");
            Add("enc.shipwright.depart", "떠난다", "Leave");
            Add("enc.shipwright.depart.r", "조선공이 다음 항구로 향합니다.", "The shipwright heads for the next port.");
            Add("enc.customs_inspection.title", "세관 검사", "THE CUSTOMS INSPECTION");
            Add("enc.customs_inspection.body", "세관선이 화물 검사를 요구합니다. 선단에 숨겨 둔 피난민이 있습니다.", "A customs cutter demands to inspect cargo. Refugees are hidden in your holds.");
            Add("enc.customs_inspection.submit", "보급 2를 '관세'로 낸다", "Pay 2 supplies in 'duties'");
            Add("enc.customs_inspection.submit.r", "세관은 서류를 보지도 않고 떠났습니다.", "Customs leaves without reading a page.");
            Add("enc.customs_inspection.hide", "피난민을 숨기고 통과한다 (60%)", "Hide the refugees and bluff (60%)");
            Add("enc.customs_inspection.hide.r", "세관은 아무것도 찾지 못했습니다.", "Customs finds nothing.");
            Add("enc.customs_inspection.hide_fail", "발각", "Discovered");
            Add("enc.customs_inspection.hide_fail.r", "피난민이 발각됐습니다. 세관선이 포문을 엽니다!", "The refugees are found. The cutter opens fire!");
            Add("enc.customs_inspection.fight", "먼저 포문을 연다", "Open fire first");
            Add("enc.customs_inspection.fight.r", "세관선이 결계를 올립니다.", "The cutter raises its ward.");
            Add("enc.loyalty_oath.title", "충성 서약", "THE LOYALTY OATH");
            Add("enc.loyalty_oath.body", "제국 선전선이 통과 조건으로 공개 충성 서약을 요구합니다.", "An imperial broadcast ship demands a public loyalty oath as the price of passage.");
            Add("enc.loyalty_oath.swear", "서약하고 연료를 받는다", "Swear and take the fuel");
            Add("enc.loyalty_oath.swear.r", "서약이 방송됐습니다. 선단은 부끄러워합니다.", "The oath is broadcast. The convoy is ashamed.");
            Add("enc.loyalty_oath.recite", "[인간] 옛 공화국의 서약을 대신 읊는다", "[Human] Recite the old republic's oath instead");
            Add("enc.loyalty_oath.recite.r", "장교는 미소를 지으며 통과를 허락했습니다.", "The officer smiles and waves you through.");
            Add("enc.loyalty_oath.refuse", "거부하고 돌파한다", "Refuse and break through");
            Add("enc.loyalty_oath.refuse.r", "선전선이 호위함을 부릅니다.", "The broadcast ship calls its escort.");
            Add("enc.bounty_hunters.title", "현상금 사냥꾼", "THE BOUNTY HUNTERS");
            Add("enc.bounty_hunters.body", "현상금 사냥꾼들이 함장의 목에 걸린 값을 들먹입니다.", "Bounty hunters name the price on your captain's head.");
            Add("enc.bounty_hunters.pay", "인양물 8로 매수한다", "Buy them off for 8 salvage");
            Add("enc.bounty_hunters.pay.r", "사냥꾼들이 돈을 세며 떠났습니다.", "The hunters leave counting coin.");
            Add("enc.bounty_hunters.intimidate", "[오크] 해병을 갑판에 세운다", "[Orc] Line the deck with marines");
            Add("enc.bounty_hunters.intimidate.r", "사냥꾼들은 다시 생각했습니다.", "The hunters reconsider.");
            Add("enc.bounty_hunters.fight", "싸운다", "Fight");
            Add("enc.bounty_hunters.fight.r", "사냥꾼선이 무장을 펼칩니다.", "The hunters run out their guns.");
            Add("enc.blockade_toll.title", "봉쇄 통행세", "THE BLOCKADE TOLL");
            Add("enc.blockade_toll.body", "제국 봉쇄선이 통행세를 요구합니다. 뒤에는 순양함이 대기 중입니다.", "An imperial blockade demands a toll. A cruiser waits behind it.");
            Add("enc.blockade_toll.pay", "에테르 1과 인양물 4를 낸다", "Pay 1 aether and 4 salvage");
            Add("enc.blockade_toll.pay.r", "봉쇄선이 길을 열었습니다.", "The blockade opens.");
            Add("enc.blockade_toll.run", "전속으로 돌파한다 (50%)", "Run the blockade (50%)");
            Add("enc.blockade_toll.run.r", "봉쇄선이 미처 반응하지 못했습니다.", "The blockade fails to react in time.");
            Add("enc.blockade_toll.run_fail", "차단", "Intercepted");
            Add("enc.blockade_toll.run_fail.r", "순양함이 앞을 막아섭니다!", "The cruiser cuts you off!");
            Add("enc.blockade_toll.fight", "순양함과 정면으로 싸운다", "Fight the cruiser head-on");
            Add("enc.blockade_toll.fight.r", "순양함이 전투 태세에 들어갑니다.", "The cruiser clears for action.");
            Add("enc.propaganda_broadcast.title", "선전 방송", "THE PROPAGANDA BROADCAST");
            Add("enc.propaganda_broadcast.body", "제국 방송이 선단 통신망을 점령해 항복을 종용합니다.", "Imperial propaganda floods the convoy channel, urging surrender.");
            Add("enc.propaganda_broadcast.jam", "군수품 1을 써 방해 전파를 쏜다", "Spend 1 ordnance to jam it");
            Add("enc.propaganda_broadcast.jam.r", "방송이 끊기자 환호가 터졌습니다.", "The broadcast dies and the convoy cheers.");
            Add("enc.propaganda_broadcast.counter", "함장이 직접 연설한다", "The captain answers on the open channel");
            Add("enc.propaganda_broadcast.counter.r", "함장의 목소리가 선단을 붙잡았습니다.", "The captain's voice holds the convoy together.");
            Add("enc.propaganda_broadcast.ignore", "무시한다", "Ignore it");
            Add("enc.propaganda_broadcast.ignore.r", "방송이 며칠간 이어졌습니다.", "The broadcast drones on for days.");
            Add("enc.reformist_courier.title", "개혁파 급사", "THE REFORMIST COURIER");
            Add("enc.reformist_courier.body", "개혁파 급사선이 추격을 받으며 도움을 청합니다.", "A reformist courier, pursued, asks for cover.");
            Add("enc.reformist_courier.help", "보급 1을 주고 숨겨 준다", "Hide them for 1 supply");
            Add("enc.reformist_courier.help.r", "급사는 비밀 연료고 좌표로 보답했습니다.", "The courier repays you with the coordinates of a hidden fuel cache.");
            Add("enc.reformist_courier.refuse", "관여하지 않는다", "Stay out of it");
            Add("enc.reformist_courier.refuse.r", "급사선이 홀로 사라졌습니다.", "The courier vanishes alone.");
            Add("enc.hostage_exchange.title", "인질 교환", "THE HOSTAGE EXCHANGE");
            Add("enc.hostage_exchange.body", "제국 초계함이 선단 출신 인질을 군수품과 바꾸자고 합니다.", "An imperial picket offers convoy hostages in exchange for ordnance.");
            Add("enc.hostage_exchange.trade", "군수품 2로 교환한다", "Trade 2 ordnance");
            Add("enc.hostage_exchange.trade.r", "인질들이 돌아왔습니다.", "The hostages come home.");
            Add("enc.hostage_exchange.assault", "강습대로 구출한다 (50%)", "Storm the picket (50%)");
            Add("enc.hostage_exchange.assault.r", "강습대가 인질을 구출했습니다.", "The boarders free the hostages.");
            Add("enc.hostage_exchange.assault_fail", "강습 실패", "Assault fails");
            Add("enc.hostage_exchange.assault_fail.r", "강습이 막혔고 초계함이 반격합니다!", "The assault is repulsed and the picket fights back!");
            Add("enc.hostage_exchange.refuse", "거절한다", "Refuse");
            Add("enc.hostage_exchange.refuse.r", "초계함이 인질을 데리고 떠났습니다.", "The picket leaves with the hostages.");
            Add("enc.spy_aboard.title", "함내 첩자", "THE SPY ABOARD");
            Add("enc.spy_aboard.body", "제국 검문관이 선단에 첩자가 있다고 경고합니다. 진심일까요?", "An imperial inspector warns that a spy hides in your convoy. Is it true?");
            Add("enc.spy_aboard.search", "보급 1을 쓰며 전수 조사한다", "Search every hold (1 supply)");
            Add("enc.spy_aboard.search.r", "첩자와 숨겨진 폭약을 찾았습니다.", "You find the spy and a hidden charge.");
            Add("enc.spy_aboard.spot", "[조인] 눈으로 찾아낸다", "[Avian] Pick the spy out by sight");
            Add("enc.spy_aboard.spot.r", "조인의 눈이 첩자를 골라냈습니다.", "Avian eyes single out the spy.");
            Add("enc.spy_aboard.ignore", "무시한다 (50%)", "Ignore the warning (50%)");
            Add("enc.spy_aboard.ignore.r", "경고는 헛소리였습니다.", "The warning was nothing.");
            Add("enc.spy_aboard.sabotage", "파괴 공작", "Sabotage");
            Add("enc.spy_aboard.sabotage.r", "첩자가 연료를 빼돌리고 코어를 흔들었습니다.", "The spy bleeds fuel and rattles the core.");
            Add("enc.pilgrim_blockade.title", "문 앞의 순례자", "THE PILGRIMS AT THE GATE");
            Add("enc.pilgrim_blockade.body", "검문소가 순례자들을 막고 있습니다. 그들은 선단의 호위를 청합니다.", "A checkpoint is holding pilgrims back. They ask to travel under your protection.");
            Add("enc.pilgrim_blockade.escort", "에테르 1을 쓰며 호위한다", "Escort them (1 aether)");
            Add("enc.pilgrim_blockade.escort.r", "순례자들이 선단에 합류했습니다.", "The pilgrims join the convoy.");
            Add("enc.pilgrim_blockade.leave", "지나친다", "Pass on");
            Add("enc.pilgrim_blockade.leave.r", "순례자들이 뒤에 남았습니다.", "The pilgrims stay behind.");
            Add("enc.ion_squall.title", "이온 스콜", "THE ION SQUALL");
            Add("enc.ion_squall.body", "이온 스콜이 전 계기를 흔듭니다. 코어가 비명을 지릅니다.", "An ion squall rattles every instrument. The core screams.");
            Add("enc.ion_squall.calm", "에테르 1을 태워 코어를 진정시킨다", "Burn 1 aether to calm the core");
            Add("enc.ion_squall.calm.r", "코어가 진정됐습니다.", "The core settles.");
            Add("enc.ion_squall.push", "그대로 밀어붙인다 (60%)", "Push through (60%)");
            Add("enc.ion_squall.push.r", "스콜을 뚫었고 잔류 에테르를 회수했습니다.", "You clear the squall and recover stray aether.");
            Add("enc.ion_squall.push_fail", "방전", "Discharge");
            Add("enc.ion_squall.push_fail.r", "방전이 선체를 태우고 코어를 흔들었습니다.", "A discharge scorches the hull and rattles the core.");
            Add("enc.static_fog.title", "정전기 안개", "THE STATIC FOG");
            Add("enc.static_fog.body", "정전기 안개가 시야를 지웁니다.", "Static fog erases all sight.");
            Add("enc.static_fog.chart", "[정찰선] 앞장서게 한다", "[Pathfinder] Send the pathfinder ahead");
            Add("enc.static_fog.chart.r", "정찰선이 안전한 길을 찾았습니다.", "The pathfinder finds a clear line.");
            Add("enc.static_fog.slow", "속도를 늦춘다 (에테르 1)", "Slow down (1 aether)");
            Add("enc.static_fog.slow.r", "천천히, 무사히 빠져나왔습니다.", "Slow and safe.");
            Add("enc.static_fog.fast", "전속으로 돌파한다 (50%)", "Full speed (50%)");
            Add("enc.static_fog.fast.r", "안개를 단숨에 벗어났습니다.", "You burst out of the fog.");
            Add("enc.static_fog.fast_fail", "충돌", "Collision");
            Add("enc.static_fog.fast_fail.r", "잔해와 충돌해 장갑이 찢겼습니다.", "You clip wreckage and lose armor.");
            Add("enc.hail_front.title", "우박 전선", "THE HAIL FRONT");
            Add("enc.hail_front.body", "주먹만 한 우박이 선단을 두드립니다.", "Fist-sized hail hammers the convoy.");
            Add("enc.hail_front.brace", "[드워프] 장갑을 세워 버틴다", "[Dwarf] Brace the plating");
            Add("enc.hail_front.brace.r", "드워프들이 장갑을 지켰습니다.", "The dwarves hold the plating.");
            Add("enc.hail_front.climb", "에테르 2로 전선 위로 오른다", "Climb above it (2 aether)");
            Add("enc.hail_front.climb.r", "우박 위의 하늘은 고요했습니다.", "Above the front, the sky is still.");
            Add("enc.hail_front.endure", "버틴다", "Endure it");
            Add("enc.hail_front.endure.r", "우박이 장갑을 두들겼습니다.", "The hail dents the armor.");
            Add("enc.aether_bloom.title", "에테르 개화", "THE AETHER BLOOM");
            Add("enc.aether_bloom.body", "폭풍 속에 에테르 꽃이 피었습니다. 눈부시고 위험합니다.", "An aether bloom opens inside the storm — dazzling and dangerous.");
            Add("enc.aether_bloom.harvest", "가운데로 들어가 채집한다", "Fly into the bloom and harvest");
            Add("enc.aether_bloom.harvest.r", "에테르가 넘치지만 코어가 비명을 지릅니다.", "Aether floods in; the core howls.");
            Add("enc.aether_bloom.skirt", "가장자리만 스친다", "Skirt the edge");
            Add("enc.aether_bloom.skirt.r", "약간의 에테르를 얻었습니다.", "A little aether gained.");
            Add("enc.aether_bloom.avoid", "피한다", "Avoid it");
            Add("enc.aether_bloom.avoid.r", "개화가 뒤에서 사그라듭니다.", "The bloom fades behind you.");
            Add("enc.lightning_choir.title", "번개 성가", "THE LIGHTNING CHOIR");
            Add("enc.lightning_choir.body", "번개가 규칙적인 화음으로 칩니다. 공명자가 귀를 기울입니다.", "Lightning strikes in regular chords. Your resonator listens.");
            Add("enc.lightning_choir.conduct", "[엘프] 화음을 지휘해 코어를 채운다", "[Elf] Conduct the chords into the core");
            Add("enc.lightning_choir.conduct.r", "번개가 코어를 채웠습니다.", "Lightning fills the core.");
            Add("enc.lightning_choir.ground", "군수품 1을 피뢰침으로 쓴다", "Sacrifice 1 ordnance as a lightning rod");
            Add("enc.lightning_choir.ground.r", "번개가 미끼를 쳤습니다.", "The lightning takes the bait.");
            Add("enc.lightning_choir.endure", "버틴다 (50%)", "Ride it out (50%)");
            Add("enc.lightning_choir.endure.r", "번개가 선단을 비껴갔습니다.", "The lightning passes you by.");
            Add("enc.lightning_choir.strike", "낙뢰", "Struck");
            Add("enc.lightning_choir.strike.r", "낙뢰가 선체를 강타했습니다.", "Lightning hammers the hull.");
            Add("enc.updraft_chasm.title", "상승기류 협곡", "THE UPDRAFT CHASM");
            Add("enc.updraft_chasm.body", "협곡에서 거대한 상승기류가 솟습니다.", "A vast updraft rises from the chasm.");
            Add("enc.updraft_chasm.high", "기류를 타고 고고도로 오른다", "Ride it to high altitude");
            Add("enc.updraft_chasm.high.r", "선단이 힘들이지 않고 고고도에 올랐습니다.", "The convoy climbs high without burning fuel.");
            Add("enc.updraft_chasm.avoid", "우회한다 (에테르 1)", "Go around (1 aether)");
            Add("enc.updraft_chasm.avoid.r", "협곡을 돌아갔습니다.", "You skirt the chasm.");
            Add("enc.cloud_reef.title", "구름 암초", "THE CLOUD REEF");
            Add("enc.cloud_reef.body", "굳은 구름 암초가 항로를 막습니다. 암초 속에 난파선이 박혀 있습니다.", "A reef of hardened cloud blocks the lane. Wrecks are lodged inside it.");
            Add("enc.cloud_reef.climb", "[고블린] 암초를 타고 잔해를 챙긴다", "[Goblin] Climb the reef for salvage");
            Add("enc.cloud_reef.climb.r", "고블린들이 잔해를 뜯어 왔습니다.", "The goblins strip the wrecks.");
            Add("enc.cloud_reef.around", "우회한다 (에테르 1)", "Go around (1 aether)");
            Add("enc.cloud_reef.around.r", "암초를 돌아갔습니다.", "You go around.");
            Add("enc.cloud_reef.risk", "틈으로 통과하며 인양한다 (55%)", "Squeeze through and salvage (55%)");
            Add("enc.cloud_reef.risk.r", "틈을 통과하며 잔해를 챙겼습니다.", "You slip through and take salvage.");
            Add("enc.cloud_reef.scrape", "긁힘", "Scraped");
            Add("enc.cloud_reef.scrape.r", "암초가 선체를 긁었습니다.", "The reef tears at the hull.");
            Add("enc.whiteout.title", "화이트아웃", "THE WHITEOUT");
            Add("enc.whiteout.body", "눈보라가 모든 것을 지웁니다. 수송선이 대열을 잃기 시작합니다.", "A blizzard erases everything. Transports begin losing formation.");
            Add("enc.whiteout.anchor", "보급 1을 쓰며 정박해 기다린다", "Anchor and wait (1 supply)");
            Add("enc.whiteout.anchor.r", "눈보라가 지나갈 때까지 기다렸습니다.", "You wait out the storm.");
            Add("enc.whiteout.press", "밀고 나간다 (60%)", "Press on (60%)");
            Add("enc.whiteout.press.r", "대열을 유지한 채 빠져나왔습니다.", "Formation holds.");
            Add("enc.whiteout.lost", "이탈", "Lost transports");
            Add("enc.whiteout.lost.r", "수송선 한 척이 대열에서 사라졌습니다.", "A transport is lost from the formation.");
            Add("enc.storm_leviathan.title", "폭풍 리바이어던", "THE STORM LEVIATHAN");
            Add("enc.storm_leviathan.body", "폭풍 속에서 거대한 그림자가 선단을 따라옵니다.", "Something vast follows the convoy inside the storm.");
            Add("enc.storm_leviathan.flee", "에테르 2로 전속 이탈", "Flee at full burn (2 aether)");
            Add("enc.storm_leviathan.flee.r", "그림자가 뒤처졌습니다.", "The shadow falls behind.");
            Add("enc.storm_leviathan.sing", "[조인] 노래로 달랜다", "[Avian] Sing to it");
            Add("enc.storm_leviathan.sing.r", "리바이어던이 노래를 따라 부르더니 멀어졌습니다.", "The leviathan answers the song and drifts away.");
            Add("enc.storm_leviathan.harpoon", "작살을 쏜다 (40%)", "Harpoon it (40%)");
            Add("enc.storm_leviathan.harpoon.r", "리바이어던이 쓰러졌고 선단이 자원을 챙겼습니다.", "The leviathan falls and the convoy strips it.");
            Add("enc.storm_leviathan.harpoon_fail", "반격", "It turns on you");
            Add("enc.storm_leviathan.harpoon_fail.r", "리바이어던이 선체를 들이받았습니다.", "The leviathan rams the hull.");
        }
    }
}
