# Generates EncounterLibrary.cs and LocalizationService.Encounters.cs from one data table,
# so choice ids and localization keys can never drift apart.
R, S, T, C, W = "Rescue", "Salvage", "Trade", "Checkpoint", "Storm"

def ch(id, ko, en, rko, ren, **fx):
    return dict(id=id, ko=ko, en=en, rko=rko, ren=ren, fx=fx)

EVENTS = [
# ---------------- RESCUE ----------------
dict(id="burning_ferry", type=R, tko="불타는 연락선", ten="THE BURNING FERRY",
 bko="엔진 화재가 번진 연락선이 구름 위를 헤맵니다. 갑판에 승객이 몰려 있고, 불길은 몇 분 안에 연료고에 닿을 것입니다.",
 ben="A ferry drifts above the clouds with an engine fire spreading toward its fuel bunker. Passengers crowd the deck; you have minutes.",
 choices=[
  ch("teams","소화반을 보내 차분히 구조한다 (보급 1)","Send fire teams and evacuate methodically (1 supply)","소화반이 불길을 잡는 동안 승객 40명이 옮겨 탔습니다.","Fire teams hold the blaze while forty passengers cross.",suppliesCost=1,survivorDelta=40,moraleDelta=5),
  ch("dash","선체를 붙이고 전원 탈출시킨다 — 위험한 접근","Lash hulls and take everyone — a dangerous approach","무모했지만 통했습니다. 70명이 살았고 선단이 환호합니다.","Reckless, but it works. Seventy are saved and the convoy cheers.",survivorDelta=70,moraleDelta=6,successChance=0.6,failureChoiceId="dash_fail"),
  ch("dash_fail","연료고 폭발","The bunker detonates","연료고가 터지며 선체가 그을렸습니다. 20명만 구했습니다.","The bunker blows; the hull is scorched and only twenty are pulled clear.",hidden=True,hullDelta=-4,survivorDelta=20,moraleDelta=-3),
  ch("leave","거리를 둔다","Keep your distance","폭발의 빛이 구름을 물들이고, 선단은 침묵합니다.","The explosion lights the clouds, and the convoy falls silent.",moraleDelta=-5)]),
dict(id="ice_locked_lifeboats", type=R, tko="결빙된 구명정", ten="ICE-LOCKED LIFEBOATS",
 bko="얼어붙은 구명정 세 척이 빙운 속에 갇혀 있습니다. 안에서 두드리는 소리가 들립니다.",
 ben="Three lifeboats hang frozen inside an ice cloud. Something knocks from within.",
 choices=[
  ch("thaw","[드워프] 용광로 배관으로 천천히 녹인다 (보급 1)","[Dwarf] Thaw them with forge lines (1 supply)","드워프 기술자들이 얼음을 녹여 30명을 무사히 데려왔습니다.","Dwarven hands melt the ice away and thirty come aboard unharmed.",requiredTag="lineage.dwarf",suppliesCost=1,survivorDelta=30,moraleDelta=4),
  ch("blast","에테르로 얼음을 깨뜨린다 (에테르 1)","Crack the ice with an aether pulse (1 aether)","얼음이 깨지고 구명정과 장비를 회수했습니다.","The ice shatters; you recover the boats and their gear.",aetherCost=1,survivorDelta=28,salvageDelta=3,moraleDelta=1),
  ch("leave","두드림을 뒤로하고 떠난다","Leave the knocking behind","두드리는 소리가 잦아들 때까지 아무도 말을 하지 않았습니다.","No one speaks until the knocking fades.",moraleDelta=-4)]),
dict(id="mutiny_transport", type=R, tko="반란 수송선", ten="THE MUTINOUS TRANSPORT",
 bko="수송선의 승무원이 선장을 가두고 선단 합류를 요구합니다. 승객들은 겁에 질려 있습니다.",
 ben="A transport's crew has locked up their captain and demand to join the convoy. The passengers are terrified.",
 choices=[
  ch("intimidate","[오크] 무장 승무원을 보내 질서를 잡는다","[Orc] Send armed crew to restore order","반란자들은 오크 해병을 보자마자 무기를 내렸습니다.","The mutineers drop their weapons the moment the orc marines board.",requiredTag="lineage.orc",survivorDelta=55,moraleDelta=2),
  ch("negotiate","보급 2를 주고 협상한다","Negotiate with 2 supplies","보급을 나누자 양측이 합류에 동의했습니다.","Shared stores bring both sides to the table.",suppliesCost=2,survivorDelta=55,moraleDelta=6),
  ch("refuse","반란선을 선단에 들이지 않는다","Refuse the mutineers","수송선은 홀로 구름 속으로 사라졌습니다.","The transport vanishes alone into the clouds.",moraleDelta=-3)]),
dict(id="plague_barge", type=R, tko="역병 바지선", ten="THE PLAGUE BARGE",
 bko="격리 깃발을 단 바지선이 도움을 청합니다. 생존자들은 열에 시달리지만 아직 걸을 수 있습니다.",
 ben="A barge flying quarantine flags pleads for help. Its survivors are feverish but still on their feet.",
 choices=[
  ch("quarantine","[병원선] 격리 병동으로 받아들인다","[Hospital ship] Take them into the isolation ward","병원선이 환자를 받았고 역병은 번지지 않았습니다.","The hospital ship takes the sick, and the fever spreads no further.",requiredTag="support.hospital",survivorDelta=60,moraleDelta=5),
  ch("take","그냥 받아들인다 — 절반의 도박","Take them anyway — a coin toss","열이 가라앉았습니다. 60명이 합류했습니다.","The fever breaks. Sixty join the convoy.",survivorDelta=60,moraleDelta=4,successChance=0.5,failureChoiceId="take_fail"),
  ch("take_fail","역병 확산","The fever spreads","역병이 선단에 번져 30명을 잃었습니다.","The fever spreads through the convoy and thirty are lost.",hidden=True,survivorDelta=-30,moraleDelta=-8),
  ch("refuse","떠난다","Leave them","바지선의 신호가 점점 약해집니다.","The barge's signal grows fainter.",moraleDelta=-4)]),
dict(id="child_choir", type=R, tko="떠도는 성가대", ten="THE WANDERING CHOIR",
 bko="음악학교 비행선이 연료를 다 쓰고 표류합니다. 아이들이 갑판에서 노래하며 신호를 보냅니다.",
 ben="A music-school airship has run dry. Children on its deck sing to signal you.",
 choices=[
  ch("take","모두 태운다 (보급 1)","Take them all aboard (1 supply)","성가대의 노래가 선단 통신망에 퍼지자 사기가 치솟았습니다.","Their song spreads across the convoy channel and morale soars.",suppliesCost=1,survivorDelta=18,moraleDelta=10),
  ch("fuel","에테르 1을 나눠 준다","Share 1 aether","비행선은 다시 떠올랐고, 아이들이 손을 흔들었습니다.","The airship lifts again; the children wave.",aetherCost=1,moraleDelta=6),
  ch("leave","지나친다","Pass them by","노래가 뒤에서 잦아듭니다.","The song fades behind you.",moraleDelta=-6)]),
dict(id="imperial_deserters", type=R, tko="제국 탈영병", ten="IMPERIAL DESERTERS",
 bko="제국 순찰정 한 척이 항복 깃발을 올렸습니다. 승무원은 탈영을 원하며 무기고를 대가로 내놓습니다.",
 ben="An imperial picket raises a surrender flag. Its crew want to desert and offer their magazine in return.",
 choices=[
  ch("accept","받아들인다","Take them in","군수품을 받았지만 선단 일부는 제국 제복을 불신합니다.","You gain ordnance, but parts of the convoy distrust the uniforms.",survivorDelta=25,ordnanceDelta=2,moraleDelta=-3),
  ch("interrogate","[인간] 옛 동료로서 항로 정보를 얻는다","[Human] Trade on old ties for route intelligence","탈영병이 제국 연료고 좌표를 넘겼습니다.","The deserters hand over the coordinates of an imperial fuel cache.",requiredTag="lineage.human",survivorDelta=25,aetherDelta=2),
  ch("refuse","거절한다","Turn them away","순찰정은 항복 깃발을 내리고 멀어졌습니다.","The picket lowers its flag and drifts away.",moraleDelta=-1)]),
dict(id="stranded_engineers", type=R, tko="조난 기술자", ten="STRANDED ENGINEERS",
 bko="부서진 정비선의 기술자들이 공구를 든 채 구조를 기다립니다.",
 ben="Engineers from a wrecked tender wait for rescue, tools in hand.",
 choices=[
  ch("take","태우고 수리를 맡긴다","Take them aboard and put them to work","기술자들이 선체 균열을 메웠습니다.","The engineers weld the flagship's cracks shut.",survivorDelta=12,hullDelta=6,moraleDelta=2),
  ch("pay","인양물 3을 주고 정식 수리를 부탁한다","Pay 3 salvage for a proper refit","자재를 받은 기술자들이 장갑판까지 손봤습니다.","With materials in hand they patch armor as well as hull.",salvageCost=3,survivorDelta=12,hullDelta=10,armorDelta=4,moraleDelta=3),
  ch("leave","떠난다","Leave them","정비선의 불빛이 꺼졌습니다.","The tender's lights go dark.",moraleDelta=-3)]),
dict(id="sky_whale_calf", type=R, tko="다친 하늘고래 새끼", ten="THE WOUNDED SKY-WHALE CALF",
 bko="그물에 얽힌 하늘고래 새끼가 선단 곁을 맴돕니다. 어미는 보이지 않습니다.",
 ben="A sky-whale calf tangled in netting circles the convoy. Its mother is nowhere in sight.",
 choices=[
  ch("calm","[조인] 노래로 달래며 그물을 푼다","[Avian] Sing it calm and cut the net","풀려난 새끼가 에테르 결정을 떨어뜨리고 떠났습니다.","Freed, the calf sheds an aether crystal and swims away.",requiredTag="lineage.avian",moraleDelta=9,aetherDelta=1),
  ch("free","보급 1을 미끼로 그물을 푼다","Lure it with 1 supply and cut the net","새끼가 선단 주위를 한 바퀴 돌고 사라졌습니다.","The calf circles the convoy once and vanishes.",suppliesCost=1,moraleDelta=5),
  ch("harvest","사냥해 자원으로 쓴다","Harvest it","자원은 얻었지만 선단은 그 울음을 잊지 못합니다.","The convoy gains salvage and cannot forget the sound it made.",salvageDelta=8,moraleDelta=-9)]),
dict(id="wreck_signal_trap", type=R, tko="부르는 난파선", ten="THE WRECK THAT CALLED",
 bko="구조 신호가 나오는 난파선 주위로 기류가 이상하게 고요합니다.",
 ben="A wreck broadcasts a distress call. The air around it is strangely still.",
 choices=[
  ch("detect","[정찰선] 주변을 먼저 훑는다","[Pathfinder] Sweep the approach first","정찰선이 매복 기뢰를 찾아냈고, 난파선은 조용히 인양됐습니다.","The pathfinder finds the ambush mines; the wreck is quietly salvaged.",requiredTag="support.pathfinder",salvageDelta=6,moraleDelta=2),
  ch("approach","그대로 접근한다","Approach directly","진짜 생존자였습니다. 50명이 합류했습니다.","The call was real. Fifty survivors join you.",survivorDelta=50,moraleDelta=5,successChance=0.55,failureChoiceId="ambush"),
  ch("ambush","매복","Ambush","난파선 뒤에서 제국 커터가 튀어나옵니다!","An imperial cutter bursts from behind the wreck!",hidden=True,startsBattle=True,moraleDelta=-2),
  ch("ignore","무시한다","Ignore the call","신호가 뒤에서 되풀이됩니다.","The signal repeats behind you.",moraleDelta=-2)]),
# ---------------- SALVAGE ----------------
dict(id="derelict_cruiser", type=S, tko="표류 순양함", ten="THE DERELICT CRUISER",
 bko="제국 순양함 한 척이 등을 꺼트린 채 표류합니다. 무장은 남아 있고 코어는 불안정하게 웅웅거립니다.",
 ben="An imperial cruiser drifts dark. Its guns are intact and its core hums unsteadily.",
 choices=[
  ch("strip","무장고를 뜯어낸다","Strip the magazines","군수품과 부품을 확보했습니다.","Ordnance and parts secured.",ordnanceDelta=4,salvageDelta=4),
  ch("core","[드워프] 코어를 추출한다","[Dwarf] Extract the core","코어가 안전하게 빠져나왔습니다.","The core comes free cleanly.",requiredTag="lineage.dwarf",aetherDelta=3,salvageDelta=3,successChance=0.7,failureChoiceId="core_fail"),
  ch("core_fail","코어 폭주","Core surge","코어가 폭주하며 선체를 태웠습니다.","The core surges and scorches the hull.",hidden=True,hullDelta=-5,instabilityDelta=15),
  ch("leave","손대지 않는다","Leave it","순양함은 계속 표류합니다.","The cruiser drifts on.")]),
dict(id="aether_geyser", type=S, tko="에테르 간헐천", ten="THE AETHER GEYSER",
 bko="구름 아래에서 에테르 기둥이 주기적으로 솟구칩니다.",
 ben="Columns of aether erupt from beneath the clouds at intervals.",
 choices=[
  ch("harvest","코어를 열어 최대한 흡수한다","Open the core and drink deep","에테르는 넘치지만 코어가 불안하게 떨립니다.","Aether overflows; the core shudders.",aetherDelta=4,instabilityDelta=20),
  ch("careful","가장자리에서 조심스럽게 채집한다","Skim the edges carefully","안전하게 에테르를 채웠습니다.","Aether gathered safely.",aetherDelta=2,instabilityDelta=5),
  ch("pass","지나간다","Pass it by","간헐천이 뒤에서 솟구칩니다.","The geyser erupts behind you.")]),
dict(id="floating_monastery", type=S, tko="부유 수도원", ten="THE FLOATING MONASTERY",
 bko="버려진 수도원이 조용히 떠 있습니다. 성유물과 낡은 기도문이 남아 있습니다.",
 ben="An abandoned monastery floats in silence, relics and worn prayers still inside.",
 choices=[
  ch("relics","성유물을 가져간다","Take the relics","성유물은 값지지만 순례자들이 눈을 돌립니다.","The relics are valuable; the pilgrims look away.",salvageDelta=10,moraleDelta=-6),
  ch("prayers","기도문을 선단에 낭독한다","Read the prayers to the convoy","오래된 기도가 선단을 달랬습니다.","Old words steady the convoy.",moraleDelta=7),
  ch("resonate","[엘프] 성가의 공명으로 코어를 채운다","[Elf] Tune the core to the chant","성가가 코어에 에테르를 불어넣었습니다.","The chant breathes aether into the core.",requiredTag="lineage.elf",aetherDelta=2,moraleDelta=4)]),
dict(id="mine_field", type=S, tko="옛 기뢰 지대", ten="THE OLD MINEFIELD",
 bko="옛 전쟁의 기뢰가 항로를 막습니다. 기뢰 사이에 침몰선 잔해가 보입니다.",
 ben="Mines from an old war block the lane. Wreckage glints between them.",
 choices=[
  ch("chart","[정찰선] 안전한 길을 그린다","[Pathfinder] Chart a safe path","정찰선이 기뢰를 해체해 군수품으로 만들었습니다.","The pathfinder defuses mines into ordnance.",requiredTag="support.pathfinder",ordnanceDelta=3,salvageDelta=5),
  ch("thread","기뢰 사이를 통과한다","Thread the mines","잔해를 챙겨 무사히 빠져나왔습니다.","You pull salvage from the wreck and slip out.",salvageDelta=9,successChance=0.6,failureChoiceId="thread_fail"),
  ch("thread_fail","기뢰 접촉","Mine strike","기뢰가 터져 장갑이 찢겼습니다.","A mine detonates against the armor.",hidden=True,hullDelta=-6,armorDelta=-4,salvageDelta=3),
  ch("avoid","우회한다 (에테르 1)","Go around (1 aether)","연료를 태워 기뢰 지대를 돌아갔습니다.","You burn fuel to skirt the field.",aetherCost=1)]),
dict(id="crashed_courier", type=S, tko="추락한 급사선", ten="THE CRASHED COURIER",
 bko="암호 장치가 켜진 채 추락한 제국 급사선이 있습니다.",
 ben="An imperial courier has crashed with its cipher engine still running.",
 choices=[
  ch("decode","암호를 풀어 보급 좌표를 찾는다","Decode it for depot coordinates","근처 보급 좌표를 얻었습니다.","You find a nearby depot's coordinates.",aetherDelta=1,suppliesDelta=2,moraleDelta=1),
  ch("sell","장치를 뜯어 팔 준비를 한다","Rip out the engine to sell","암호 장치는 값이 나갈 것입니다.","The engine will fetch a good price.",salvageDelta=7),
  ch("burn","급사선을 불태워 흔적을 지운다","Burn the courier to hide your trail","추격군이 며칠은 헤맬 것입니다.","The pursuit will chase ghosts for days.",moraleDelta=3,ordnanceDelta=1)]),
dict(id="cloud_farm", type=S, tko="구름 농장 잔해", ten="THE CLOUD FARM",
 bko="부서진 수경 농장이 떠다닙니다. 작물은 아직 살아 있고, 농부들도 일부 남았습니다.",
 ben="A broken hydroponic farm drifts by. Its crops still live, and so do a few farmers.",
 choices=[
  ch("harvest","작물을 거둔다","Harvest the crops","보급이 늘었습니다.","Supplies replenished.",suppliesDelta=6),
  ch("settle","농부들과 작물을 함께 태운다","Take the farmers and their crops","농부들이 선단 식량 관리를 맡았습니다.","The farmers take charge of the convoy's rations.",survivorDelta=20,suppliesDelta=3,moraleDelta=3),
  ch("leave","지나친다","Leave it","농장이 뒤로 멀어집니다.","The farm drifts behind.")]),
dict(id="ordnance_cache", type=S, tko="봉인된 저장고", ten="THE SEALED CACHE",
 bko="제국 군수 저장고가 봉인된 채 절벽에 박혀 있습니다.",
 ben="A sealed imperial ordnance cache is wedged into a cliff.",
 choices=[
  ch("careful","천천히 봉인을 푼다","Work the seal open slowly","군수품 일부를 회수했습니다.","Some ordnance recovered.",ordnanceDelta=3),
  ch("blast","폭파해서 연다","Blow it open","저장고가 통째로 열렸습니다.","The whole cache is yours.",ordnanceDelta=6,salvageDelta=2,successChance=0.65,failureChoiceId="blast_fail"),
  ch("blast_fail","유폭","Sympathetic detonation","저장고가 유폭해 선체가 흔들렸습니다.","The cache cooks off and rattles the hull.",hidden=True,ordnanceDelta=1,hullDelta=-3),
  ch("leave","건드리지 않는다","Leave it sealed","저장고는 절벽에 남았습니다.","The cache stays in the cliff.")]),
dict(id="sky_kelp_forest", type=S, tko="하늘 켈프 숲", ten="THE SKY-KELP FOREST",
 bko="부유 켈프 숲이 항로를 덮습니다. 켈프 사이에 새 둥지와 오래된 잔해가 있습니다.",
 ben="Floating kelp blankets the lane, nests and old wreckage hidden in its fronds.",
 choices=[
  ch("gather","켈프를 거둔다","Gather kelp","식용 켈프를 저장했습니다.","Edible kelp stored.",suppliesDelta=5),
  ch("scavenge","[고블린] 둥지와 잔해를 뒤진다","[Goblin] Pick through the nests and wreckage","고블린들이 켈프 속에서 값진 부품을 찾았습니다.","The goblins find valuable parts in the fronds.",requiredTag="lineage.goblin",salvageDelta=6,suppliesDelta=2),
  ch("push","밀고 나간다 (에테르 1)","Push through (1 aether)","켈프를 헤치고 나왔습니다.","You force a way through.",aetherCost=1,moraleDelta=1)]),
dict(id="gate_shard", type=S, tko="천공문 파편", ten="THE GATE SHARD",
 bko="고대 천공문의 파편이 공중에 떠 있습니다. 코어가 그 진동에 반응합니다.",
 ben="A shard of an ancient sky gate hangs in the air. Your core answers its hum.",
 choices=[
  ch("study","파편을 연구한다","Study the shard","파편의 진동에서 에테르를 얻었습니다.","The shard's hum yields aether.",aetherDelta=2,moraleDelta=3),
  ch("sell","파편을 잘라 판다","Cut it up to sell","파편은 상인들에게 큰 값을 받을 것입니다.","The fragments will fetch a fortune.",salvageDelta=12),
  ch("attune","[엘프] 파편에 코어를 공명시킨다","[Elf] Attune the core to the shard","코어가 넘치도록 채워졌지만 불안정해졌습니다.","The core brims — and trembles.",requiredTag="lineage.elf",aetherDelta=4,instabilityDelta=10)]),
# ---------------- TRADE ----------------
dict(id="smuggler_flotilla", type=T, tko="밀수단 선단", ten="THE SMUGGLER FLOTILLA",
 bko="깃발 없는 밀수선들이 거래를 제안합니다. 가격은 좋지만 질문은 받지 않습니다.",
 ben="Flagless smugglers offer a deal. The prices are good and no questions are taken.",
 choices=[
  ch("ordnance","인양물 5로 군수품 4","4 ordnance for 5 salvage","군수품이 조용히 옮겨졌습니다.","The ordnance changes hands quietly.",salvageCost=5,ordnanceDelta=4),
  ch("aether","인양물 7로 에테르 4","4 aether for 7 salvage","연료 탱크가 채워졌습니다.","Your tanks are filled.",salvageCost=7,aetherDelta=4),
  ch("sell","보급 2를 팔아 인양물 9","Sell 2 supplies for 9 salvage","밀수단이 식량에 후한 값을 쳤습니다.","The smugglers pay well for food.",suppliesCost=2,salvageDelta=9),
  ch("depart","거래하지 않는다","Decline","밀수선들이 구름 속으로 흩어졌습니다.","The smugglers scatter into the clouds.")]),
dict(id="guild_caravan", type=T, tko="길드 상단", ten="THE GUILD CARAVAN",
 bko="무장한 상단이 폭풍을 피해 호위를 원합니다.",
 ben="An armed guild caravan wants an escort through the storm.",
 choices=[
  ch("escort","군수품 1을 쓰며 호위한다","Escort them (1 ordnance)","상단이 호위비를 후하게 치렀습니다.","The caravan pays handsomely for the escort.",ordnanceCost=1,salvageDelta=8,moraleDelta=3),
  ch("buy","인양물 5로 보급 6","6 supplies for 5 salvage","보급이 늘었습니다.","Supplies replenished.",salvageCost=5,suppliesDelta=6),
  ch("depart","떠난다","Move on","상단은 다른 호위를 찾아 떠났습니다.","The caravan seeks another escort.")]),
dict(id="refit_yard", type=T, tko="개장 조선소", ten="THE REFIT YARD",
 bko="떠돌이 조선소가 개장 서비스를 광고합니다.",
 ben="A roaming refit yard advertises its services.",
 choices=[
  ch("refit","인양물 6으로 편대 전면 보충","Full air-wing refit for 6 salvage","편대가 정원을 채웠습니다.","Both wings are back to full strength.",salvageCost=6,refitSquadrons=True),
  ch("plating","인양물 9로 장갑판 보강","Armor plating for 9 salvage","새 장갑판이 선체를 감쌌습니다.","Fresh plating wraps the hull.",salvageCost=9,armorDelta=8),
  ch("depart","떠난다","Move on","조선소가 다음 손님을 부릅니다.","The yard hails its next customer.")]),
dict(id="black_market", type=T, tko="암시장", ten="THE BLACK MARKET",
 bko="부유 암시장이 싼 에테르를 팝니다. 출처는 묻지 않는 편이 낫습니다.",
 ben="A floating black market sells cheap aether. Better not to ask where it came from.",
 choices=[
  ch("cheap","인양물 4로 에테르 3","3 aether for 4 salvage","출처 불명의 에테르가 탱크에 들어갔습니다.","Aether of uncertain origin fills the tanks.",salvageCost=4,aetherDelta=3,moraleDelta=-2),
  ch("haggle","[고블린] 흥정한다","[Goblin] Haggle","고블린의 흥정으로 덤까지 챙겼습니다.","Goblin haggling wins a bonus.",requiredTag="lineage.goblin",salvageCost=3,aetherDelta=3,suppliesDelta=2),
  ch("depart","떠난다","Leave","시장의 불빛이 멀어집니다.","The market's lights fade.")]),
dict(id="pilgrim_bazaar", type=T, tko="순례자 시장", ten="THE PILGRIM BAZAAR",
 bko="순례선단이 임시 시장을 열었습니다. 사기 진작 물품과 성물이 오갑니다.",
 ben="A pilgrim fleet has opened a bazaar of comforts and holy trinkets.",
 choices=[
  ch("comforts","보급 1로 위문품 구입","Buy comforts for 1 supply","선단에 온기가 돌았습니다.","Warmth spreads through the convoy.",suppliesCost=1,moraleDelta=8),
  ch("sell","성물을 판다","Sell holy trinkets","돈은 벌었지만 순례자들의 시선이 차갑습니다.","You profit; the pilgrims' eyes are cold.",salvageDelta=5,moraleDelta=-3),
  ch("depart","떠난다","Leave","시장이 문을 닫습니다.","The bazaar closes.")]),
dict(id="mercenary_wing", type=T, tko="용병 편대", ten="THE MERCENARY WING",
 bko="용병 편대가 정비와 호위를 제안합니다. 값은 비쌉니다.",
 ben="A mercenary wing offers maintenance and escort. It is not cheap.",
 choices=[
  ch("hire","인양물 10으로 계약","Hire them for 10 salvage","용병들이 편대를 보충하고 군수품을 나눴습니다.","The mercenaries refit your wings and share ordnance.",salvageCost=10,ordnanceDelta=3,refitSquadrons=True),
  ch("ordnance","인양물 4로 군수품 2","2 ordnance for 4 salvage","군수품을 구입했습니다.","Ordnance purchased.",salvageCost=4,ordnanceDelta=2),
  ch("depart","거절한다","Decline","용병들이 경례하고 떠났습니다.","The mercenaries salute and depart.")]),
dict(id="fuel_barge", type=T, tko="연료 바지선", ten="THE FUEL BARGE",
 bko="연료 바지선이 에테르를 팝니다. 식량도 받습니다.",
 ben="A fuel barge sells aether and accepts food in trade.",
 choices=[
  ch("small","보급 3으로 에테르 3","3 aether for 3 supplies","연료를 보충했습니다.","Fuel topped up.",suppliesCost=3,aetherDelta=3),
  ch("big","인양물 8로 에테르 6","6 aether for 8 salvage","탱크가 가득 찼습니다.","Tanks full.",salvageCost=8,aetherDelta=6),
  ch("depart","떠난다","Leave","바지선 승무원이 손을 흔듭니다.","The barge crew wave you off.")]),
dict(id="quartermaster", type=T, tko="부패한 보급관", ten="THE CROOKED QUARTERMASTER",
 bko="제국 보급관이 몰래 물자를 팔겠다고 합니다.",
 ben="An imperial quartermaster offers to sell stores under the table.",
 choices=[
  ch("bribe","인양물 7로 군수품 5","5 ordnance for 7 salvage","군수품이 조용히 넘어왔습니다.","The ordnance arrives quietly.",salvageCost=7,ordnanceDelta=5,moraleDelta=-2),
  ch("pose","[인간] 감찰관 행세로 물자를 압수한다","[Human] Pose as inspectors and seize stores","보급관은 서류를 보고 물자를 내줬습니다.","One look at the papers and the stores are yours.",requiredTag="lineage.human",suppliesCost=1,ordnanceDelta=4,aetherDelta=1),
  ch("depart","떠난다","Leave","보급관이 어깨를 으쓱합니다.","The quartermaster shrugs.")]),
dict(id="shipwright", type=T, tko="떠돌이 조선공", ten="THE WANDERING SHIPWRIGHT",
 bko="은퇴한 조선공이 수리 대가로 인양물을 원합니다.",
 ben="A retired shipwright will patch you up for salvage.",
 choices=[
  ch("repair","인양물 7로 기함 수리","Repair the flagship for 7 salvage","조선공이 선체와 구획을 손봤습니다.","The shipwright patches hull and compartments.",salvageCost=7),
  ch("reinforce","인양물 5로 선체 보강","Reinforce the hull for 5 salvage","보강재가 선체를 감쌌습니다.","Bracing wraps the hull.",salvageCost=5,hullDelta=5,armorDelta=3),
  ch("depart","떠난다","Leave","조선공이 다음 항구로 향합니다.","The shipwright heads for the next port.")]),
# ---------------- CHECKPOINT ----------------
dict(id="customs_inspection", type=C, tko="세관 검사", ten="THE CUSTOMS INSPECTION",
 bko="세관선이 화물 검사를 요구합니다. 선단에 숨겨 둔 피난민이 있습니다.",
 ben="A customs cutter demands to inspect cargo. Refugees are hidden in your holds.",
 choices=[
  ch("submit","보급 2를 '관세'로 낸다","Pay 2 supplies in 'duties'","세관은 서류를 보지도 않고 떠났습니다.","Customs leaves without reading a page.",suppliesCost=2,moraleDelta=-1),
  ch("hide","피난민을 숨기고 통과한다","Hide the refugees and bluff","세관은 아무것도 찾지 못했습니다.","Customs finds nothing.",moraleDelta=4,successChance=0.6,failureChoiceId="hide_fail"),
  ch("hide_fail","발각","Discovered","피난민이 발각됐습니다. 세관선이 포문을 엽니다!","The refugees are found. The cutter opens fire!",hidden=True,startsBattle=True,moraleDelta=-3),
  ch("fight","먼저 포문을 연다","Open fire first","세관선이 결계를 올립니다.","The cutter raises its ward.",startsBattle=True)]),
dict(id="loyalty_oath", type=C, tko="충성 서약", ten="THE LOYALTY OATH",
 bko="제국 선전선이 통과 조건으로 공개 충성 서약을 요구합니다.",
 ben="An imperial broadcast ship demands a public loyalty oath as the price of passage.",
 choices=[
  ch("swear","서약하고 연료를 받는다","Swear and take the fuel","서약이 방송됐습니다. 선단은 부끄러워합니다.","The oath is broadcast. The convoy is ashamed.",aetherDelta=2,moraleDelta=-8),
  ch("recite","[인간] 옛 공화국의 서약을 대신 읊는다","[Human] Recite the old republic's oath instead","장교는 미소를 지으며 통과를 허락했습니다.","The officer smiles and waves you through.",requiredTag="lineage.human",moraleDelta=2,aetherDelta=1),
  ch("refuse","거부하고 돌파한다","Refuse and break through","선전선이 호위함을 부릅니다.","The broadcast ship calls its escort.",startsBattle=True,moraleDelta=3)]),
dict(id="bounty_hunters", type=C, tko="현상금 사냥꾼", ten="THE BOUNTY HUNTERS",
 bko="현상금 사냥꾼들이 함장의 목에 걸린 값을 들먹입니다.",
 ben="Bounty hunters name the price on your captain's head.",
 choices=[
  ch("pay","인양물 8로 매수한다","Buy them off for 8 salvage","사냥꾼들이 돈을 세며 떠났습니다.","The hunters leave counting coin.",salvageCost=8),
  ch("intimidate","[오크] 해병을 갑판에 세운다","[Orc] Line the deck with marines","사냥꾼들은 다시 생각했습니다.","The hunters reconsider.",requiredTag="lineage.orc",moraleDelta=4),
  ch("fight","싸운다","Fight","사냥꾼선이 무장을 펼칩니다.","The hunters run out their guns.",startsBattle=True)]),
dict(id="blockade_toll", type=C, tko="봉쇄 통행세", ten="THE BLOCKADE TOLL",
 bko="제국 봉쇄선이 통행세를 요구합니다. 뒤에는 순양함이 대기 중입니다.",
 ben="An imperial blockade demands a toll. A cruiser waits behind it.",
 choices=[
  ch("pay","에테르 1과 인양물 4를 낸다","Pay 1 aether and 4 salvage","봉쇄선이 길을 열었습니다.","The blockade opens.",aetherCost=1,salvageCost=4),
  ch("run","전속으로 돌파한다","Run the blockade","봉쇄선이 미처 반응하지 못했습니다.","The blockade fails to react in time.",moraleDelta=5,successChance=0.5,failureChoiceId="run_fail"),
  ch("run_fail","차단","Intercepted","순양함이 앞을 막아섭니다!","The cruiser cuts you off!",hidden=True,startsBattle=True,battleTier=2),
  ch("fight","순양함과 정면으로 싸운다","Fight the cruiser head-on","순양함이 전투 태세에 들어갑니다.","The cruiser clears for action.",startsBattle=True,battleTier=2)]),
dict(id="propaganda_broadcast", type=C, tko="선전 방송", ten="THE PROPAGANDA BROADCAST",
 bko="제국 방송이 선단 통신망을 점령해 항복을 종용합니다.",
 ben="Imperial propaganda floods the convoy channel, urging surrender.",
 choices=[
  ch("jam","군수품 1을 써 방해 전파를 쏜다","Spend 1 ordnance to jam it","방송이 끊기자 환호가 터졌습니다.","The broadcast dies and the convoy cheers.",ordnanceCost=1,moraleDelta=5),
  ch("counter","함장이 직접 연설한다","The captain answers on the open channel","함장의 목소리가 선단을 붙잡았습니다.","The captain's voice holds the convoy together.",moraleDelta=2),
  ch("ignore","무시한다","Ignore it","방송이 며칠간 이어졌습니다.","The broadcast drones on for days.",moraleDelta=-6)]),
dict(id="reformist_courier", type=C, tko="개혁파 급사", ten="THE REFORMIST COURIER",
 bko="개혁파 급사선이 추격을 받으며 도움을 청합니다.",
 ben="A reformist courier, pursued, asks for cover.",
 choices=[
  ch("help","보급 1을 주고 숨겨 준다","Hide them for 1 supply","급사는 비밀 연료고 좌표로 보답했습니다.","The courier repays you with the coordinates of a hidden fuel cache.",suppliesCost=1,aetherDelta=2,moraleDelta=4),
  ch("refuse","관여하지 않는다","Stay out of it","급사선이 홀로 사라졌습니다.","The courier vanishes alone.",moraleDelta=-2)]),
dict(id="hostage_exchange", type=C, tko="인질 교환", ten="THE HOSTAGE EXCHANGE",
 bko="제국 초계함이 선단 출신 인질을 군수품과 바꾸자고 합니다.",
 ben="An imperial picket offers convoy hostages in exchange for ordnance.",
 choices=[
  ch("trade","군수품 2로 교환한다","Trade 2 ordnance","인질들이 돌아왔습니다.","The hostages come home.",ordnanceCost=2,survivorDelta=40,moraleDelta=6),
  ch("assault","강습대로 구출한다","Storm the picket","강습대가 인질을 구출했습니다.","The boarders free the hostages.",survivorDelta=40,moraleDelta=8,successChance=0.5,failureChoiceId="assault_fail"),
  ch("assault_fail","강습 실패","Assault fails","강습이 막혔고 초계함이 반격합니다!","The assault is repulsed and the picket fights back!",hidden=True,startsBattle=True,moraleDelta=-3),
  ch("refuse","거절한다","Refuse","초계함이 인질을 데리고 떠났습니다.","The picket leaves with the hostages.",moraleDelta=-4)]),
dict(id="spy_aboard", type=C, tko="함내 첩자", ten="THE SPY ABOARD",
 bko="제국 검문관이 선단에 첩자가 있다고 경고합니다. 진심일까요?",
 ben="An imperial inspector warns that a spy hides in your convoy. Is it true?",
 choices=[
  ch("search","보급 1을 쓰며 전수 조사한다","Search every hold (1 supply)","첩자와 숨겨진 폭약을 찾았습니다.","You find the spy and a hidden charge.",suppliesCost=1,moraleDelta=-2,ordnanceDelta=1),
  ch("spot","[조인] 눈으로 찾아낸다","[Avian] Pick the spy out by sight","조인의 눈이 첩자를 골라냈습니다.","Avian eyes single out the spy.",requiredTag="lineage.avian",moraleDelta=5),
  ch("ignore","무시한다","Ignore the warning","경고는 헛소리였습니다.","The warning was nothing.",moraleDelta=1,successChance=0.5,failureChoiceId="sabotage"),
  ch("sabotage","파괴 공작","Sabotage","첩자가 연료를 빼돌리고 코어를 흔들었습니다.","The spy bleeds fuel and rattles the core.",hidden=True,aetherDelta=-2,instabilityDelta=10)]),
dict(id="pilgrim_blockade", type=C, tko="문 앞의 순례자", ten="THE PILGRIMS AT THE GATE",
 bko="검문소가 순례자들을 막고 있습니다. 그들은 선단의 호위를 청합니다.",
 ben="A checkpoint is holding pilgrims back. They ask to travel under your protection.",
 choices=[
  ch("escort","에테르 1을 쓰며 호위한다","Escort them (1 aether)","순례자들이 선단에 합류했습니다.","The pilgrims join the convoy.",aetherCost=1,survivorDelta=30,moraleDelta=7),
  ch("leave","지나친다","Pass on","순례자들이 뒤에 남았습니다.","The pilgrims stay behind.",moraleDelta=-2)]),
# ---------------- STORM ----------------
dict(id="ion_squall", type=W, tko="이온 스콜", ten="THE ION SQUALL",
 bko="이온 스콜이 전 계기를 흔듭니다. 코어가 비명을 지릅니다.",
 ben="An ion squall rattles every instrument. The core screams.",
 choices=[
  ch("calm","에테르 1을 태워 코어를 진정시킨다","Burn 1 aether to calm the core","코어가 진정됐습니다.","The core settles.",aetherCost=1,instabilityDelta=-15),
  ch("push","그대로 밀어붙인다","Push through","스콜을 뚫었고 잔류 에테르를 회수했습니다.","You clear the squall and recover stray aether.",aetherDelta=1,successChance=0.6,failureChoiceId="push_fail"),
  ch("push_fail","방전","Discharge","방전이 선체를 태우고 코어를 흔들었습니다.","A discharge scorches the hull and rattles the core.",hidden=True,hullDelta=-4,instabilityDelta=15)]),
dict(id="static_fog", type=W, tko="정전기 안개", ten="THE STATIC FOG",
 bko="정전기 안개가 시야를 지웁니다.",
 ben="Static fog erases all sight.",
 choices=[
  ch("chart","[정찰선] 앞장서게 한다","[Pathfinder] Send the pathfinder ahead","정찰선이 안전한 길을 찾았습니다.","The pathfinder finds a clear line.",requiredTag="support.pathfinder",moraleDelta=2,aetherDelta=1),
  ch("slow","속도를 늦춘다 (에테르 1)","Slow down (1 aether)","천천히, 무사히 빠져나왔습니다.","Slow and safe.",aetherCost=1),
  ch("fast","전속으로 돌파한다","Full speed","안개를 단숨에 벗어났습니다.","You burst out of the fog.",moraleDelta=2,successChance=0.5,failureChoiceId="fast_fail"),
  ch("fast_fail","충돌","Collision","잔해와 충돌해 장갑이 찢겼습니다.","You clip wreckage and lose armor.",hidden=True,armorDelta=-6)]),
dict(id="hail_front", type=W, tko="우박 전선", ten="THE HAIL FRONT",
 bko="주먹만 한 우박이 선단을 두드립니다.",
 ben="Fist-sized hail hammers the convoy.",
 choices=[
  ch("brace","[드워프] 장갑을 세워 버틴다","[Dwarf] Brace the plating","드워프들이 장갑을 지켰습니다.","The dwarves hold the plating.",requiredTag="lineage.dwarf",armorDelta=-1,moraleDelta=2),
  ch("climb","에테르 2로 전선 위로 오른다","Climb above it (2 aether)","우박 위의 하늘은 고요했습니다.","Above the front, the sky is still.",aetherCost=2),
  ch("endure","버틴다","Endure it","우박이 장갑을 두들겼습니다.","The hail dents the armor.",armorDelta=-5,hullDelta=-2)]),
dict(id="aether_bloom", type=W, tko="에테르 개화", ten="THE AETHER BLOOM",
 bko="폭풍 속에 에테르 꽃이 피었습니다. 눈부시고 위험합니다.",
 ben="An aether bloom opens inside the storm — dazzling and dangerous.",
 choices=[
  ch("harvest","가운데로 들어가 채집한다","Fly into the bloom and harvest","에테르가 넘치지만 코어가 비명을 지릅니다.","Aether floods in; the core howls.",aetherDelta=4,instabilityDelta=20),
  ch("skirt","가장자리만 스친다","Skirt the edge","약간의 에테르를 얻었습니다.","A little aether gained.",aetherDelta=1),
  ch("avoid","피한다","Avoid it","개화가 뒤에서 사그라듭니다.","The bloom fades behind you.")]),
dict(id="lightning_choir", type=W, tko="번개 성가", ten="THE LIGHTNING CHOIR",
 bko="번개가 규칙적인 화음으로 칩니다. 공명자가 귀를 기울입니다.",
 ben="Lightning strikes in regular chords. Your resonator listens.",
 choices=[
  ch("conduct","[엘프] 화음을 지휘해 코어를 채운다","[Elf] Conduct the chords into the core","번개가 코어를 채웠습니다.","Lightning fills the core.",requiredTag="lineage.elf",aetherDelta=3,moraleDelta=3),
  ch("ground","군수품 1을 피뢰침으로 쓴다","Sacrifice 1 ordnance as a lightning rod","번개가 미끼를 쳤습니다.","The lightning takes the bait.",ordnanceCost=1),
  ch("endure","버틴다","Ride it out","번개가 선단을 비껴갔습니다.","The lightning passes you by.",moraleDelta=1,successChance=0.5,failureChoiceId="strike"),
  ch("strike","낙뢰","Struck","낙뢰가 선체를 강타했습니다.","Lightning hammers the hull.",hidden=True,hullDelta=-5,moraleDelta=-2)]),
dict(id="updraft_chasm", type=W, tko="상승기류 협곡", ten="THE UPDRAFT CHASM",
 bko="협곡에서 거대한 상승기류가 솟습니다.",
 ben="A vast updraft rises from the chasm.",
 choices=[
  ch("high","기류를 타고 고고도로 오른다","Ride it to high altitude","선단이 힘들이지 않고 고고도에 올랐습니다.","The convoy climbs high without burning fuel.",aetherDelta=2),
  ch("avoid","우회한다 (에테르 1)","Go around (1 aether)","협곡을 돌아갔습니다.","You skirt the chasm.",aetherCost=1)]),
dict(id="cloud_reef", type=W, tko="구름 암초", ten="THE CLOUD REEF",
 bko="굳은 구름 암초가 항로를 막습니다. 암초 속에 난파선이 박혀 있습니다.",
 ben="A reef of hardened cloud blocks the lane. Wrecks are lodged inside it.",
 choices=[
  ch("climb","[고블린] 암초를 타고 잔해를 챙긴다","[Goblin] Climb the reef for salvage","고블린들이 잔해를 뜯어 왔습니다.","The goblins strip the wrecks.",requiredTag="lineage.goblin",salvageDelta=5),
  ch("around","우회한다 (에테르 1)","Go around (1 aether)","암초를 돌아갔습니다.","You go around.",aetherCost=1),
  ch("risk","틈으로 통과하며 인양한다","Squeeze through and salvage","틈을 통과하며 잔해를 챙겼습니다.","You slip through and take salvage.",salvageDelta=8,successChance=0.55,failureChoiceId="scrape"),
  ch("scrape","긁힘","Scraped","암초가 선체를 긁었습니다.","The reef tears at the hull.",hidden=True,hullDelta=-6,salvageDelta=2)]),
dict(id="whiteout", type=W, tko="화이트아웃", ten="THE WHITEOUT",
 bko="눈보라가 모든 것을 지웁니다. 수송선이 대열을 잃기 시작합니다.",
 ben="A blizzard erases everything. Transports begin losing formation.",
 choices=[
  ch("anchor","보급 1을 쓰며 정박해 기다린다","Anchor and wait (1 supply)","눈보라가 지나갈 때까지 기다렸습니다.","You wait out the storm.",suppliesCost=1,moraleDelta=1),
  ch("press","밀고 나간다","Press on","대열을 유지한 채 빠져나왔습니다.","Formation holds.",moraleDelta=2,successChance=0.6,failureChoiceId="lost"),
  ch("lost","이탈","Lost transports","수송선 한 척이 대열에서 사라졌습니다.","A transport is lost from the formation.",hidden=True,survivorDelta=-20,moraleDelta=-5)]),
dict(id="storm_leviathan", type=W, tko="폭풍 리바이어던", ten="THE STORM LEVIATHAN",
 bko="폭풍 속에서 거대한 그림자가 선단을 따라옵니다.",
 ben="Something vast follows the convoy inside the storm.",
 choices=[
  ch("flee","에테르 2로 전속 이탈","Flee at full burn (2 aether)","그림자가 뒤처졌습니다.","The shadow falls behind.",aetherCost=2),
  ch("sing","[조인] 노래로 달랜다","[Avian] Sing to it","리바이어던이 노래를 따라 부르더니 멀어졌습니다.","The leviathan answers the song and drifts away.",requiredTag="lineage.avian",moraleDelta=8,aetherDelta=1),
  ch("harpoon","작살을 쏜다","Harpoon it","리바이어던이 쓰러졌고 선단이 자원을 챙겼습니다.","The leviathan falls and the convoy strips it.",salvageDelta=15,moraleDelta=5,successChance=0.4,failureChoiceId="harpoon_fail"),
  ch("harpoon_fail","반격","It turns on you","리바이어던이 선체를 들이받았습니다.","The leviathan rams the hull.",hidden=True,hullDelta=-8,moraleDelta=-4)]),

# ================= EXPANSION: ten more per type =================
# ---------------- RESCUE ----------------
dict(id="frozen_survey_team", type=R, regions=[3], tko="얼어붙은 측량단", ten="THE FROZEN SURVEY TEAM",
 bko="빙운 고원의 관측소에서 측량단이 구조를 청합니다. 장비는 온전하지만 연료가 다 됐습니다.",
 ben="A survey team calls from an observatory on the icefield. Their instruments are intact; their fuel is gone.",
 choices=[
  ch("fetch","에테르 1을 쓰며 데려온다","Fly them out (1 aether)","측량단이 지도와 함께 합류했습니다.","The surveyors join you, charts and all.",aetherCost=1,survivorDelta=14,moraleDelta=4,salvageDelta=4),
  ch("dwarf","[드워프] 발전기를 고쳐 관측소를 살린다","[Dwarf] Repair their generator","관측소가 되살아나 앞길의 결빙 정보를 넘겼습니다.","The observatory lives again and radios icing warnings ahead.",requiredTag="lineage.dwarf",moraleDelta=6,aetherDelta=1),
  ch("leave","지나친다","Pass by","관측소의 불빛이 눈보라에 묻힙니다.","The observatory's lights vanish into the snow.",moraleDelta=-3)]),
dict(id="abyss_diving_bell", type=R, regions=[5], tko="심연의 잠수종", ten="THE ABYSSAL BELL",
 bko="구름 밑바닥으로 내려간 잠수종 선단이 케이블에 매달려 있습니다. 끌어올리려면 힘이 듭니다.",
 ben="A diving-bell expedition hangs by its cable below the cloud floor. Hauling it up will strain the engines.",
 choices=[
  ch("haul","엔진을 혹사해 끌어올린다","Haul them up","케이블이 버텼고 탐사대가 심연의 표본을 넘겼습니다.","The cable holds; the explorers hand over samples from the deep.",survivorDelta=22,salvageDelta=8,instabilityDelta=10),
  ch("cut","케이블을 끊고 떠난다","Cut the cable","선단은 아무 말 없이 항로를 계속했습니다.","No one speaks as the convoy moves on.",moraleDelta=-8),
  ch("orc","[오크] 해병이 케이블을 손으로 당긴다","[Orc] Marines haul by hand","오크들이 노래를 부르며 종을 끌어올렸습니다.","The orcs sing as they drag the bell home.",requiredTag="lineage.orc",survivorDelta=22,salvageDelta=8,moraleDelta=4)]),
dict(id="cordon_escapees", type=R, regions=[4,6], tko="봉쇄선 탈출자", ten="CORDON ESCAPEES",
 bko="제국 봉쇄선을 뚫고 나온 소형선 여러 척이 추격을 받고 있습니다.",
 ben="A handful of small craft have broken through the Imperial cordon with pursuers close behind.",
 choices=[
  ch("cover","호위하며 받아들인다","Cover them and take them in","탈출자들이 합류했지만 추격대가 위치를 알아챘습니다.","The escapees join you; the pursuit now knows where you are.",survivorDelta=36,moraleDelta=5,startsBattle=True),
  ch("decoy","군수품 1로 기만 신호를 쏜다","Fire a decoy beacon (1 ordnance)","추격대가 미끼를 물었고 탈출자들이 조용히 합류했습니다.","The pursuit takes the bait and the escapees slip aboard.",ordnanceCost=1,survivorDelta=36,moraleDelta=6),
  ch("leave","관여하지 않는다","Stay clear","소형선들이 구름 속으로 흩어졌습니다.","The craft scatter into the clouds.",moraleDelta=-4)]),
dict(id="drifting_nursery", type=R, tko="떠도는 보육선", ten="THE DRIFTING NURSERY",
 bko="보육선 한 척이 항법 장치 고장으로 표류합니다. 보호자는 둘뿐입니다.",
 ben="A nursery ship drifts with a dead navigation core. Two adults are all that watch over it.",
 choices=[
  ch("adopt","선단에 받아들인다","Bring them into the convoy","아이들이 선단 곳곳에 흩어져 새 가족을 만났습니다.","The children find new families throughout the convoy.",survivorDelta=30,moraleDelta=9,suppliesCost=1),
  ch("navigator","[조인] 항법 장치를 고쳐 스스로 가게 한다","[Avian] Fix their navigation and send them on","보육선이 안전한 항로로 떠났습니다.","The nursery ship sails on along a safe course.",requiredTag="lineage.avian",moraleDelta=6),
  ch("leave","지나친다","Pass by","선단이 침묵합니다.","The convoy falls silent.",moraleDelta=-7)]),
dict(id="wrecked_gunship", type=R, tko="난파한 포함", ten="THE WRECKED GUNSHIP",
 bko="제국 포함의 잔해에서 생존자들이 신호를 보냅니다. 무장은 대부분 온전합니다.",
 ben="Survivors signal from the wreck of an Imperial gunship. Most of its guns survived the crash.",
 choices=[
  ch("both","생존자와 무장을 모두 회수한다 (보급 1)","Recover crew and guns (1 supply)","포함 승무원이 합류했고 군수품이 늘었습니다.","The gunship's crew join you and the magazines fill.",suppliesCost=1,survivorDelta=16,ordnanceDelta=3,salvageDelta=4),
  ch("guns","무장만 뜯어간다","Strip the guns only","군수품은 얻었지만 생존자들의 눈길이 따라옵니다.","You gain ordnance; the survivors' eyes follow you.",ordnanceDelta=4,salvageDelta=6,moraleDelta=-5),
  ch("leave","떠난다","Leave","잔해가 구름 아래로 가라앉습니다.","The wreck sinks beneath the clouds.")]),
dict(id="storm_shrine_hermits", type=R, regions=[2,5], tko="폭풍 사원의 은둔자", ten="THE STORM SHRINE HERMITS",
 bko="폭풍 속 사원에 은둔자들이 남아 있습니다. 떠나기를 거부하지만 아이들은 보내려 합니다.",
 ben="Hermits keep a shrine inside the storm. They refuse to leave but will send their children with you.",
 choices=[
  ch("children","아이들을 받아들인다","Take the children","은둔자들이 축복과 함께 아이들을 보냈습니다.","The hermits send their children with a blessing.",survivorDelta=12,moraleDelta=6,aetherDelta=1),
  ch("persuade","[엘프] 폭풍 노래로 설득한다","[Elf] Persuade them with the storm-song","은둔자 전원이 선단에 합류했습니다.","Every hermit comes aboard.",requiredTag="lineage.elf",survivorDelta=28,moraleDelta=8),
  ch("leave","존중하고 떠난다","Respect their choice and leave","사원의 종소리가 뒤에서 울립니다.","The shrine's bell rings behind you.",moraleDelta=1)]),
dict(id="quarantined_liner", type=R, tko="격리된 여객선", ten="THE QUARANTINED LINER",
 bko="제국이 격리 표식을 붙인 여객선이 표류합니다. 승객들은 건강해 보입니다.",
 ben="A liner drifts with Imperial quarantine markings. Its passengers look healthy enough.",
 choices=[
  ch("inspect","[병원선] 검진 후 받아들인다","[Hospital ship] Screen and admit them","격리 표식은 정치적 낙인이었습니다. 승객 전원이 합류했습니다.","The quarantine was a political brand; every passenger joins.",requiredTag="support.hospital",survivorDelta=70,moraleDelta=6),
  ch("risk","검진 없이 받아들인다","Admit them unscreened","아무 문제도 없었습니다.","Nothing was wrong with them at all.",survivorDelta=70,moraleDelta=4,successChance=0.6,failureChoiceId="risk_fail"),
  ch("risk_fail","전염","Contagion","선단에 열병이 돌아 25명을 잃었습니다.","A fever runs through the convoy and 25 are lost.",hidden=True,survivorDelta=-25,moraleDelta=-6),
  ch("leave","떠난다","Leave them","여객선의 등불이 멀어집니다.","The liner's lamps recede.",moraleDelta=-3)]),
dict(id="lost_patrol", type=R, tko="길 잃은 순찰대", ten="THE LOST PATROL",
 bko="탈영한 제국 순찰대가 길을 잃고 연료를 구걸합니다. 무장은 없습니다.",
 ben="A deserted Imperial patrol has lost its way and begs for fuel. They carry no weapons.",
 choices=[
  ch("fuel","에테르 1을 준다","Give them 1 aether","순찰대가 감사의 표시로 항로 정보를 넘겼습니다.","The patrol repays you with route intelligence.",aetherCost=1,moraleDelta=3,salvageDelta=3),
  ch("recruit","선단에 편입시킨다","Recruit them","순찰대원들이 선단 경비를 맡았습니다.","The patrol takes up convoy guard duty.",survivorDelta=18,moraleDelta=-2,ordnanceDelta=1),
  ch("leave","돌려보낸다","Send them off","순찰대는 흩어졌습니다.","The patrol scatters.")]),
dict(id="collapsing_spire", type=R, tko="무너지는 첨탑", ten="THE COLLAPSING SPIRE",
 bko="공중 첨탑 도시가 기울고 있습니다. 주민들이 위층에 갇혀 있습니다.",
 ben="A spire-city leans further every minute. Its people are trapped on the upper floors.",
 choices=[
  ch("bridge","선체를 붙여 다리를 만든다","Bridge the gap with the hull","주민들이 선체를 건너 살아났습니다.","The people cross the hull to safety.",survivorDelta=60,moraleDelta=8,successChance=0.7,failureChoiceId="bridge_fail"),
  ch("bridge_fail","붕괴","Collapse","첨탑이 무너지며 선체를 긁었고 일부만 구했습니다.","The spire falls against the hull; only some are saved.",hidden=True,hullDelta=-6,survivorDelta=20,moraleDelta=-2),
  ch("wings","편대로 실어 나른다 (군수품 1)","Ferry them by wing (1 ordnance)","편대가 왕복하며 주민을 옮겼습니다.","The wings shuttle the people out.",ordnanceCost=1,survivorDelta=40,moraleDelta=6),
  ch("leave","떠난다","Leave","첨탑이 구름 속으로 사라집니다.","The spire disappears into the clouds.",moraleDelta=-6)]),
dict(id="throne_pilgrims_stranded", type=R, regions=[6], tko="왕좌의 순례자", ten="PILGRIMS OF THE THRONE",
 bko="천공 왕좌를 향하던 순례선단이 연료를 다 쓰고 멈췄습니다. 그들은 문을 봤다고 말합니다.",
 ben="A pilgrim fleet bound for the Sky Throne has run dry. They say they have seen the gate.",
 choices=[
  ch("share","에테르 2를 나눠 함께 간다","Share 2 aether and travel together","순례자들이 문까지의 마지막 항로를 알려 줬습니다.","The pilgrims describe the last stretch to the gate.",aetherCost=2,survivorDelta=25,moraleDelta=10),
  ch("take","순례자만 태운다","Take the pilgrims aboard","순례선은 버려졌지만 사람들은 살았습니다.","The pilgrim ships are left behind; the people live.",survivorDelta=25,moraleDelta=4),
  ch("leave","지나친다","Pass by","순례자들이 왕좌를 향해 기도합니다.","The pilgrims pray toward the throne.",moraleDelta=-4)]),
# ---------------- SALVAGE ----------------
dict(id="ice_locked_freighter", type=S, regions=[3], tko="결빙된 화물선", ten="THE ICE-LOCKED FREIGHTER",
 bko="화물선이 얼음에 갇혀 있습니다. 화물칸은 봉인된 채입니다.",
 ben="A freighter is locked in ice with its holds still sealed.",
 choices=[
  ch("thaw","천천히 녹여 화물을 꺼낸다","Thaw it slowly","보급과 자재를 회수했습니다.","Supplies and materials recovered.",suppliesDelta=5,salvageDelta=6),
  ch("blast","에테르로 얼음을 깬다 (에테르 1)","Blast the ice (1 aether)","화물 전체를 빠르게 회수했습니다.","The whole cargo comes free quickly.",aetherCost=1,suppliesDelta=6,salvageDelta=9,ordnanceDelta=1),
  ch("leave","떠난다","Leave it","화물선은 얼음 속에 남았습니다.","The freighter stays in the ice.")]),
dict(id="abyss_relic_field", type=S, regions=[5], tko="심연 유물 지대", ten="THE ABYSSAL RELIC FIELD",
 bko="구름 밑바닥에서 고대 유물이 떠오릅니다. 코어가 불안하게 공명합니다.",
 ben="Ancient relics rise from the cloud floor. Your core resonates uneasily.",
 choices=[
  ch("gather","최대한 수집한다","Gather everything","유물은 값지지만 코어가 진동합니다.","The relics are priceless; the core shudders.",salvageDelta=14,aetherDelta=2,instabilityDelta=25),
  ch("careful","[엘프] 공명을 조율하며 고른다","[Elf] Tune the resonance while choosing","코어가 안정된 채 유물을 골라냈습니다.","The core stays calm as you pick the relics.",requiredTag="lineage.elf",salvageDelta=12,aetherDelta=3),
  ch("skirt","가장자리만 훑는다","Skirt the field","약간의 유물을 얻었습니다.","A few relics gathered.",salvageDelta=5)]),
dict(id="cordon_supply_dump", type=S, regions=[4,6], tko="봉쇄선 보급소", ten="THE CORDON SUPPLY DUMP",
 bko="버려진 제국 보급소가 부표에 매달려 있습니다. 경비는 없지만 감시 장치가 있을지 모릅니다.",
 ben="An abandoned Imperial supply dump hangs from buoys. No guards, but perhaps sensors.",
 choices=[
  ch("raid","전부 털어 간다","Raid it all","감시 장치는 없었습니다. 보급소를 비웠습니다.","No sensors after all; the dump is yours.",suppliesDelta=6,ordnanceDelta=4,salvageDelta=8,successChance=0.6,failureChoiceId="raid_fail"),
  ch("raid_fail","경보","Alarm","경보가 울리고 순찰함이 나타났습니다!","An alarm sounds and a patrol arrives!",hidden=True,suppliesDelta=3,ordnanceDelta=2,startsBattle=True),
  ch("scout","[정찰선] 감시 장치를 먼저 무력화한다","[Pathfinder] Disable the sensors first","조용히 보급소를 비웠습니다.","You empty the dump in silence.",requiredTag="support.pathfinder",suppliesDelta=6,ordnanceDelta=4,salvageDelta=8),
  ch("leave","건드리지 않는다","Leave it","보급소가 뒤에서 흔들립니다.","The dump sways behind you.")]),
dict(id="whale_bone_reef", type=S, tko="고래뼈 암초", ten="THE WHALEBONE REEF",
 bko="하늘고래의 뼈로 이루어진 암초입니다. 뼈 사이에 에테르 결정이 맺혀 있습니다.",
 ben="A reef of sky-whale bone. Aether crystals cling between the ribs.",
 choices=[
  ch("mine","결정을 캔다","Mine the crystals","에테르를 얻었습니다.","Aether gained.",aetherDelta=3,salvageDelta=3),
  ch("respect","[조인] 뼈를 건드리지 않고 노래로 결정을 부른다","[Avian] Sing the crystals loose without touching the bones","결정이 스스로 떨어졌습니다.","The crystals drop on their own.",requiredTag="lineage.avian",aetherDelta=3,moraleDelta=4),
  ch("leave","지나간다","Pass by","암초가 뒤로 멀어집니다.","The reef recedes.")]),
dict(id="sunken_arsenal", type=S, tko="가라앉은 무기고", ten="THE SUNKEN ARSENAL",
 bko="구름 아래로 가라앉는 무기고가 마지막 불빛을 깜빡입니다.",
 ben="An arsenal sinking into the clouds blinks its last lights.",
 choices=[
  ch("dive","급강하해 회수한다","Dive for it","무기고를 비우고 빠져나왔습니다.","You empty the arsenal and climb out.",ordnanceDelta=6,salvageDelta=5,successChance=0.55,failureChoiceId="dive_fail"),
  ch("dive_fail","압력 손상","Pressure damage","급강하로 선체가 뒤틀렸고 일부만 회수했습니다.","The dive warps the hull; you recover a little.",hidden=True,hullDelta=-5,ordnanceDelta=2),
  ch("wings","편대를 보낸다 (군수품 1)","Send the wings (1 ordnance)","편대가 상자를 물고 돌아왔습니다.","The wings return with crates.",ordnanceCost=1,ordnanceDelta=4,salvageDelta=3),
  ch("leave","포기한다","Let it sink","무기고가 사라집니다.","The arsenal is gone.")]),
dict(id="derelict_hospital_ship", type=S, tko="버려진 병원선", ten="THE DERELICT HOSPITAL SHIP",
 bko="버려진 병원선에 의료품과 장비가 남아 있습니다.",
 ben="An abandoned hospital ship still holds medicine and equipment.",
 choices=[
  ch("medicine","의료품을 회수한다","Recover the medicine","부상자들이 치료를 받았습니다.","The wounded are treated.",moraleDelta=6,suppliesDelta=3),
  ch("equipment","장비를 뜯어 의무실을 보강한다","Strip equipment for the infirmary","의무실이 개량됐습니다.","The infirmary is upgraded.",salvageDelta=8,moraleDelta=2),
  ch("leave","떠난다","Leave","병원선이 떠돕니다.","The hospital ship drifts on.")]),
dict(id="storm_wrecked_convoy", type=S, regions=[2,5], tko="폭풍에 부서진 선단", ten="THE STORM-WRECKED CONVOY",
 bko="폭풍이 다른 피난선단을 찢어 놓았습니다. 잔해 사이에 여전히 물자가 있습니다.",
 ben="The storm has torn another refugee convoy apart. Supplies still float among the wreckage.",
 choices=[
  ch("salvage","잔해를 인양한다","Salvage the wreckage","물자를 회수했지만 선단은 침묵했습니다.","You recover supplies; the convoy is quiet.",suppliesDelta=6,salvageDelta=8,moraleDelta=-3),
  ch("honour","희생자를 기리고 일부만 가져간다","Honour the dead and take only what is needed","선단이 묵념했습니다.","The convoy holds a moment of silence.",suppliesDelta=3,salvageDelta=3,moraleDelta=4),
  ch("leave","지나간다","Pass by","잔해가 폭풍 속으로 사라집니다.","The wreckage vanishes into the storm.")]),
dict(id="throne_watchtower", type=S, regions=[6], tko="왕좌의 감시탑", ten="THE THRONE WATCHTOWER",
 bko="천공 왕좌 외곽의 고대 감시탑이 아직 작동합니다. 안에는 문의 기록이 있습니다.",
 ben="An ancient watchtower on the throne's edge still hums. Inside are records of the gate.",
 choices=[
  ch("records","기록을 연구한다","Study the records","문의 약점을 알아냈습니다. 선단이 희망을 품습니다.","You learn the gate's weakness; the convoy takes heart.",moraleDelta=10,aetherDelta=2),
  ch("strip","장치를 뜯어 판다","Strip the machinery","값진 부품을 얻었습니다.","Valuable parts recovered.",salvageDelta=14),
  ch("leave","건드리지 않는다","Leave it","감시탑이 계속 웅웅거립니다.","The tower keeps humming.")]),
dict(id="pirate_cache", type=S, tko="해적의 은닉처", ten="THE PIRATE CACHE",
 bko="암초 속에 해적의 은닉처가 있습니다. 함정이 있을 수 있습니다.",
 ben="A pirate cache is hidden in the reef. It may be trapped.",
 choices=[
  ch("goblin","[고블린] 함정을 해체하고 연다","[Goblin] Disarm the traps and open it","고블린들이 함정을 웃으며 해체했습니다.","The goblins laugh as they disarm the traps.",requiredTag="lineage.goblin",salvageDelta=12,ordnanceDelta=2),
  ch("open","그냥 연다","Open it","함정은 없었습니다.","No trap after all.",salvageDelta=10,ordnanceDelta=2,successChance=0.65,failureChoiceId="open_fail"),
  ch("open_fail","폭발","Explosion","은닉처가 폭발했습니다.","The cache explodes.",hidden=True,hullDelta=-4,salvageDelta=3),
  ch("leave","떠난다","Leave it","은닉처는 암초에 남았습니다.","The cache stays in the reef.")]),
dict(id="crystal_garden", type=S, tko="결정 정원", ten="THE CRYSTAL GARDEN",
 bko="부유 섬에 에테르 결정 정원이 자랍니다. 지키는 이는 없습니다.",
 ben="An aether-crystal garden grows on a floating isle. No one tends it.",
 choices=[
  ch("harvest","전부 수확한다","Harvest it all","에테르가 넘칩니다.","Aether overflows.",aetherDelta=4,moraleDelta=-2),
  ch("tend","일부만 거두고 나머지를 심는다","Take some and replant","정원이 다음 선단을 위해 남았습니다.","The garden will feed the next convoy.",aetherDelta=2,moraleDelta=5),
  ch("leave","지나간다","Pass by","정원이 빛납니다.","The garden glitters.")]),
# ---------------- TRADE ----------------
dict(id="ice_trading_post", type=T, regions=[3], tko="빙운 교역소", ten="THE ICEFIELD TRADING POST",
 bko="빙운 고원의 교역소가 방한 물자와 연료를 팝니다.",
 ben="A trading post on the icefield sells cold-weather stores and fuel.",
 choices=[
  ch("stores","인양물 5로 보급 6","6 supplies for 5 salvage","보급이 늘었습니다.","Supplies replenished.",salvageCost=5,suppliesDelta=6),
  ch("fuel","인양물 6으로 에테르 4","4 aether for 6 salvage","연료를 채웠습니다.","Fuel topped up.",salvageCost=6,aetherDelta=4),
  ch("depart","떠난다","Leave","교역소가 눈보라에 묻힙니다.","The post fades into the snow.")]),
dict(id="abyss_salvagers", type=T, regions=[5], tko="심연 인양꾼", ten="THE ABYSSAL SALVAGERS",
 bko="심연 인양꾼들이 값진 부품과 군수품을 팝니다. 값은 인양물뿐입니다.",
 ben="Abyssal salvagers sell prized parts and ordnance. They take only salvage.",
 choices=[
  ch("ordnance","인양물 8로 군수품 6","6 ordnance for 8 salvage","군수품이 늘었습니다.","Ordnance purchased.",salvageCost=8,ordnanceDelta=6),
  ch("plating","인양물 10으로 장갑판","Armor plating for 10 salvage","장갑이 보강됐습니다.","Armor reinforced.",salvageCost=10,armorDelta=8),
  ch("depart","떠난다","Leave","인양꾼들이 심연으로 내려갑니다.","The salvagers descend into the abyss.")]),
dict(id="cordon_smuggler_tunnel", type=T, regions=[4,6], tko="봉쇄선 밀수로", ten="THE CORDON SMUGGLER RUN",
 bko="봉쇄선을 뚫는 밀수꾼이 항로 정보와 물자를 팝니다.",
 ben="Smugglers who run the cordon sell routes and stores.",
 choices=[
  ch("route","인양물 6으로 항로 정보","Route intelligence for 6 salvage","다음 도약 비용이 줄었습니다.","The next jumps cost less.",salvageCost=6,aetherDelta=3),
  ch("stores","인양물 7로 보급 5·군수품 2","5 supplies and 2 ordnance for 7 salvage","물자를 확보했습니다.","Stores secured.",salvageCost=7,suppliesDelta=5,ordnanceDelta=2),
  ch("depart","떠난다","Leave","밀수꾼이 사라집니다.","The smugglers vanish.")]),
dict(id="throne_court_merchant", type=T, regions=[6], tko="왕좌 궁정 상인", ten="THE THRONE COURT MERCHANT",
 bko="천공 왕좌의 궁정 상인이 마지막 거래를 제안합니다. 값은 비싸지만 물건은 최고입니다.",
 ben="A merchant of the throne court offers one last trade. Expensive, but the best goods you will see.",
 choices=[
  ch("refit","인양물 12로 기함 개장","Full refit for 12 salvage","선체와 장갑이 보강됐습니다.","Hull and armor reinforced.",salvageCost=12,hullDelta=8,armorDelta=6),
  ch("wings","인양물 10으로 편대 보충","Wing refit for 10 salvage","편대가 정원을 채웠습니다.","Wings at full strength.",salvageCost=10,refitSquadrons=True),
  ch("depart","떠난다","Leave","상인이 고개를 숙입니다.","The merchant bows.")]),
dict(id="wandering_alchemist", type=T, tko="떠돌이 연금술사", ten="THE WANDERING ALCHEMIST",
 bko="연금술사가 코어 안정제를 팝니다.",
 ben="An alchemist sells core stabilisers.",
 choices=[
  ch("stabilise","인양물 5로 불안정 −30","Cut instability by 30 for 5 salvage","코어가 잠잠해졌습니다.","The core settles.",salvageCost=5,instabilityDelta=-30),
  ch("tonic","보급 1로 사기 강장제","Morale tonic for 1 supply","선단이 활기를 되찾았습니다.","The convoy perks up.",suppliesCost=1,moraleDelta=6),
  ch("depart","떠난다","Leave","연금술사가 손을 흔듭니다.","The alchemist waves.")]),
dict(id="refugee_market", type=T, tko="피난민 장터", ten="THE REFUGEE MARKET",
 bko="다른 피난선단이 장터를 열었습니다. 물물교환입니다.",
 ben="Another refugee convoy has opened a barter market.",
 choices=[
  ch("swap","군수품 2를 보급 6과 교환","Trade 2 ordnance for 6 supplies","보급이 늘었습니다.","Supplies gained.",ordnanceCost=2,suppliesDelta=6),
  ch("swap2","보급 3을 에테르 2와 교환","Trade 3 supplies for 2 aether","연료가 늘었습니다.","Fuel gained.",suppliesCost=3,aetherDelta=2),
  ch("depart","떠난다","Leave","장터가 흩어집니다.","The market disperses.")]),
dict(id="gunsmith_barge", type=T, tko="총포공 바지선", ten="THE GUNSMITH BARGE",
 bko="총포공이 군수품과 정비를 팝니다.",
 ben="A gunsmith sells ordnance and tune-ups.",
 choices=[
  ch("ordnance","인양물 5로 군수품 4","4 ordnance for 5 salvage","군수품을 구입했습니다.","Ordnance purchased.",salvageCost=5,ordnanceDelta=4),
  ch("tune","인양물 6으로 무장실 정비 (수리)","Weapons tune-up for 6 salvage","무장실이 정비됐습니다.","The weapons room is tuned.",salvageCost=6,hullDelta=3),
  ch("depart","떠난다","Leave","바지선이 멀어집니다.","The barge drifts off.")]),
dict(id="monastery_kitchens", type=T, tko="수도원 주방", ten="THE MONASTERY KITCHENS",
 bko="수도원이 순례자에게 식량을 나눕니다. 기부를 받습니다.",
 ben="A monastery feeds pilgrims and accepts donations.",
 choices=[
  ch("donate","인양물 4를 기부하고 식량을 받는다","Donate 4 salvage for food","보급과 축복을 받았습니다.","Food and a blessing.",salvageCost=4,suppliesDelta=5,moraleDelta=3),
  ch("free","식량만 받는다","Take the food only","수도사들이 조용히 식량을 건넸습니다.","The monks hand over food in silence.",suppliesDelta=3,moraleDelta=-2),
  ch("depart","떠난다","Leave","종소리가 울립니다.","A bell rings.")]),
dict(id="captains_exchange", type=T, tko="함장 교환소", ten="THE CAPTAINS' EXCHANGE",
 bko="자유 함장들이 정보와 장비를 교환하는 정박지입니다.",
 ben="An anchorage where free captains swap intelligence and gear.",
 choices=[
  ch("intel","인양물 4로 항로 정보","Route intelligence for 4 salvage","앞길의 폭풍 정보를 얻었습니다.","You learn where the storms are.",salvageCost=4,aetherDelta=2,moraleDelta=2),
  ch("human","[인간] 옛 동료와 정보를 나눈다","[Human] Trade stories with old comrades","공짜로 항로 정보와 군수품을 얻었습니다.","Free intelligence and ordnance from old friends.",requiredTag="lineage.human",aetherDelta=2,ordnanceDelta=2),
  ch("depart","떠난다","Leave","함장들이 경례합니다.","The captains salute.")]),
dict(id="scrap_auction", type=T, tko="고철 경매", ten="THE SCRAP AUCTION",
 bko="고철 경매가 열립니다. 헐값에 부품이 나오지만 품질은 복불복입니다.",
 ben="A scrap auction. Parts go cheap, quality is a gamble.",
 choices=[
  ch("bid","인양물 5로 입찰","Bid 5 salvage","좋은 부품을 낙찰받았습니다.","You win good parts.",salvageCost=5,hullDelta=6,armorDelta=4,successChance=0.6,failureChoiceId="bid_fail"),
  ch("bid_fail","불량품","Junk","부품은 쓸모없었습니다.","The parts are junk.",hidden=True),
  ch("sell","인양물을 판다","Sell scrap","인양물 6을 보급 4로 바꿨습니다.","6 salvage becomes 4 supplies.",salvageCost=6,suppliesDelta=4),
  ch("depart","떠난다","Leave","경매가 끝났습니다.","The auction closes.")]),
# ---------------- CHECKPOINT ----------------
dict(id="ice_garrison", type=C, regions=[3], tko="빙운 수비대", ten="THE ICEFIELD GARRISON",
 bko="얼어붙은 제국 수비대가 통행을 막습니다. 병사들은 추위에 지쳐 있습니다.",
 ben="A frozen Imperial garrison blocks the pass. Its soldiers are worn down by the cold.",
 choices=[
  ch("bribe","보급 2를 넘긴다","Hand over 2 supplies","수비대가 길을 열었습니다.","The garrison opens the pass.",suppliesCost=2),
  ch("dwarf","[드워프] 난방을 고쳐 주고 통과한다","[Dwarf] Fix their heating and pass","수비대가 감사하며 길을 열었습니다.","The grateful garrison waves you through.",requiredTag="lineage.dwarf",moraleDelta=4),
  ch("fight","돌파한다","Break through","수비대가 포문을 엽니다.","The garrison opens fire.",startsBattle=True)]),
dict(id="abyss_toll_keepers", type=C, regions=[5], tko="심연 통행세 징수인", ten="THE ABYSSAL TOLL KEEPERS",
 bko="심연 해협의 징수인들은 제국 소속이 아닙니다. 그들은 인양물을 원합니다.",
 ben="The toll keepers of the Abyssal Strait answer to no empire. They want salvage.",
 choices=[
  ch("pay","인양물 6을 낸다","Pay 6 salvage","징수인들이 길을 열었습니다.","The keepers open the strait.",salvageCost=6),
  ch("goblin","[고블린] 흥정으로 반값에 통과","[Goblin] Haggle to half price","징수인들이 웃으며 받아들였습니다.","The keepers accept with a grin.",requiredTag="lineage.goblin",salvageCost=3),
  ch("run","돌파한다","Run past","징수인들이 반응하지 못했습니다.","The keepers fail to react.",moraleDelta=3,successChance=0.55,failureChoiceId="run_fail"),
  ch("run_fail","기뢰","Mines","기뢰가 터졌습니다.","Mines detonate.",hidden=True,hullDelta=-5,armorDelta=-3)]),
dict(id="cordon_inquisitor", type=C, regions=[4,6], tko="봉쇄선 심문관", ten="THE CORDON INQUISITOR",
 bko="제국 심문관이 선단의 함장을 심문하겠다고 합니다.",
 ben="An Imperial inquisitor demands to question the convoy's captain.",
 choices=[
  ch("submit","심문에 응한다","Submit to questioning","심문은 길었지만 통과했습니다.","The questioning is long, but you pass.",moraleDelta=-5),
  ch("human","[인간] 옛 지위를 내세워 거절한다","[Human] Invoke old rank and refuse","심문관이 물러섰습니다.","The inquisitor backs down.",requiredTag="lineage.human",moraleDelta=4),
  ch("fight","포문을 연다","Open fire","심문선이 결계를 올립니다.","The inquisitor's ship raises its ward.",startsBattle=True,battleTier=2)]),
dict(id="throne_gatekeepers", type=C, regions=[6], tko="왕좌의 문지기", ten="THE THRONE GATEKEEPERS",
 bko="천공 왕좌의 문지기들이 시험을 요구합니다. 통과하면 문까지의 길이 열립니다.",
 ben="The throne's gatekeepers demand a trial. Pass it and the way to the gate opens.",
 choices=[
  ch("trial","시험을 치른다","Take the trial","문지기들이 길을 열고 선단을 축복했습니다.","The gatekeepers open the way and bless the convoy.",moraleDelta=10,aetherDelta=2,successChance=0.6,failureChoiceId="trial_fail"),
  ch("trial_fail","시험 실패","Trial failed","문지기들이 전투로 시험합니다!","The gatekeepers test you in battle!",hidden=True,startsBattle=True,battleTier=2),
  ch("elf","[엘프] 고대의 노래로 시험을 대신한다","[Elf] Answer with the ancient song","문지기들이 무릎을 꿇었습니다.","The gatekeepers kneel.",requiredTag="lineage.elf",moraleDelta=12,aetherDelta=2),
  ch("fight","싸운다","Fight","문지기들이 무장을 펼칩니다.","The gatekeepers arm.",startsBattle=True,battleTier=2)]),
dict(id="conscription_sweep", type=C, tko="징집 수색", ten="THE CONSCRIPTION SWEEP",
 bko="제국 징집대가 선단의 젊은이들을 요구합니다.",
 ben="An Imperial press gang demands the convoy's young.",
 choices=[
  ch("refuse","거부하고 싸운다","Refuse and fight","징집대가 포문을 엽니다.","The press gang opens fire.",startsBattle=True,moraleDelta=4),
  ch("bribe","인양물 8로 눈감게 한다","Bribe them with 8 salvage","징집대가 떠났습니다.","The press gang leaves.",salvageCost=8,moraleDelta=-2),
  ch("orc","[오크] 해병을 세워 위협한다","[Orc] Face them down with marines","징집대가 물러섰습니다.","The press gang backs off.",requiredTag="lineage.orc",moraleDelta=5)]),
dict(id="tariff_station", type=C, tko="관세 기지", ten="THE TARIFF STATION",
 bko="관세 기지가 화물의 10분의 1을 요구합니다.",
 ben="A tariff station demands a tenth of your cargo.",
 choices=[
  ch("pay","보급 1·인양물 3을 낸다","Pay 1 supply and 3 salvage","통과했습니다.","You pass.",suppliesCost=1,salvageCost=3),
  ch("forge","서류를 위조한다","Forge the manifests","위조는 통했습니다.","The forgery works.",moraleDelta=2,successChance=0.5,failureChoiceId="forge_fail"),
  ch("forge_fail","적발","Caught","위조가 적발돼 벌금을 물었습니다.","The forgery is caught and fined.",hidden=True,salvageDelta=-8,moraleDelta=-3),
  ch("fight","돌파한다","Break through","기지가 포문을 엽니다.","The station opens fire.",startsBattle=True)]),
dict(id="deserter_hunt", type=C, tko="탈영병 수색", ten="THE DESERTER HUNT",
 bko="제국군이 탈영병을 찾아 선단을 수색하려 합니다. 선단에 탈영병이 있을지도 모릅니다.",
 ben="Imperial troops want to search the convoy for deserters. There may be some aboard.",
 choices=[
  ch("allow","수색을 허락한다","Allow the search","몇 명이 끌려갔습니다.","A few are taken away.",survivorDelta=-10,moraleDelta=-6),
  ch("hide","숨긴다","Hide them","아무도 발견되지 않았습니다.","No one is found.",moraleDelta=5,successChance=0.6,failureChoiceId="hide_fail"),
  ch("hide_fail","발각","Discovered","숨긴 이들이 발각돼 전투가 시작됩니다!","The hidden are found; battle!",hidden=True,startsBattle=True),
  ch("fight","거부한다","Refuse","제국군이 무장을 펼칩니다.","The troops arm.",startsBattle=True)]),
dict(id="weather_station_seizure", type=C, tko="기상 관측소 압수", ten="THE WEATHER STATION SEIZURE",
 bko="제국이 기상 관측소를 봉쇄했습니다. 관측 자료가 있으면 폭풍을 피할 수 있습니다.",
 ben="The Empire has sealed a weather station. Its data would let you dodge the storms.",
 choices=[
  ch("buy","인양물 5로 자료를 산다","Buy the data for 5 salvage","폭풍 경로를 얻었습니다.","You learn the storm tracks.",salvageCost=5,aetherDelta=2),
  ch("avian","[조인] 하늘을 읽어 자료 없이 통과한다","[Avian] Read the sky instead","조인이 폭풍을 읽어 냈습니다.","The avian reads the storms.",requiredTag="lineage.avian",aetherDelta=1,moraleDelta=3),
  ch("leave","지나친다","Pass by","관측소가 멀어집니다.","The station recedes.")]),
dict(id="refugee_registration", type=C, tko="피난민 등록소", ten="THE REFUGEE REGISTRY",
 bko="제국 등록소가 선단 전원의 등록을 요구합니다. 등록하면 추적당합니다.",
 ben="An Imperial registry demands every soul aboard be recorded. Registered means tracked.",
 choices=[
  ch("register","등록한다","Register","추격군이 위치를 알았지만 통과했습니다.","The pursuit learns your position; you pass.",moraleDelta=-4,suppliesDelta=2),
  ch("partial","일부만 등록한다","Register only some","등록관이 눈치채지 못했습니다.","The registrar notices nothing.",successChance=0.65,failureChoiceId="partial_fail"),
  ch("partial_fail","적발","Caught","등록관이 알아채고 초계함을 불렀습니다.","The registrar calls a picket.",hidden=True,startsBattle=True),
  ch("fight","등록소를 파괴한다","Destroy the registry","등록소가 방어선을 부릅니다.","The registry calls its guards.",startsBattle=True,moraleDelta=3)]),
dict(id="admiral_parley", type=C, tko="제독의 회담", ten="THE ADMIRAL'S PARLEY",
 bko="추격군 제독이 회담을 제안합니다. 항복하면 선단은 살려 준다고 합니다.",
 ben="The pursuing admiral proposes a parley: surrender, and the convoy lives.",
 choices=[
  ch("refuse","거절하고 떠난다","Refuse and leave","제독이 침묵했습니다. 선단은 결의를 다졌습니다.","The admiral says nothing. The convoy hardens.",moraleDelta=6),
  ch("stall","시간을 끌며 정보를 캔다","Stall and probe","제독의 함대 배치를 알아냈습니다.","You learn the fleet's disposition.",aetherDelta=1,moraleDelta=2),
  ch("fight","기함을 노린다","Strike the flagship","제독의 기함이 응전합니다!","The admiral's flagship answers!",startsBattle=True,battleTier=2)]),
# ---------------- STORM ----------------
dict(id="ice_storm", type=W, regions=[3], tko="얼음 폭풍", ten="THE ICE STORM",
 bko="얼음 폭풍이 선단을 덮칩니다. 갑판이 얼어붙습니다.",
 ben="An ice storm engulfs the convoy. The decks freeze.",
 choices=[
  ch("heat","에테르 1로 갑판을 녹인다","Heat the decks (1 aether)","편대가 출격 가능 상태로 유지됐습니다.","The wings stay ready.",aetherCost=1,moraleDelta=2),
  ch("endure","버틴다","Endure","장갑에 얼음이 끼었습니다.","Ice cakes the armor.",armorDelta=-4,instabilityDelta=5),
  ch("dwarf","[드워프] 용광로 열을 돌린다","[Dwarf] Route forge heat","드워프들이 선단을 녹였습니다.","The dwarves thaw the convoy.",requiredTag="lineage.dwarf",moraleDelta=4)]),
dict(id="abyss_undertow", type=W, regions=[5], tko="심연 역류", ten="THE ABYSSAL UNDERTOW",
 bko="구름 밑바닥에서 역류가 선단을 끌어내립니다.",
 ben="An undertow from the cloud floor drags the convoy down.",
 choices=[
  ch("climb","에테르 2로 전속 상승","Climb at full burn (2 aether)","선단이 빠져나왔습니다.","The convoy pulls free.",aetherCost=2),
  ch("ride","역류를 타고 내려갔다 올라온다","Ride it down and out","심연에서 에테르를 건졌습니다.","You come up with aether from the deep.",aetherDelta=3,salvageDelta=4,successChance=0.55,failureChoiceId="ride_fail"),
  ch("ride_fail","압력","Pressure","선체가 압력에 눌렸습니다.","The hull buckles under pressure.",hidden=True,hullDelta=-7),
  ch("anchor","보급 1을 쓰며 정박한다","Anchor and wait (1 supply)","역류가 지나갔습니다.","The undertow passes.",suppliesCost=1)]),
dict(id="cordon_searchlights", type=W, regions=[4,6], tko="봉쇄선 탐조등", ten="THE CORDON SEARCHLIGHTS",
 bko="폭풍 속에서 제국 탐조등이 선단을 훑습니다.",
 ben="Imperial searchlights sweep the storm for you.",
 choices=[
  ch("dark","전등화 관제로 숨는다","Run dark","탐조등이 지나갔습니다.","The lights pass over.",instabilityDelta=5),
  ch("fast","전속으로 벗어난다 (에테르 1)","Burn out of the sweep (1 aether)","벗어났습니다.","You are clear.",aetherCost=1),
  ch("caught","그대로 간다","Press on","들키지 않았습니다.","Unseen.",successChance=0.5,failureChoiceId="caught_fail"),
  ch("caught_fail","포착","Spotted","탐조등이 선단을 잡았습니다!","The searchlights find you!",hidden=True,startsBattle=True)]),
dict(id="throne_aurora", type=W, regions=[6], tko="왕좌의 오로라", ten="THE THRONE AURORA",
 bko="천공 왕좌 위로 오로라가 흐릅니다. 코어가 노래합니다.",
 ben="An aurora flows above the Sky Throne. The core sings.",
 choices=[
  ch("bathe","오로라 속으로 들어간다","Fly into the aurora","코어가 가득 찼습니다.","The core brims.",aetherDelta=5,instabilityDelta=20,moraleDelta=5),
  ch("elf","[엘프] 오로라를 조율한다","[Elf] Tune the aurora","코어가 안정된 채 채워졌습니다.","The core fills and stays calm.",requiredTag="lineage.elf",aetherDelta=5,moraleDelta=6),
  ch("skirt","가장자리를 지난다","Skirt it","약간의 에테르를 얻었습니다.","A little aether.",aetherDelta=2)]),
dict(id="ash_cloud", type=W, tko="재 구름", ten="THE ASH CLOUD",
 bko="화산재 구름이 항로를 덮습니다. 엔진 필터가 막힙니다.",
 ben="A volcanic ash cloud covers the lane. Engine filters clog.",
 choices=[
  ch("slow","천천히 통과한다 (에테르 1)","Go slowly (1 aether)","필터를 갈며 통과했습니다.","You swap filters as you go.",aetherCost=1),
  ch("fast","단숨에 돌파한다","Punch through","엔진이 손상됐습니다.","The engines take damage.",hullDelta=-3,instabilityDelta=10),
  ch("around","우회한다 (에테르 2)","Go around (2 aether)","깨끗한 하늘로 돌아갔습니다.","Clear skies around.",aetherCost=2,moraleDelta=1)]),
dict(id="ghost_lights", type=W, tko="도깨비불", ten="THE GHOST LIGHTS",
 bko="폭풍 속에 도깨비불이 선단을 유혹합니다. 항로를 잃기 쉽습니다.",
 ben="Ghost lights in the storm lure the convoy off course.",
 choices=[
  ch("ignore","무시하고 계기 비행","Ignore them and fly by instruments","무사히 지났습니다.","Safely through.",aetherCost=1),
  ch("follow","따라간다","Follow them","도깨비불이 숨겨진 연료고로 이끌었습니다.","The lights lead to a hidden fuel cache.",aetherDelta=3,successChance=0.5,failureChoiceId="follow_fail"),
  ch("follow_fail","미로","Lost","항로를 잃고 연료를 태웠습니다.","You lose the lane and burn fuel.",hidden=True,aetherDelta=-2,moraleDelta=-3),
  ch("avian","[조인] 진짜 별을 읽는다","[Avian] Read the true stars","조인이 선단을 이끌었습니다.","The avian leads the convoy through.",requiredTag="lineage.avian",moraleDelta=3)]),
dict(id="crystal_rain", type=W, tko="결정 비", ten="THE CRYSTAL RAIN",
 bko="에테르 결정이 비처럼 쏟아집니다. 갑판을 열면 모을 수 있지만 위험합니다.",
 ben="Aether crystals fall like rain. Opening the decks would gather them — dangerously.",
 choices=[
  ch("open","갑판을 열어 모은다","Open the decks","에테르가 모였지만 갑판이 긁혔습니다.","Aether gathered; the decks are scarred.",aetherDelta=3,armorDelta=-3),
  ch("closed","갑판을 닫고 지난다","Keep the decks closed","무사히 지났습니다.","Safely through."),
  ch("goblin","[고블린] 그물로 받는다","[Goblin] Catch it in nets","고블린들이 그물 가득 결정을 받았습니다.","The goblins fill their nets.",requiredTag="lineage.goblin",aetherDelta=3,salvageDelta=3)]),
dict(id="pressure_front", type=W, tko="기압 전선", ten="THE PRESSURE FRONT",
 bko="급격한 기압 변화가 승무원을 쓰러뜨립니다.",
 ben="A violent pressure change knocks crew off their feet.",
 choices=[
  ch("medic","의무실을 가동한다 (보급 1)","Run the infirmary (1 supply)","승무원이 회복했습니다.","The crew recover.",suppliesCost=1,moraleDelta=2),
  ch("endure","버틴다","Endure","선단 일부가 앓았습니다.","Some of the convoy fall ill.",survivorDelta=-8,moraleDelta=-3),
  ch("climb","에테르 1로 고도를 바꾼다","Change altitude (1 aether)","전선을 피했습니다.","You dodge the front.",aetherCost=1)]),
dict(id="thunder_leviathan_pod", type=W, regions=[2,5], tko="천둥 리바이어던 무리", ten="THE THUNDER LEVIATHAN POD",
 bko="리바이어던 무리가 폭풍과 함께 이동합니다. 그 사이에 숨으면 추격을 따돌릴 수 있습니다.",
 ben="A pod of leviathans travels with the storm. Hiding among them could shake the pursuit.",
 choices=[
  ch("hide","무리 사이에 숨는다","Hide among them","추격군이 무리에 막혔습니다.","The pursuit is blocked by the pod.",aetherDelta=1,moraleDelta=5,successChance=0.6,failureChoiceId="hide_fail"),
  ch("hide_fail","꼬리","The tail","리바이어던의 꼬리가 선체를 쳤습니다.","A leviathan's tail strikes the hull.",hidden=True,hullDelta=-6),
  ch("avian","[조인] 노래로 무리와 함께 간다","[Avian] Sing and travel with the pod","리바이어던들이 선단을 호위했습니다.","The leviathans escort the convoy.",requiredTag="lineage.avian",moraleDelta=8,aetherDelta=1),
  ch("avoid","피한다 (에테르 1)","Avoid them (1 aether)","무리를 돌아갔습니다.","You go around the pod.",aetherCost=1)]),
dict(id="eye_of_silence", type=W, tko="침묵의 눈", ten="THE EYE OF SILENCE",
 bko="폭풍의 눈 안은 완전한 정적입니다. 승무원이 쉴 수 있습니다.",
 ben="Inside the storm's eye there is perfect silence. The crew could rest.",
 choices=[
  ch("rest","정박해 쉰다 (보급 1)","Anchor and rest (1 supply)","승무원과 선단이 회복했습니다.","Crew and convoy recover.",suppliesCost=1,moraleDelta=6,instabilityDelta=-15),
  ch("repair","쉬는 동안 수리한다 (인양물 4)","Repair while resting (4 salvage)","선체가 수리됐습니다.","The hull is patched.",salvageCost=4,hullDelta=6),
  ch("move","쉬지 않고 나간다","Move on","선단은 계속 나아갔습니다.","The convoy presses on.")]),
]

def cs_str(s): return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
def cs_val(k, v):
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, float): return f"{v}f"
    if isinstance(v, str): return cs_str(v)
    return str(v)

lib = ["using System.Collections.Generic;", "using AetherArk.Core;", "", "namespace AetherArk.Content", "{",
       "    /// <summary>Authored events beyond the five baseline encounters. Generated from tools/gen_events.py data.</summary>",
       "    public static class EncounterLibrary", "    {",
       "        public static void AddAll(Dictionary<string, EncounterDefinition> result)", "        {"]
for e in EVENTS:
    regions = e.get("regions") or []
    lib.append(f'            Event(result, "{e["id"]}", EncounterType.{e["type"]}, new int[] {{ {", ".join(map(str, regions))} }},')
    for i, c in enumerate(e["choices"]):
        fx = ", ".join(f"{k} = {cs_val(k, v)}" for k, v in c["fx"].items())
        parts = [f'id = "{c["id"]}"'] + ([fx] if fx else [])
        comma = "," if i < len(e["choices"]) - 1 else ");"
        lib.append(f'                new EncounterChoiceDefinition {{ {", ".join(parts)} }}{comma}')
lib += ["        }", "",
        "        private static void Event(Dictionary<string, EncounterDefinition> result, string id, EncounterType type, int[] regions, params EncounterChoiceDefinition[] choices)",
        "        {",
        "            var encounter = new EncounterDefinition { id = id, type = type, regions = regions, titleKey = \"enc.\" + id + \".title\", bodyKey = \"enc.\" + id + \".body\" };",
        "            for (var i = 0; i < choices.Length; i++)",
        "            {",
        "                choices[i].textKey = \"enc.\" + id + \".\" + choices[i].id;",
        "                choices[i].resultKey = \"enc.\" + id + \".\" + choices[i].id + \".r\";",
        "                encounter.choices.Add(choices[i]);",
        "            }",
        "            result[id] = encounter;",
        "        }", "    }", "}", ""]
open("/Users/hanshin/workspace/air-carrier/Assets/_Project/Scripts/Content/EncounterLibrary.cs", "w", encoding="utf-8").write("\n".join(lib))

loc = ["namespace AetherArk.Content", "{",
       "    /// <summary>Event strings. Generated from tools/gen_events.py data; keep in sync with EncounterLibrary.</summary>",
       "    public sealed partial class LocalizationService", "    {",
       "        private void AddEncounterStrings()", "        {"]
for e in EVENTS:
    loc.append(f'            Add("enc.{e["id"]}.title", {cs_str(e["tko"])}, {cs_str(e["ten"])});')
    loc.append(f'            Add("enc.{e["id"]}.body", {cs_str(e["bko"])}, {cs_str(e["ben"])});')
    for c in e["choices"]:
        loc.append(f'            Add("enc.{e["id"]}.{c["id"]}", {cs_str(c["ko"])}, {cs_str(c["en"])});')
        loc.append(f'            Add("enc.{e["id"]}.{c["id"]}.r", {cs_str(c["rko"])}, {cs_str(c["ren"])});')
loc += ["        }", "    }", "}", ""]
open("/Users/hanshin/workspace/air-carrier/Assets/_Project/Scripts/Content/LocalizationService.Encounters.cs", "w", encoding="utf-8").write("\n".join(loc))
from collections import Counter
print("events:", len(EVENTS), Counter(e["type"] for e in EVENTS))
